DQMCore: dqm4hep::core::GenericEvent Class Reference
dqm4hep::core::GenericEvent Class Reference
GenericEvent class.
#include <GenericEvent.h>
Public Member Functions
GenericEvent ()
Constructor.
~GenericEvent ()
Destructor.
template<typename T >
StatusCode setValues (const std::string &key, const T &vals)
Set a vector of values identified by key.
template<typename T >
StatusCode getValues (const std::string &key, T &vals) const
Get a vector of values identified by key.
template<>
StatusCode setValues (const std::string &key, const IntVector &vals)
template<>
StatusCode setValues (const std::string &key, const FloatVector &vals)
template<>
StatusCode setValues (const std::string &key, const DoubleVector &vals)
template<>
StatusCode setValues (const std::string &key, const StringVector &vals)
template<>
StatusCode getValues (const std::string &key, IntVector &vals) const
template<>
StatusCode getValues (const std::string &key, FloatVector &vals) const
template<>
StatusCode getValues (const std::string &key, DoubleVector &vals) const
template<>
StatusCode getValues (const std::string &key, StringVector &vals) const
Private Types
typedef std::map< std::string,
IntVector > IntVectorMap
typedef std::map< std::string,
FloatVector > FloatVectorMap
typedef std::map< std::string,
DoubleVector > DoubleVectorMap
typedef std::map< std::string,
StringVector > StringVectorMap
Private Member Functions
template<typename T >
StatusCode setValuesPrivate (const std::string &key, std::map< std::string, T > &valuesMap, const T &vals)
Workhorse of GenericEvent::setValues(key, vals)
template<typename T >
StatusCode getValuesPrivate (const std::string &key, std::map< std::string, T > &valuesMap, T &vals) const
Workhorse of GenericEvent::getValues(key, vals)
Private Attributes
IntVectorMap m_intValues
FloatVectorMap m_floatValues
DoubleVectorMap m_doubleValues
StringVectorMap m_stringValues
Friends
class GenericEventStreamer
Detailed Description
GenericEvent class.
Basic event implementation with a list of vectors stored in maps. See GenericEvent::setValues() and GenericEvent::getValues() to respectively set and get values into these map.
To get this kind of event within an analysis module, proceed like this :
StatusCode MyModule::processEvent(Event *pEvent) {
  GenericEvent *pGenericEvent = pEvent->getEvent<GenericEvent>();
    // Access contents via getValues()
  FloatVector temperatures;
  pGenericEvent->getValues("Temperature", temperatures);
  // ...
}
Definition at line 68 of file GenericEvent.h.
Member Typedef Documentation
typedef std::map<std::string, DoubleVector> dqm4hep::core::GenericEvent::DoubleVectorMap private
Definition at line 119 of file GenericEvent.h.
typedef std::map<std::string, FloatVector> dqm4hep::core::GenericEvent::FloatVectorMap private
Definition at line 118 of file GenericEvent.h.
typedef std::map<std::string, IntVector> dqm4hep::core::GenericEvent::IntVectorMap private
Definition at line 117 of file GenericEvent.h.
typedef std::map<std::string, StringVector> dqm4hep::core::GenericEvent::StringVectorMap private
Definition at line 120 of file GenericEvent.h.
Constructor & Destructor Documentation
dqm4hep::core::GenericEvent::GenericEvent ()
Constructor.
Definition at line 39 of file GenericEvent.cc.
     {
       /* nop */
     }
dqm4hep::core::GenericEvent::~GenericEvent ()
Destructor.
Definition at line 46 of file GenericEvent.cc.
     {
       /* nop */
     }
Member Function Documentation
template<> StatusCode dqm4hep::core::GenericEvent::getValues (const std::string & key, IntVector & vals) const
Definition at line 86 of file GenericEvent.cc.
References getValuesPrivate(), and m_intValues.
     {
       return this->getValuesPrivate(key, m_intValues, vals);
     }
template<> StatusCode dqm4hep::core::GenericEvent::getValues (const std::string & key, FloatVector & vals) const
Definition at line 94 of file GenericEvent.cc.
References getValuesPrivate(), and m_floatValues.
     {
       return this->getValuesPrivate(key, m_floatValues, vals);
     }
template<> StatusCode dqm4hep::core::GenericEvent::getValues (const std::string & key, DoubleVector & vals) const
Definition at line 102 of file GenericEvent.cc.
References getValuesPrivate(), and m_doubleValues.
     {
       return this->getValuesPrivate(key, m_doubleValues, vals);
     }
template<typename T > StatusCode dqm4hep::core::GenericEvent::getValues (const std::string & key, T & vals) const
Get a vector of values identified by key.
Attention : Template interface restricted to the following types :
vector<int>
vector<float>
vector<double>
vector<string> In case where an another parameter type is passed, the code will compile but will do nothing and return failure.
Definition at line 177 of file GenericEvent.h.
     {
       return STATUS_CODE_FAILURE;
     }
template<> StatusCode dqm4hep::core::GenericEvent::getValues (const std::string & key, StringVector & vals) const
Definition at line 110 of file GenericEvent.cc.
References getValuesPrivate(), and m_stringValues.
     {
       return this->getValuesPrivate(key, m_stringValues, vals);
     }
template<typename T > StatusCode dqm4hep::core::GenericEvent::getValuesPrivate (const std::string & key, std::map< std::string, T > & valuesMap, T & vals) const inline private
Workhorse of GenericEvent::getValues(key, vals)
Definition at line 194 of file GenericEvent.h.
Referenced by getValues().
     {
       vals = valuesMap[ key ];
       return STATUS_CODE_SUCCESS;
     }
template<> StatusCode dqm4hep::core::GenericEvent::setValues (const std::string & key, const IntVector & vals)
Definition at line 54 of file GenericEvent.cc.
References m_intValues, and setValuesPrivate().
     {
       return this->setValuesPrivate(key, m_intValues, vals);
     }
template<> StatusCode dqm4hep::core::GenericEvent::setValues (const std::string & key, const FloatVector & vals)
Definition at line 62 of file GenericEvent.cc.
References m_floatValues, and setValuesPrivate().
     {
       return this->setValuesPrivate(key, m_floatValues, vals);
     }
template<> StatusCode dqm4hep::core::GenericEvent::setValues (const std::string & key, const DoubleVector & vals)
Definition at line 70 of file GenericEvent.cc.
References m_doubleValues, and setValuesPrivate().
     {
       return this->setValuesPrivate(key, m_doubleValues, vals);
     }
template<> StatusCode dqm4hep::core::GenericEvent::setValues (const std::string & key, const StringVector & vals)
Definition at line 78 of file GenericEvent.cc.
References m_stringValues, and setValuesPrivate().
     {
       return this->setValuesPrivate(key, m_stringValues, vals);
     }
template<typename T > StatusCode dqm4hep::core::GenericEvent::setValues (const std::string & key, const T & vals)
Set a vector of values identified by key.
Attention : Template interface restricted to the following types :
vector<int>
vector<float>
vector<double>
vector<string> In case where an another parameter type is passed, the code will compile but will do nothing and return failure.
Definition at line 169 of file GenericEvent.h.
     {
       return STATUS_CODE_FAILURE;
     }
template<typename T > StatusCode dqm4hep::core::GenericEvent::setValuesPrivate (const std::string & key, std::map< std::string, T > & valuesMap, const T & vals) inline private
Workhorse of GenericEvent::setValues(key, vals)
Definition at line 185 of file GenericEvent.h.
Referenced by setValues().
     {
       valuesMap[ key ] = vals;
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class GenericEventStreamer friend
Definition at line 127 of file GenericEvent.h.
Member Data Documentation
DoubleVectorMap dqm4hep::core::GenericEvent::m_doubleValues mutable private
Definition at line 124 of file GenericEvent.h.
Referenced by getValues(), dqm4hep::core::GenericEventStreamer::read(), setValues(), and dqm4hep::core::GenericEventStreamer::write().
FloatVectorMap dqm4hep::core::GenericEvent::m_floatValues mutable private
Definition at line 123 of file GenericEvent.h.
Referenced by getValues(), dqm4hep::core::GenericEventStreamer::read(), setValues(), and dqm4hep::core::GenericEventStreamer::write().
IntVectorMap dqm4hep::core::GenericEvent::m_intValues mutable private
Definition at line 122 of file GenericEvent.h.
Referenced by getValues(), dqm4hep::core::GenericEventStreamer::read(), setValues(), and dqm4hep::core::GenericEventStreamer::write().
StringVectorMap dqm4hep::core::GenericEvent::m_stringValues mutable private
Definition at line 125 of file GenericEvent.h.
Referenced by getValues(), setValues(), and dqm4hep::core::GenericEventStreamer::write().
The documentation for this class was generated from the following files:
GenericEvent.h
GenericEvent.cc