DQMCore: dqm4hep::core::StreamingHelper Class Reference
dqm4hep::core::StreamingHelper Class Reference
#include <StreamingHelper.h>
Static Public Member Functions
template<typename T >
static xdrstream::Status read (xdrstream::IODevice *pDevice, T &stlContainer)
template<typename T >
static xdrstream::Status write (xdrstream::IODevice *pDevice, const T &stlContainer)
template<typename KeyType , typename ValueType >
static xdrstream::Status read (xdrstream::IODevice *pDevice, std::map< KeyType, ValueType > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status write (xdrstream::IODevice *pDevice, const std::map< KeyType, ValueType > &stlMap)
template<typename KeyType , typename VectorType >
static xdrstream::Status read (xdrstream::IODevice *pDevice, std::map< KeyType, std::vector< VectorType > > &stlMap)
template<typename KeyType , typename VectorType >
static xdrstream::Status write (xdrstream::IODevice *pDevice, const std::map< KeyType, std::vector< VectorType > > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status read (xdrstream::IODevice *pDevice, std::multimap< KeyType, ValueType > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status write (xdrstream::IODevice *pDevice, const std::multimap< KeyType, ValueType > &stlMap)
template<typename T >
static xdrstream::Status readStreamables (xdrstream::IODevice *pDevice, T &stlContainer)
template<typename T >
static xdrstream::Status writeStreamables (xdrstream::IODevice *pDevice, const T &stlContainer)
template<typename KeyType , typename ValueType >
static xdrstream::Status readStreamables (xdrstream::IODevice *pDevice, std::map< KeyType, ValueType > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status writeStreamables (xdrstream::IODevice *pDevice, const std::map< KeyType, ValueType > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status readStreamables (xdrstream::IODevice *pDevice, std::multimap< KeyType, ValueType > &stlMap)
template<typename KeyType , typename ValueType >
static xdrstream::Status writeStreamables (xdrstream::IODevice *pDevice, const std::multimap< KeyType, ValueType > &stlMap)
Detailed Description
Definition at line 43 of file StreamingHelper.h.
Member Function Documentation
template<typename T > xdrstream::Status dqm4hep::core::StreamingHelper::read (xdrstream::IODevice * pDevice, T & stlContainer) inline static
Definition at line 121 of file StreamingHelper.h.
Referenced by read(), dqm4hep::core::GenericEventStreamer::read(), and dqm4hep::core::Run::stream().
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i= 0 ; i<nRead ; i++ )
       {
         typename T::value_type value;
         XDR_STREAM( pDevice->read( & value ) )
         stlContainer.insert( stlContainer.end() , value );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::read (xdrstream::IODevice * pDevice, std::map< KeyType, ValueType > & stlMap) inline static
Definition at line 154 of file StreamingHelper.h.
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i=0 ; i<nRead ; i++ )
       {
         KeyType key;
         ValueType value;
         XDR_STREAM( pDevice->read( & key ) )
         XDR_STREAM( pDevice->read( & value ) )
         stlContainer.insert( stlContainer.end() , typename std::map<KeyType, ValueType>::value_type(key, value) );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename VectorType > xdrstream::Status dqm4hep::core::StreamingHelper::read (xdrstream::IODevice * pDevice, std::map< KeyType, std::vector< VectorType > > & stlMap) inline static
Definition at line 194 of file StreamingHelper.h.
References read().
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i=0 ; i<nRead ; i++ )
       {
         KeyType key;
         std::vector<VectorType> value;
         XDR_STREAM( pDevice->read( & key ) )
         XDR_STREAM( StreamingHelper::read( pDevice , value ) )
         stlContainer.insert( stlContainer.end() , typename std::map<KeyType, std::vector<VectorType> >::value_type(key, value) );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::read (xdrstream::IODevice * pDevice, std::multimap< KeyType, ValueType > & stlMap) inline static
Definition at line 234 of file StreamingHelper.h.
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i= 0 ; i<nRead ; i++ )
       {
         KeyType key;
         ValueType value;
         XDR_STREAM( pDevice->read( & key ) )
         XDR_STREAM( pDevice->read( & value ) )
         stlContainer.insert( stlContainer.end() , typename std::multimap<KeyType, ValueType>::value_type(key, value) );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename T > xdrstream::Status dqm4hep::core::StreamingHelper::readStreamables (xdrstream::IODevice * pDevice, T & stlContainer) inline static
Definition at line 274 of file StreamingHelper.h.
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i= 0 ; i<nRead ; i++ )
       {
         T *pObject = new T();
         XDR_STREAM( pObject->stream( xdrstream::XDR_READ_STREAM , pDevice ) )
         stlContainer.insert( stlContainer.end() , pObject );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::readStreamables (xdrstream::IODevice * pDevice, std::map< KeyType, ValueType > & stlMap) inline static
Definition at line 307 of file StreamingHelper.h.
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i= 0 ; i<nRead ; i++ )
       {
         KeyType key;
         XDR_STREAM( pDevice->read( & key ) )
         ValueType *pObject = new ValueType();
         XDR_STREAM( pObject->stream( xdrstream::XDR_READ_STREAM , pDevice ) )
         typename std::map<KeyType, ValueType>::value_type value( key , pObject );
         stlContainer.insert( stlContainer.end() , value );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::readStreamables (xdrstream::IODevice * pDevice, std::multimap< KeyType, ValueType > & stlMap) inline static
Definition at line 348 of file StreamingHelper.h.
     {
       uint32_t nRead = 0;
       XDR_STREAM( pDevice->read( & nRead ) )
       for( uint32_t i= 0 ; i<nRead ; i++ )
       {
         KeyType key;
         XDR_STREAM( pDevice->read( & key ) )
         ValueType *pObject = new ValueType();
         XDR_STREAM( pObject->stream( xdrstream::XDR_READ_STREAM , pDevice ) )
         typename std::multimap<KeyType, ValueType>::value_type value( key , pObject );
         stlContainer.insert( stlContainer.end() , value );
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename T > xdrstream::Status dqm4hep::core::StreamingHelper::write (xdrstream::IODevice * pDevice, const T & stlContainer) inline static
Definition at line 139 of file StreamingHelper.h.
Referenced by dqm4hep::core::Run::stream(), write(), and dqm4hep::core::GenericEventStreamer::write().
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename T::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
         XDR_STREAM( pDevice->write( & ( *iter ) ) )
         return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::write (xdrstream::IODevice * pDevice, const std::map< KeyType, ValueType > & stlMap) inline static
Definition at line 176 of file StreamingHelper.h.
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename std::map<KeyType, ValueType>::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
       {
         XDR_STREAM( pDevice->write( & ( iter->first ) ) )
         XDR_STREAM( pDevice->write( & ( iter->second ) ) )
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename VectorType > xdrstream::Status dqm4hep::core::StreamingHelper::write (xdrstream::IODevice * pDevice, const std::map< KeyType, std::vector< VectorType > > & stlMap) inline static
Definition at line 216 of file StreamingHelper.h.
References write().
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename std::map<KeyType, std::vector<VectorType> >::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
       {
         XDR_STREAM( pDevice->write( & ( iter->first ) ) )
         XDR_STREAM( StreamingHelper::write( pDevice , iter->second ) )
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::write (xdrstream::IODevice * pDevice, const std::multimap< KeyType, ValueType > & stlMap) inline static
Definition at line 256 of file StreamingHelper.h.
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename std::multimap<KeyType, ValueType>::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
       {
         XDR_STREAM( pDevice->write( & ( iter->first ) ) )
         XDR_STREAM( pDevice->write( & ( iter->second ) ) )
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename T > xdrstream::Status dqm4hep::core::StreamingHelper::writeStreamables (xdrstream::IODevice * pDevice, const T & stlContainer) inline static
Definition at line 292 of file StreamingHelper.h.
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename T::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
         XDR_STREAM( (*iter)->stream( xdrstream::XDR_WRITE_STREAM , pDevice ) )
         return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::writeStreamables (xdrstream::IODevice * pDevice, const std::map< KeyType, ValueType > & stlMap) inline static
Definition at line 330 of file StreamingHelper.h.
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename std::map<KeyType, ValueType>::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
       {
         XDR_STREAM( pDevice->write( & ( iter->first ) ) )
         XDR_STREAM( (iter->second)->stream( xdrstream::XDR_WRITE_STREAM , pDevice ) )
       }
       return xdrstream::XDR_SUCCESS;
     }
template<typename KeyType , typename ValueType > xdrstream::Status dqm4hep::core::StreamingHelper::writeStreamables (xdrstream::IODevice * pDevice, const std::multimap< KeyType, ValueType > & stlMap) inline static
Definition at line 371 of file StreamingHelper.h.
     {
       uint32_t nWrite = stlContainer.size();
       XDR_STREAM( pDevice->write( & nWrite ) )
       for( typename std::multimap<KeyType, ValueType>::const_iterator iter = stlContainer.begin(), endIter = stlContainer.end() ;
           endIter != iter ; ++iter)
       {
         XDR_STREAM( pDevice->write( & ( iter->first ) ) )
         XDR_STREAM( (iter->second)->stream( xdrstream::XDR_WRITE_STREAM , pDevice ) )
       }
       return xdrstream::XDR_SUCCESS;
     }
The documentation for this class was generated from the following file:
StreamingHelper.h