DQMCore: TCLAP::CmdLine Class Reference
TCLAP::CmdLine Class Reference
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
#include <CmdLine.h>
Public Member Functions
CmdLine (const std::string &message, const char delimiter= ' ', const std::string &version="none", bool helpAndVersion=true)
Command line constructor.
virtual ~CmdLine ()
Deletes any resources allocated by a CmdLine object.
void add (Arg &a)
Adds an argument to the list of arguments to be parsed.
void add (Arg *a)
An alternative add.
void xorAdd (Arg &a, Arg &b)
Add two Args that will be xor'd.
void xorAdd (std::vector< Arg * > &xors)
Add a list of Args that will be xor'd.
void parse (int argc, const char *const *argv)
Parses the command line.
void parse (std::vector< std::string > &args)
Parses the command line.
CmdLineOutput * getOutput ()
Returns the CmdLineOutput object.
void setOutput (CmdLineOutput *co)
std::string & getVersion ()
Returns the version string.
std::string & getProgramName ()
Returns the program name string.
std::list< Arg * > & getArgList ()
Returns the argList.
XorHandler & getXorHandler ()
Returns the XorHandler.
char getDelimiter ()
Returns the delimiter string.
std::string & getMessage ()
Returns the message string.
bool hasHelpAndVersion ()
Indicates whether or not the help and version switches were created automatically.
void setExceptionHandling (const bool state)
Disables or enables CmdLine's internal parsing exception handling.
bool getExceptionHandling () const
Returns the current state of the internal exception handling.
void reset ()
Allows the CmdLine object to be reused.
Public Member Functions inherited from TCLAP::CmdLineInterface
virtual ~CmdLineInterface ()
Destructor.
void parse (std::vector< std::string > &args)
Parses the command line.
Protected Member Functions
void missingArgsException ()
Throws an exception listing the missing args.
bool _emptyCombined (const std::string &s)
Checks whether a name/flag string matches entirely matches the Arg::blankChar.
void deleteOnExit (Arg *ptr)
Perform a delete ptr; operation on ptr when this object is deleted.
void deleteOnExit (Visitor *ptr)
Perform a delete ptr; operation on ptr when this object is deleted.
Protected Attributes
std::list< Arg * > _argList
The list of arguments that will be tested against the command line.
std::string _progName
The name of the program.
std::string _message
A message used to describe the program.
std::string _version
The version to be displayed with the –version switch.
int _numRequired
The number of arguments that are required to be present on the command line.
char _delimiter
The character that is used to separate the argument flag/name from the value.
XorHandler _xorHandler
The handler that manages xoring lists of args.
std::list< Arg * > _argDeleteOnExitList
A list of Args to be explicitly deleted when the destructor is called.
std::list< Visitor * > _visitorDeleteOnExitList
A list of Visitors to be explicitly deleted when the destructor is called.
CmdLineOutput * _output
Object that handles all output for the CmdLine.
bool _handleExceptions
Should CmdLine handle parsing exceptions internally?
Private Member Functions
CmdLine (const CmdLine &rhs)
Prevent accidental copying.
CmdLine & operator= (const CmdLine &rhs)
void _constructor ()
Encapsulates the code common to the constructors (which is all of it).
Private Attributes
bool _userSetOutput
Is set to true when a user sets the output object.
bool _helpAndVersion
Whether or not to automatically create help and version switches.
Detailed Description
The base class that manages the command line definition and passes along the parsing to the appropriate Arg classes.
Definition at line 70 of file CmdLine.h.
Constructor & Destructor Documentation
TCLAP::CmdLine::CmdLine (const CmdLine & rhs) private
Prevent accidental copying.
TCLAP::CmdLine::CmdLine (const std::string & message, const char delimiter = ' ', const std::string & version = "none", bool helpAndVersion = true) inline
Command line constructor.
Defines how the arguments will be parsed.
Parameters
message - The message to be used in the usage output.
delimiter - The character that is used to separate the argument flag/name from the value. Defaults to ' ' (space).
version - The version number to be used in the –version switch.
helpAndVersion - Whether or not to create the Help and Version switches. Defaults to true.
Definition at line 323 of file CmdLine.h.
References _constructor().
     :
   _argList(std::list<Arg*>()),
   _progName("not_set_yet"),
   _message(m),
   _version(v),
   _numRequired(0),
   _delimiter(delim),
   _xorHandler(XorHandler()),
   _argDeleteOnExitList(std::list<Arg*>()),
   _visitorDeleteOnExitList(std::list<Visitor*>()),
   _output(0),
   _handleExceptions(true),
   _userSetOutput(false),
   _helpAndVersion(help)
 {
   _constructor();
 }
TCLAP::CmdLine::~CmdLine () inline virtual
Deletes any resources allocated by a CmdLine object.
Definition at line 345 of file CmdLine.h.
References _argDeleteOnExitList, _output, _userSetOutput, _visitorDeleteOnExitList, and TCLAP::ClearContainer().
 {
   ClearContainer(_argDeleteOnExitList);
   ClearContainer(_visitorDeleteOnExitList);
   if ( !_userSetOutput ) {
     delete _output;
     _output = 0;
   }
 }
Member Function Documentation
void TCLAP::CmdLine::_constructor () inline private
Encapsulates the code common to the constructors (which is all of it).
Definition at line 356 of file CmdLine.h.
References _delimiter, _helpAndVersion, _output, add(), deleteOnExit(), TCLAP::Arg::flagStartString(), TCLAP::Arg::ignoreNameString(), and TCLAP::Arg::setDelimiter().
Referenced by CmdLine().
 {
   _output = new StdOutput;
   Arg::setDelimiter( _delimiter );
   Visitor* v;
   if ( _helpAndVersion )
   {
     v = new HelpVisitor( this, &_output );
     SwitchArg* help = new SwitchArg("h","help",
                           "Displays usage information and exits.",
                           false, v);
     add( help );
     deleteOnExit(help);
     deleteOnExit(v);
     v = new VersionVisitor( this, &_output );
     SwitchArg* vers = new SwitchArg("","version",
                           "Displays version information and exits.",
                           false, v);
     add( vers );
     deleteOnExit(vers);
     deleteOnExit(v);
   }
   v = new IgnoreRestVisitor();
   SwitchArg* ignore  = new SwitchArg(Arg::flagStartString(),
             Arg::ignoreNameString(),
             "Ignores the rest of the labeled arguments following this flag.",
             false, v);
   add( ignore );
   deleteOnExit(ignore);
   deleteOnExit(v);
 }
bool TCLAP::CmdLine::_emptyCombined (const std::string & s) inline protected
Checks whether a name/flag string matches entirely matches the Arg::blankChar.
Used when multiple switches are combined into a single argument.
Parameters
s - The message to be used in the usage.
Definition at line 512 of file CmdLine.h.
References TCLAP::Arg::blankChar(), and TCLAP::Arg::flagStartChar().
Referenced by parse().
 {
   if ( s.length() > 0 && s[0] != Arg::flagStartChar() )
     return false;
   for ( int i = 1; static_cast<unsigned int>(i) < s.length(); i++ )
     if ( s[i] != Arg::blankChar() )
       return false;
   return true;
 }
void TCLAP::CmdLine::add (Arg & a) inline virtual
Adds an argument to the list of arguments to be parsed.
Parameters
a - Argument to be added.
Implements TCLAP::CmdLineInterface.
Definition at line 413 of file CmdLine.h.
Referenced by _constructor(), and xorAdd().
 {
   add( &a );
 }
void TCLAP::CmdLine::add (Arg * a) inline virtual
An alternative add.
Functionally identical.
Parameters
a - Argument to be added.
Implements TCLAP::CmdLineInterface.
Definition at line 418 of file CmdLine.h.
References _argList, _numRequired, TCLAP::Arg::addToList(), TCLAP::Arg::isRequired(), and TCLAP::Arg::longID().
 {
   for( ArgListIterator it = _argList.begin(); it != _argList.end(); it++ )
     if ( *a == *(*it) )
       throw( SpecificationException(
               "Argument with same flag/name already exists!",
               a->longID() ) );
   a->addToList( _argList );
   if ( a->isRequired() )
     _numRequired++;
 }
void TCLAP::CmdLine::deleteOnExit (Arg * ptr) inline protected
Perform a delete ptr; operation on ptr when this object is deleted.
Definition at line 551 of file CmdLine.h.
References _argDeleteOnExitList.
Referenced by _constructor().
 {
   _argDeleteOnExitList.push_back(ptr);
 }
void TCLAP::CmdLine::deleteOnExit (Visitor * ptr) inline protected
Perform a delete ptr; operation on ptr when this object is deleted.
Definition at line 556 of file CmdLine.h.
References _visitorDeleteOnExitList.
 {
   _visitorDeleteOnExitList.push_back(ptr);
 }
std::list< Arg * > & TCLAP::CmdLine::getArgList () inline virtual
Returns the argList.
Implements TCLAP::CmdLineInterface.
Definition at line 584 of file CmdLine.h.
References _argList.
 {
   return _argList;
 }
char TCLAP::CmdLine::getDelimiter () inline virtual
Returns the delimiter string.
Implements TCLAP::CmdLineInterface.
Definition at line 594 of file CmdLine.h.
References _delimiter.
 {
   return _delimiter;
 }
bool TCLAP::CmdLine::getExceptionHandling () const inline
Returns the current state of the internal exception handling.
Return values
true Parsing exceptions are handled internally.
false Parsing exceptions are propagated to the caller.
Definition at line 614 of file CmdLine.h.
References _handleExceptions.
 {
   return _handleExceptions;
 }
std::string & TCLAP::CmdLine::getMessage () inline virtual
Returns the message string.
Implements TCLAP::CmdLineInterface.
Definition at line 599 of file CmdLine.h.
References _message.
 {
   return _message;
 }
CmdLineOutput * TCLAP::CmdLine::getOutput () inline virtual
Returns the CmdLineOutput object.
Implements TCLAP::CmdLineInterface.
Definition at line 561 of file CmdLine.h.
References _output.
 {
   return _output;
 }
std::string & TCLAP::CmdLine::getProgramName () inline virtual
Returns the program name string.
Implements TCLAP::CmdLineInterface.
Definition at line 579 of file CmdLine.h.
References _progName.
 {
   return _progName;
 }
std::string & TCLAP::CmdLine::getVersion () inline virtual
Returns the version string.
Implements TCLAP::CmdLineInterface.
Definition at line 574 of file CmdLine.h.
References _version.
 {
   return _version;
 }
XorHandler & TCLAP::CmdLine::getXorHandler () inline virtual
Returns the XorHandler.
Implements TCLAP::CmdLineInterface.
Definition at line 589 of file CmdLine.h.
References _xorHandler.
 {
   return _xorHandler;
 }
bool TCLAP::CmdLine::hasHelpAndVersion () inline virtual
Indicates whether or not the help and version switches were created automatically.
Implements TCLAP::CmdLineInterface.
Definition at line 604 of file CmdLine.h.
References _helpAndVersion.
 {
   return _helpAndVersion;
 }
void TCLAP::CmdLine::missingArgsException () inline protected
Throws an exception listing the missing args.
Definition at line 524 of file CmdLine.h.
References _argList.
Referenced by parse().
 {
     int count = 0;
     std::string missingArgList;
     for (ArgListIterator it = _argList.begin(); it != _argList.end(); it++)
     {
       if ( (*it)->isRequired() && !(*it)->isSet() )
       {
         missingArgList += (*it)->getName();
         missingArgList += ", ";
         count++;
       }
     }
     missingArgList = missingArgList.substr(0,missingArgList.length()-2);
     std::string msg;
     if ( count > 1 )
       msg = "Required arguments missing: ";
     else
       msg = "Required argument missing: ";
     msg += missingArgList;
     throw(CmdLineParseException(msg));
 }
CmdLine& TCLAP::CmdLine::operator= (const CmdLine & rhs) private
void TCLAP::CmdLine::parse (int argc, const char *const * argv) inline virtual
Parses the command line.
Parameters
argc - Number of arguments.
argv - Array of arguments.
Implements TCLAP::CmdLineInterface.
Definition at line 433 of file CmdLine.h.
 {
     // this step is necessary so that we have easy access to
     // mutable strings.
     std::vector<std::string> args;
     for (int i = 0; i < argc; i++)
       args.push_back(argv[i]);
     parse(args);
 }
void TCLAP::CmdLine::parse (std::vector< std::string > & args) inline
Parses the command line.
Parameters
args - A vector of strings representing the args. args[0] is still the program name.
Definition at line 444 of file CmdLine.h.
References _argList, _emptyCombined(), _handleExceptions, _numRequired, _output, _progName, _xorHandler, TCLAP::XorHandler::check(), TCLAP::CmdLineOutput::failure(), TCLAP::ExitException::getExitStatus(), TCLAP::Arg::ignoreRest(), and missingArgsException().
 {
   bool shouldExit = false;
   int estat = 0;
   try {
     _progName = args.front();
     args.erase(args.begin());
     int requiredCount = 0;
     for (int i = 0; static_cast<unsigned int>(i) < args.size(); i++)
     {
       bool matched = false;
       for (ArgListIterator it = _argList.begin();
            it != _argList.end(); it++) {
         if ( (*it)->processArg( &i, args ) )
         {
           requiredCount += _xorHandler.check( *it );
           matched = true;
           break;
         }
       }
       // checks to see if the argument is an empty combined
       // switch and if so, then we've actually matched it
       if ( !matched && _emptyCombined( args[i] ) )
         matched = true;
       if ( !matched && !Arg::ignoreRest() )
         throw(CmdLineParseException("Couldn't find match "
                                     "for argument",
                                     args[i]));
     }
     if ( requiredCount < _numRequired )
       missingArgsException();
     if ( requiredCount > _numRequired )
       throw(CmdLineParseException("Too many arguments!"));
   } catch ( ArgException& e ) {
     // If we're not handling the exceptions, rethrow.
     if ( !_handleExceptions) {
       throw;
     }
     try {
       _output->failure(*this,e);
     } catch ( ExitException &ee ) {
       estat = ee.getExitStatus();
       shouldExit = true;
     }
   } catch (ExitException &ee) {
     // If we're not handling the exceptions, rethrow.
     if ( !_handleExceptions) {
       throw;
     }
     estat = ee.getExitStatus();
     shouldExit = true;
   }
   if (shouldExit)
     exit(estat);
 }
void TCLAP::CmdLine::reset () inline virtual
Allows the CmdLine object to be reused.
Implements TCLAP::CmdLineInterface.
Definition at line 619 of file CmdLine.h.
References _argList, and _progName.
 {
   for( ArgListIterator it = _argList.begin(); it != _argList.end(); it++ )
     (*it)->reset();
   _progName.clear();
 }
void TCLAP::CmdLine::setExceptionHandling (const bool state) inline
Disables or enables CmdLine's internal parsing exception handling.
Parameters
state Should CmdLine handle parsing exceptions internally?
Definition at line 609 of file CmdLine.h.
References _handleExceptions.
 {
   _handleExceptions = state;
 }
void TCLAP::CmdLine::setOutput (CmdLineOutput * co) inline virtual
Parameters
co - CmdLineOutput object that we want to use instead.
Implements TCLAP::CmdLineInterface.
Definition at line 566 of file CmdLine.h.
References _output, and _userSetOutput.
 {
   if ( !_userSetOutput )
     delete _output;
   _userSetOutput = true;
   _output = co;
 }
void TCLAP::CmdLine::xorAdd (Arg & a, Arg & b) inline virtual
Add two Args that will be xor'd.
If this method is used, add does not need to be called.
Parameters
a - Argument to be added and xor'd.
b - Argument to be added and xor'd.
Implements TCLAP::CmdLineInterface.
Definition at line 405 of file CmdLine.h.
 {
   std::vector<Arg*> ors;
   ors.push_back( &a );
   ors.push_back( &b );
   xorAdd( ors );
 }
void TCLAP::CmdLine::xorAdd (std::vector< Arg * > & xors) inline virtual
Add a list of Args that will be xor'd.
If this method is used, add does not need to be called.
Parameters
xors - List of Args to be added and xor'd.
Implements TCLAP::CmdLineInterface.
Definition at line 393 of file CmdLine.h.
References _xorHandler, TCLAP::XorHandler::add(), and add().
 {
   _xorHandler.add( ors );
   for (ArgVectorIterator it = ors.begin(); it != ors.end(); it++)
   {
     (*it)->forceRequired();
     (*it)->setRequireLabel( "OR required" );
     add( *it );
   }
 }
Member Data Documentation
std::list<Arg*> TCLAP::CmdLine::_argDeleteOnExitList protected
A list of Args to be explicitly deleted when the destructor is called.
At the moment, this only includes the three default Args.
Definition at line 118 of file CmdLine.h.
Referenced by deleteOnExit(), and ~CmdLine().
std::list<Arg*> TCLAP::CmdLine::_argList protected
The list of arguments that will be tested against the command line.
Definition at line 78 of file CmdLine.h.
Referenced by add(), getArgList(), missingArgsException(), parse(), and reset().
char TCLAP::CmdLine::_delimiter protected
The character that is used to separate the argument flag/name from the value.
Defaults to ' ' (space).
Definition at line 106 of file CmdLine.h.
Referenced by _constructor(), and getDelimiter().
bool TCLAP::CmdLine::_handleExceptions protected
Should CmdLine handle parsing exceptions internally?
Definition at line 135 of file CmdLine.h.
Referenced by getExceptionHandling(), parse(), and setExceptionHandling().
bool TCLAP::CmdLine::_helpAndVersion private
Whether or not to automatically create help and version switches.
Definition at line 184 of file CmdLine.h.
Referenced by _constructor(), and hasHelpAndVersion().
std::string TCLAP::CmdLine::_message protected
A message used to describe the program.
Used in the usage output.
Definition at line 88 of file CmdLine.h.
Referenced by getMessage().
int TCLAP::CmdLine::_numRequired protected
The number of arguments that are required to be present on the command line.
This is set dynamically, based on the Args added to the CmdLine object.
Definition at line 100 of file CmdLine.h.
Referenced by add(), and parse().
CmdLineOutput* TCLAP::CmdLine::_output protected
Object that handles all output for the CmdLine.
Definition at line 130 of file CmdLine.h.
Referenced by _constructor(), getOutput(), parse(), setOutput(), and ~CmdLine().
std::string TCLAP::CmdLine::_progName protected
The name of the program.
Set to argv[0].
Definition at line 83 of file CmdLine.h.
Referenced by getProgramName(), parse(), and reset().
bool TCLAP::CmdLine::_userSetOutput private
Is set to true when a user sets the output object.
We use this so that we don't delete objects that are created outside of this lib.
Definition at line 179 of file CmdLine.h.
Referenced by setOutput(), and ~CmdLine().
std::string TCLAP::CmdLine::_version protected
The version to be displayed with the –version switch.
Definition at line 93 of file CmdLine.h.
Referenced by getVersion().
std::list<Visitor*> TCLAP::CmdLine::_visitorDeleteOnExitList protected
A list of Visitors to be explicitly deleted when the destructor is called.
At the moment, these are the Vistors created for the default Args.
Definition at line 125 of file CmdLine.h.
Referenced by deleteOnExit(), and ~CmdLine().
XorHandler TCLAP::CmdLine::_xorHandler protected
The handler that manages xoring lists of args.
Definition at line 111 of file CmdLine.h.
Referenced by getXorHandler(), parse(), and xorAdd().
The documentation for this class was generated from the following file:
CmdLine.h