DQMCore: dqm4hep::core::Logger Class Reference
dqm4hep::core::Logger Class Reference
#include <Logger.h>
Public Types
typedef std::shared_ptr
< spdlog::logger > LoggerPtr
typedef std::shared_ptr
< spdlog::sinks::sink > AppenderPtr
typedef spdlog::level::level_enum Level
Static Public Member Functions
static LoggerPtr createLogger (const std::string &name, std::initializer_list< AppenderPtr > appenders)
Create a new logger with the target appenders.
static LoggerPtr createLogger (const std::string &name, const std::vector< AppenderPtr > &appenders)
Create a new logger with the target appenders.
static AppenderPtr simpleFile (const std::string &fileName, bool truncated=false)
Create a simple file appender.
static AppenderPtr rotatingFile (const std::string &baseFileName, size_t maxSize, size_t maxNFiles)
Create a rotating file appender.
static AppenderPtr dailyFile (const std::string &baseFileName, int rotationHour, int rotationMinute)
Create a daily file appender.
static AppenderPtr console ()
Create a console appender.
static AppenderPtr coloredConsole ()
Create a colored console appender.
static AppenderPtr remote ()
Create a remote appender.
static LoggerPtr logger (const std::string &name)
Get an existing logger.
static void setLogLevel (Level level)
Set the log level of the main logger.
static LoggerPtr mainLogger ()
Get the main logger.
static LoggerPtr setMainLogger (const std::string &logger)
Change the main logger or the target one.
static std::string logLevelToString (Level level)
Convert log level to std::string.
static Level logLevelFromString (const std::string &level)
Convert std::string to log level.
static StringVector logLevels ()
Get the log levels list as strings.
static void setLoggerPattern (const std::string &logger, const std::string &pattern)
Set the logger log format pattern.
Static Private Attributes
static LoggerPtr m_mainLogger
The main logger instance.
Detailed Description
Definition at line 50 of file Logger.h.
Member Typedef Documentation
typedef std::shared_ptr<spdlog::sinks::sink> dqm4hep::core::Logger::AppenderPtr
Definition at line 54 of file Logger.h.
typedef spdlog::level::level_enum dqm4hep::core::Logger::Level
Definition at line 55 of file Logger.h.
typedef std::shared_ptr<spdlog::logger> dqm4hep::core::Logger::LoggerPtr
Definition at line 53 of file Logger.h.
Member Function Documentation
Logger::AppenderPtr dqm4hep::core::Logger::coloredConsole () static
Create a colored console appender.
Returns
an appender pointer (smart pointer)
Definition at line 192 of file Logger.cc.
References console().
     {
       return std::make_shared<spdlog::sinks::ansicolor_sink>(Logger::console());
     }
Logger::AppenderPtr dqm4hep::core::Logger::console () static
Create a console appender.
Returns
an appender pointer (smart pointer)
Definition at line 185 of file Logger.cc.
Referenced by coloredConsole().
     {
       return std::make_shared<spdlog::sinks::stdout_sink_mt>();
     }
static LoggerPtr dqm4hep::core::Logger::createLogger (const std::string & name, std::initializer_list< AppenderPtr > appenders) static
Create a new logger with the target appenders.
Parameters
name the logger name
appenders the list of appenders
Returns
a logger pointer (smart ptr)
static LoggerPtr dqm4hep::core::Logger::createLogger (const std::string & name, const std::vector< AppenderPtr > & appenders) static
Create a new logger with the target appenders.
Parameters
name the logger name
appenders the list of appenders
Returns
a logger pointer (smart ptr)
Logger::AppenderPtr dqm4hep::core::Logger::dailyFile (const std::string & baseFileName, int rotationHour, int rotationMinute) static
Create a daily file appender.
Parameters
baseFileName the base file name
rotationHour the hour for rotation
rotationMinute the minute for rotation
Returns
an appender pointer (smart pointer)
Definition at line 178 of file Logger.cc.
     {
       return std::make_shared<spdlog::sinks::daily_file_sink_mt>(baseFileName, rotationHour, rotationMinute);
     }
Logger::LoggerPtr dqm4hep::core::Logger::logger (const std::string & name) static
Get an existing logger.
Parameters
name the logger name
Returns
a logger pointer (smart pointer) or nullptr if doesn't exists
Definition at line 96 of file Logger.cc.
Referenced by setLoggerPattern(), and setMainLogger().
     {
       return spdlog::get(name);
     }
Logger::Level dqm4hep::core::Logger::logLevelFromString (const std::string & level) static
Convert std::string to log level.
Parameters
level the log level string
Returns
the log level
Definition at line 117 of file Logger.cc.
     {
       if(level == "trace")
         return spdlog::level::trace;
       if(level == "debug")
         return spdlog::level::debug;
       if(level == "info")
         return spdlog::level::info;
       if(level == "warning")
         return spdlog::level::warn;
       if(level == "error")
         return spdlog::level::err;
       if(level == "critical")
         return spdlog::level::critical;
       if(level == "off")
         return spdlog::level::off;
       throw StatusCodeException(STATUS_CODE_NOT_FOUND);
     }
StringVector dqm4hep::core::Logger::logLevels () static
Get the log levels list as strings.
Definition at line 139 of file Logger.cc.
References logLevelToString().
     {
       return StringVector({
         logLevelToString(spdlog::level::trace),
         logLevelToString(spdlog::level::debug),
         logLevelToString(spdlog::level::info),
         logLevelToString(spdlog::level::warn),
         logLevelToString(spdlog::level::err),
         logLevelToString(spdlog::level::critical),
         logLevelToString(spdlog::level::off)
       });
     }
std::string dqm4hep::core::Logger::logLevelToString (Logger::Level level) static
Convert log level to std::string.
Parameters
level the log level
Returns
log level in string format
Definition at line 110 of file Logger.cc.
Referenced by logLevels().
     {
       return spdlog::level::to_str(static_cast<spdlog::level::level_enum>(level));
     }
Logger::LoggerPtr dqm4hep::core::Logger::mainLogger () static
Get the main logger.
Returns
a logger pointer (smart pointer)
Definition at line 77 of file Logger.cc.
References m_mainLogger.
     {
       return m_mainLogger;
     }
static AppenderPtr dqm4hep::core::Logger::remote () static
Create a remote appender.
Returns
an appender pointer (smart pointer)
Logger::AppenderPtr dqm4hep::core::Logger::rotatingFile (const std::string & baseFileName, size_t maxSize, size_t maxNFiles) static
Create a rotating file appender.
Parameters
baseFileName the base file name
maxSize the maximum single file size (unit bytes)
maxNFiles the maximum number of files to rotate with
Returns
an appender pointer (smart pointer)
Definition at line 171 of file Logger.cc.
     {
       return std::make_shared<spdlog::sinks::rotating_file_sink_mt>(baseFileName, maxSize, maxNFiles);
     }
void dqm4hep::core::Logger::setLoggerPattern (const std::string & logger, const std::string & pattern) static
Set the logger log format pattern.
v The actual text to log t Thread id P Process id n Logger's name l The log level of the message L Short log level of the message, i.e "D", "I", etc a Abbreviated weekday name, i.e "Thu" A Full weekday name, i.e "Thursday" b Abbreviated month name, i.e "Aug" B Full month name, i.e "August" c Date and time representation, i.e "Thu Aug 23 15:35:46 2014" C Year in 2 digits, i.e "14" Y Year in 4 digits, i.e "2014" D (or x) Short MM/DD/YY date m Month 1-12 d Day of month 1-31 H Hours in 24 format 0-23 I Hours in 12 format 1-12 M Minutes 0-59 S Seconds 0-59 e Millisecond part of the current second 0-999 "678" f Microsecond part of the current second 0-999999 "056789" F Nanosecond part of the current second 0-999999999 "256789123" p AM/PM "AM" r 12 hour clock "02:55:02 pm" R 24-hour HH:MM time, equivalent to H:M "23:55" T (or X) ISO 8601 time format (HH:MM:SS), equivalent to H:M:S "23:55:59" z ISO 8601 offset from UTC in timezone ([+/-]HH:MM) "+02:00" %% The % sign "%" %+ default format "[2014-31-10 23:46:59.678] [mylogger] [info] Some message"
Parameters
logger the logger name
pattern the logging pattern
Definition at line 154 of file Logger.cc.
References logger().
     {
       LoggerPtr logger_ptr = Logger::logger(logger);
       if(logger_ptr)
         logger_ptr->set_pattern(pattern);
     }
void dqm4hep::core::Logger::setLogLevel (Level level) static
Set the log level of the main logger.
Parameters
level the log level
Definition at line 103 of file Logger.cc.
References m_mainLogger.
     {
       m_mainLogger->set_level(static_cast<spdlog::level::level_enum>(level));
     }
Logger::LoggerPtr dqm4hep::core::Logger::setMainLogger (const std::string & logger) static
Change the main logger or the target one.
Parameters
logger the new main logger name
Returns
a pointer to the main logger
Definition at line 84 of file Logger.cc.
References logger(), and m_mainLogger.
     {
       LoggerPtr logger_ptr(Logger::logger(logger));
       if(nullptr != logger_ptr)
         m_mainLogger = logger_ptr;
       return m_mainLogger;
     }
Logger::AppenderPtr dqm4hep::core::Logger::simpleFile (const std::string & fileName, bool truncated = false) static
Create a simple file appender.
Parameters
fileName the file name
truncated whether to truncate the file if needed
Returns
an appender pointer (smart pointer)
Definition at line 164 of file Logger.cc.
     {
       return std::make_shared<spdlog::sinks::simple_file_sink_mt>(fileName, truncated);
     }
Member Data Documentation
std::shared_ptr< spdlog::logger > dqm4hep::core::Logger::m_mainLogger static private
Initial value:
= Logger::createLogger("main", {
      Logger::coloredConsole()
    })
The main logger instance.
Definition at line 205 of file Logger.h.
Referenced by mainLogger(), setLogLevel(), and setMainLogger().
The documentation for this class was generated from the following files:
Logger.h
Logger.cc