DQMCore: dqm4hep::core::TiXmlComment Class Reference
dqm4hep::core::TiXmlComment Class Reference
An XML comment.
#include <tinyxml.h>
Public Member Functions
TiXmlComment ()
Constructs an empty comment.
TiXmlComment (const char *_value)
Construct a comment from text.
TiXmlComment (const TiXmlComment &)
void operator= (const TiXmlComment &base)
virtual ~TiXmlComment ()
virtual TiXmlNode * Clone () const
Returns a copy of this Comment.
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *visitor) const
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from dqm4hep::core::TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const std::string & ValueStr () const
Return Value() as a std::string.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'.
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
void CopyTo (TiXmlComment *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Protected Member Functions inherited from dqm4hep::core::TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Additional Inherited Members
Public Types inherited from dqm4hep::core::TiXmlNode
enum NodeType {
TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN,
TINYXML_TEXT, TINYXML_DECLARATION, TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from dqm4hep::core::TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
An XML comment.
Definition at line 1162 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlComment::TiXmlComment () inline
Constructs an empty comment.
Definition at line 1166 of file tinyxml.h.
Referenced by Clone().
 : TiXmlNode( TiXmlNode::TINYXML_COMMENT ) {}
dqm4hep::core::TiXmlComment::TiXmlComment (const char * _value) inline
Construct a comment from text.
Definition at line 1168 of file tinyxml.h.
References dqm4hep::core::TiXmlNode::SetValue().
                                          : TiXmlNode( TiXmlNode::TINYXML_COMMENT ) {
         SetValue( _value );
       }
dqm4hep::core::TiXmlComment::TiXmlComment (const TiXmlComment & copy)
Definition at line 1242 of file tinyxml.cc.
References CopyTo().
                                                          : TiXmlNode( TiXmlNode::TINYXML_COMMENT )
     {
       copy.CopyTo( this );
     }
virtual dqm4hep::core::TiXmlComment::~TiXmlComment () inline virtual
Definition at line 1174 of file tinyxml.h.
 {}
Member Function Documentation
bool dqm4hep::core::TiXmlComment::Accept (TiXmlVisitor * visitor) const virtual
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::core::TiXmlNode.
Definition at line 1272 of file tinyxml.cc.
References dqm4hep::core::TiXmlVisitor::Visit().
     {
       return visitor->Visit( *this );
     }
TiXmlNode * dqm4hep::core::TiXmlComment::Clone () const virtual
Returns a copy of this Comment.
Implements dqm4hep::core::TiXmlNode.
Definition at line 1278 of file tinyxml.cc.
References CopyTo(), and TiXmlComment().
     {
       TiXmlComment* clone = new TiXmlComment();
       if ( !clone )
         return 0;
       CopyTo( clone );
       return clone;
     }
void dqm4hep::core::TiXmlComment::CopyTo (TiXmlComment * target) const protected
Definition at line 1266 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlComment().
     {
       TiXmlNode::CopyTo( target );
     }
void dqm4hep::core::TiXmlComment::operator= (const TiXmlComment & base)
Definition at line 1248 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::Clear(), and CopyTo().
     {
       Clear();
       base.CopyTo( this );
     }
const char * dqm4hep::core::TiXmlComment::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements dqm4hep::core::TiXmlBase.
Definition at line 1340 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlParsingData::Cursor(), dqm4hep::core::TiXmlNode::GetDocument(), dqm4hep::core::TiXmlBase::location, dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlParsingData::Stamp(), dqm4hep::core::TiXmlBase::StringEqual(), dqm4hep::core::TiXmlBase::TIXML_ERROR_PARSING_COMMENT, and dqm4hep::core::TiXmlNode::value.
     {
       TiXmlDocument* document = GetDocument();
       value = "";
       p = SkipWhiteSpace( p, encoding );
       if ( data )
       {
         data->Stamp( p, encoding );
         location = data->Cursor();
       }
       const char* startTag = "<!--";
       const char* endTag   = "-->";
       if ( !StringEqual( p, startTag, false, encoding ) )
       {
         document->SetError( TIXML_ERROR_PARSING_COMMENT, p, data, encoding );
         return 0;
       }
       p += strlen( startTag );
       // [ 1475201 ] TinyXML parses entities in comments
       // Oops - ReadText doesn't work, because we don't want to parse the entities.
       // p = ReadText( p, &value, false, endTag, false, encoding );
       //
       // from the XML spec:
       /*
    [Definition: Comments may appear anywhere in a document outside other markup; in addition,
                 they may appear within the document type declaration at places allowed by the grammar.
           They are not part of the document's character data; an XML processor MAY, but need not,
           make it possible for an application to retrieve the text of comments. For compatibility,
           the string "--" (double-hyphen) MUST NOT occur within comments.] Parameter entity
           references MUST NOT be recognized within comments.
           An example of a comment:
           <!-- declarations for <head> & <body> -->
        */
       value = "";
       // Keep all the white space.
       while ( p && *p && !StringEqual( p, endTag, false, encoding ) )
       {
         value.append( p, 1 );
         ++p;
       }
       if ( p && *p )
         p += strlen( endTag );
       return p;
     }
void dqm4hep::core::TiXmlComment::Print (FILE * cfile, int depth) const virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::core::TiXmlBase.
Definition at line 1255 of file tinyxml.cc.
References dqm4hep::core::TiXmlNode::value.
     {
       assert( cfile );
       for ( int i=0; i<depth; i++ )
       {
         fprintf( cfile,  "    " );
       }
       fprintf( cfile, "<!--%s-->", value.c_str() );
     }
virtual void dqm4hep::core::TiXmlComment::StreamIn (std::istream * in, TIXML_STRING * tag) protected virtual
Implements dqm4hep::core::TiXmlNode.
virtual const TiXmlComment* dqm4hep::core::TiXmlComment::ToComment () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1186 of file tinyxml.h.
virtual TiXmlComment* dqm4hep::core::TiXmlComment::ToComment () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1187 of file tinyxml.h.
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc