DQMCore: dqm4hep::core::Signal< void > Class Template Reference
dqm4hep::core::Signal< void > Class Template Reference
#include <Signal.h>
Public Member Functions
~Signal ()
void process ()
template<typename T , typename S >
bool connect (T *pClass, S function)
template<typename T >
bool disconnect (T *pClass)
void disconnectAll ()
template<typename T >
bool isConnected (T *pClass) const
bool hasConnection () const
Private Attributes
SignalBase< void >::Vector m_callbacks
Detailed Description
template<>
class dqm4hep::core::Signal< void >
Definition at line 196 of file Signal.h.
Constructor & Destructor Documentation
dqm4hep::core::Signal< void >::~Signal () inline
Definition at line 341 of file Signal.h.
References dqm4hep::core::Signal< Args >::disconnectAll().
     {
       this->disconnectAll();
     }
Member Function Documentation
template<typename T , typename S > bool dqm4hep::core::Signal< void >::connect (T * pClass, S function) inline
Definition at line 357 of file Signal.h.
References dqm4hep::core::Signal< Args >::isConnected(), and dqm4hep::core::Signal< Args >::m_callbacks.
     {
       // check for existing connection
       if(this->isConnected(pClass))
         return false;
       // add the callback
       m_callbacks.push_back(new SignalT<T, void>(pClass, function));
       return true;
     }
template<typename T > bool dqm4hep::core::Signal< void >::disconnect (T * pClass) inline
Definition at line 372 of file Signal.h.
References dqm4hep::core::SignalT< T, void >::getClass(), and dqm4hep::core::Signal< Args >::m_callbacks.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         SignalT<T, void> *pCallBackT(dynamic_cast<SignalT<T, void> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass)
         {
           delete pCallBackT;
           m_callbacks.erase(iter);
           return true;
         }
       }
       return false;
     }
void dqm4hep::core::Signal< void >::disconnectAll () inline
Definition at line 394 of file Signal.h.
References dqm4hep::core::Signal< Args >::m_callbacks.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
         delete *iter;
       m_callbacks.clear();
     }
bool dqm4hep::core::Signal< void >::hasConnection () const inline
Definition at line 423 of file Signal.h.
References dqm4hep::core::Signal< Args >::m_callbacks.
     {
       return (!m_callbacks.empty());
     }
template<typename T > bool dqm4hep::core::Signal< void >::isConnected (T * pClass) const inline
Definition at line 405 of file Signal.h.
References dqm4hep::core::SignalT< T, void >::getClass(), and dqm4hep::core::Signal< Args >::m_callbacks.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
       {
         const SignalT<T, void> *pCallBackT(dynamic_cast<const SignalT<T, void> *>(*iter));
         if(!pCallBackT)
           continue;
         if(pCallBackT->getClass() == pClass)
           return true;
       }
       return false;
     }
void dqm4hep::core::Signal< void >::process () inline
Definition at line 348 of file Signal.h.
References dqm4hep::core::Signal< Args >::m_callbacks.
     {
       for(auto iter = m_callbacks.begin(), endIter = m_callbacks.end() ; endIter != iter ; ++iter)
         (*iter)->process();
     }
Member Data Documentation
SignalBase<void>::Vector dqm4hep::core::Signal< void >::m_callbacks private
Definition at line 238 of file Signal.h.
The documentation for this class was generated from the following file:
Signal.h