DQMCore: TCLAP::StdOutput Class Reference
TCLAP::StdOutput Class Reference
A class that isolates any output from the CmdLine object so that it may be easily modified.
#include <StdOutput.h>
Public Member Functions
virtual void usage (CmdLineInterface &c)
Prints the usage to stdout.
virtual void version (CmdLineInterface &c)
Prints the version to stdout.
virtual void failure (CmdLineInterface &c, ArgException &e)
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Public Member Functions inherited from TCLAP::CmdLineOutput
virtual ~CmdLineOutput ()
Virtual destructor.
Protected Member Functions
void _shortUsage (CmdLineInterface &c, std::ostream &os) const
Writes a brief usage message with short args.
void _longUsage (CmdLineInterface &c, std::ostream &os) const
Writes a longer usage message with long and short args, provides descriptions and prints message.
void spacePrint (std::ostream &os, const std::string &s, int maxWidth, int indentSpaces, int secondLineOffset) const
This function inserts line breaks and indents long strings according the params input.
Detailed Description
A class that isolates any output from the CmdLine object so that it may be easily modified.
Definition at line 43 of file StdOutput.h.
Member Function Documentation
void TCLAP::StdOutput::_longUsage (CmdLineInterface & c, std::ostream & os) const inline protected
Writes a longer usage message with long and short args, provides descriptions and prints message.
Parameters
c - The CmdLine object the output is generated for.
os - The stream to write the message to.
Definition at line 191 of file StdOutput.h.
References TCLAP::XorHandler::contains(), TCLAP::CmdLineInterface::getArgList(), TCLAP::CmdLineInterface::getMessage(), TCLAP::CmdLineInterface::getXorHandler(), TCLAP::XorHandler::getXorList(), and spacePrint().
Referenced by usage().
 {
   std::list<Arg*> argList = _cmd.getArgList();
   std::string message = _cmd.getMessage();
   XorHandler xorHandler = _cmd.getXorHandler();
   std::vector< std::vector<Arg*> > xorList = xorHandler.getXorList();
   // first the xor
   for ( int i = 0; static_cast<unsigned int>(i) < xorList.size(); i++ )
     {
       for ( ArgVectorIterator it = xorList[i].begin();
           it != xorList[i].end();
           it++ )
         {
           spacePrint( os, (*it)->longID(), 75, 3, 3 );
           spacePrint( os, (*it)->getDescription(), 75, 5, 0 );
           if ( it+1 != xorList[i].end() )
             spacePrint(os, "-- OR --", 75, 9, 0);
         }
       os << std::endl << std::endl;
     }
   // then the rest
   for (ArgListIterator it = argList.begin(); it != argList.end(); it++)
     if ( !xorHandler.contains( (*it) ) )
       {
         spacePrint( os, (*it)->longID(), 75, 3, 3 );
         spacePrint( os, (*it)->getDescription(), 75, 5, 0 );
         os << std::endl;
       }
   os << std::endl;
   spacePrint( os, message, 75, 3, 0 );
 }
void TCLAP::StdOutput::_shortUsage (CmdLineInterface & c, std::ostream & os) const inline protected
Writes a brief usage message with short args.
Parameters
c - The CmdLine object the output is generated for.
os - The stream to write the message to.
Definition at line 156 of file StdOutput.h.
References TCLAP::XorHandler::contains(), TCLAP::CmdLineInterface::getArgList(), TCLAP::CmdLineInterface::getProgramName(), TCLAP::CmdLineInterface::getXorHandler(), TCLAP::XorHandler::getXorList(), and spacePrint().
Referenced by failure(), and usage().
 {
   std::list<Arg*> argList = _cmd.getArgList();
   std::string progName = _cmd.getProgramName();
   XorHandler xorHandler = _cmd.getXorHandler();
   std::vector< std::vector<Arg*> > xorList = xorHandler.getXorList();
   std::string s = progName + " ";
   // first the xor
   for ( int i = 0; static_cast<unsigned int>(i) < xorList.size(); i++ )
     {
       s += " {";
       for ( ArgVectorIterator it = xorList[i].begin();
           it != xorList[i].end(); it++ )
         s += (*it)->shortID() + "|";
       s[s.length()-1] = '}';
     }
   // then the rest
   for (ArgListIterator it = argList.begin(); it != argList.end(); it++)
     if ( !xorHandler.contains( (*it) ) )
       s += " " + (*it)->shortID();
   // if the program name is too long, then adjust the second line offset
   int secondLineOffset = static_cast<int>(progName.length()) + 2;
   if ( secondLineOffset > 75/2 )
     secondLineOffset = static_cast<int>(75/2);
   spacePrint( os, s, 75, 3, secondLineOffset );
 }
void TCLAP::StdOutput::failure (CmdLineInterface & c, ArgException & e) inline virtual
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
e - The ArgException that caused the failure.
Implements TCLAP::CmdLineOutput.
Definition at line 131 of file StdOutput.h.
References _shortUsage(), TCLAP::ArgException::argId(), TCLAP::ArgException::error(), TCLAP::CmdLineInterface::getProgramName(), TCLAP::CmdLineInterface::hasHelpAndVersion(), and usage().
 {
   std::string progName = _cmd.getProgramName();
   std::cerr << "PARSE ERROR: " << e.argId() << std::endl
           << "             " << e.error() << std::endl << std::endl;
   if ( _cmd.hasHelpAndVersion() )
     {
       std::cerr << "Brief USAGE: " << std::endl;
       _shortUsage( _cmd, std::cerr );
       std::cerr << std::endl << "For complete USAGE and HELP type: "
             << std::endl << "   " << progName << " --help"
             << std::endl << std::endl;
     }
   else
     usage(_cmd);
   throw ExitException(1);
 }
void TCLAP::StdOutput::spacePrint (std::ostream & os, const std::string & s, int maxWidth, int indentSpaces, int secondLineOffset) const inline protected
This function inserts line breaks and indents long strings according the params input.
It will only break lines at spaces, commas and pipes.
Parameters
os - The stream to be printed to.
s - The string to be printed.
maxWidth - The maxWidth allowed for the output line.
indentSpaces - The number of spaces to indent the first line.
secondLineOffset - The number of spaces to indent the second and all subsequent lines in addition to indentSpaces.
Definition at line 229 of file StdOutput.h.
Referenced by _longUsage(), and _shortUsage().
 {
   int len = static_cast<int>(s.length());
   if ( (len + indentSpaces > maxWidth) && maxWidth > 0 )
     {
       int allowedLen = maxWidth - indentSpaces;
       int start = 0;
       while ( start < len )
         {
           // find the substring length
           // int stringLen = std::min<int>( len - start, allowedLen );
           // doing it this way to support a VisualC++ 2005 bug
           using namespace std;
           int stringLen = min<int>( len - start, allowedLen );
           // trim the length so it doesn't end in middle of a word
           if ( stringLen == allowedLen )
             while ( stringLen >= 0 &&
                 s[stringLen+start] != ' ' &&
                 s[stringLen+start] != ',' &&
                 s[stringLen+start] != '|' )
               stringLen--;
           // ok, the word is longer than the line, so just split
           // wherever the line ends
           if ( stringLen <= 0 )
             stringLen = allowedLen;
           // check for newlines
           for ( int i = 0; i < stringLen; i++ )
             if ( s[start+i] == '\n' )
               stringLen = i+1;
           // print the indent
           for ( int i = 0; i < indentSpaces; i++ )
             os << " ";
           if ( start == 0 )
             {
               // handle second line offsets
               indentSpaces += secondLineOffset;
               // adjust allowed len
               allowedLen -= secondLineOffset;
             }
           os << s.substr(start,stringLen) << std::endl;
           // so we don't start a line with a space
           while ( s[stringLen+start] == ' ' && start < len )
             start++;
           start += stringLen;
         }
     }
   else
     {
       for ( int i = 0; i < indentSpaces; i++ )
         os << " ";
       os << s << std::endl;
     }
 }
void TCLAP::StdOutput::usage (CmdLineInterface & c) inline virtual
Prints the usage to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 117 of file StdOutput.h.
References _longUsage(), and _shortUsage().
Referenced by failure().
 {
   std::cout << std::endl << "USAGE: " << std::endl << std::endl;
   _shortUsage( _cmd, std::cout );
   std::cout << std::endl << std::endl << "Where: " << std::endl << std::endl;
   _longUsage( _cmd, std::cout );
   std::cout << std::endl;
 }
void TCLAP::StdOutput::version (CmdLineInterface & c) inline virtual
Prints the version to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 108 of file StdOutput.h.
References TCLAP::CmdLineInterface::getProgramName(), and TCLAP::CmdLineInterface::getVersion().
 {
   std::string progName = _cmd.getProgramName();
   std::string xversion = _cmd.getVersion();
   std::cout << std::endl << progName << "  version: "
         << xversion << std::endl << std::endl;
 }
The documentation for this class was generated from the following file:
StdOutput.h