DQMCore: dqm4hep::core::MonitorElementManager Class Reference
dqm4hep::core::MonitorElementManager Class Reference
MonitorElementManager class.
#include <MonitorElementManager.h>
Public Member Functions
MonitorElementManager ()
Constructor.
~MonitorElementManager ()
Destructor.
void cd ()
Go back to root directory.
StatusCode cd (const std::string &dirName)
Go to directory 'dirName'.
StatusCode mkdir (const std::string &dirName)
Create the directory 'dirName'.
const std::string & pwd ()
List the current directory content.
const std::string & fullPwd ()
Get the current directory full name.
StatusCode goUp ()
Navigate backward in the directory structure.
StatusCode rmdir (const std::string &dirName)
Remove the directory 'dirName'.
bool dirExists (const std::string &dirName) const
Whether the directory exists.
StatusCode addMonitorElement (const std::string &path, TObject *pObject, MonitorElement *&pMonitorElement)
Add a monitor element from an external source.
StatusCode readMonitorElement (const std::string &fileName, const std::string &path, const std::string &name, MonitorElement *&pMonitorElement)
Read TObject from file and add it to list.
StatusCode readMonitorElement (TFile *pTFile, const std::string &path, const std::string &name, MonitorElement *&pMonitorElement)
Read TObject from file and add it to list.
StatusCode bookMonitorElement (const std::string &className, const std::string &path, const std::string &name, MonitorElement *&pMonitorElement)
Book a monitor element using the ROOT TClass facility.
StatusCode handleMonitorElement (const std::string &path, TObject *pObject, MonitorElement *&pMonitorElement)
Add a monitor element from an external source.
template<typename ObjectType , typename... Args>
StatusCode bookObject (const std::string &path, const std::string &name, MonitorElement *&pMonitorElement, allocator_helper< TObject, ObjectType, Args...> allocator, Args...args)
Book a monitor element.
StatusCode attachReference (MonitorElement *pMonitorElement, const std::string &fileName)
Open root file, find reference object and attach it to the monitor element.
void getMonitorElements (std::vector< MonitorElement * > &monitorElements) const
Get all the monitor elements already booked by this module in all the directories.
StatusCode getMonitorElement (const std::string &name, MonitorElement *&monitorElement) const
Get the monitor element in the current directory (result by ptr reference)
StatusCode getMonitorElement (const std::string &dirName, const std::string &name, MonitorElement *&monitorElement) const
Get the monitor element in the given directory (result by ptr reference)
StatusCode removeMonitorElement (const std::string &path, const std::string &name)
Remove the monitor element.
StatusCode createQualityTest (TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
StatusCode addQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName)
Add a (already created) quality test to the monitor element.
StatusCode removeQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName)
Remove a quality test from the monitor element.
StatusCode runQualityTests (QReportStorage &reports)
StatusCode runQualityTests (const std::string &path, const std::string &name, QReportStorage &reports)
StatusCode runQualityTest (const std::string &path, const std::string &name, const std::string &qualityTestName, QReportStorage &reports)
Private Types
typedef std::map< const
std::string, QualityTest * > QualityTestMap
typedef std::map< const
std::string, const
QualityTestFactory * > QualityTestFactoryMap
typedef std::map
< MonitorElement
*, QualityTestMap > MonitorElementToQTestMap
Private Member Functions
const Storage< MonitorElement > & getStorage () const
Get the monitor element storage.
Private Attributes
Storage< MonitorElement > m_storage
QualityTestFactoryMap m_qualityTestFactoryMap
QualityTestMap m_qualityTestMap
MonitorElementToQTestMap m_monitorElementToQTestMap
Detailed Description
MonitorElementManager class.
Definition at line 93 of file MonitorElementManager.h.
Member Typedef Documentation
typedef std::map<MonitorElement*, QualityTestMap> dqm4hep::core::MonitorElementManager::MonitorElementToQTestMap private
Definition at line 261 of file MonitorElementManager.h.
typedef std::map<const std::string, const QualityTestFactory *> dqm4hep::core::MonitorElementManager::QualityTestFactoryMap private
Definition at line 96 of file MonitorElementManager.h.
typedef std::map<const std::string, QualityTest *> dqm4hep::core::MonitorElementManager::QualityTestMap private
Definition at line 95 of file MonitorElementManager.h.
Constructor & Destructor Documentation
dqm4hep::core::MonitorElementManager::MonitorElementManager ()
Constructor.
Definition at line 62 of file MonitorElementManager.cc.
References dqm4hep::core::PluginManager::create(), dqm_error, dqm4hep::core::Singleton< PluginManager >::instance(), m_qualityTestFactoryMap, and dqm4hep::core::PluginManager::pluginNamesMatchingType().
                                                  :
       m_storage()
     {
       PluginManager *pPluginMgr(PluginManager::instance());
       StringVector factoryNames(pPluginMgr->pluginNamesMatchingType<QualityTestFactory>());
       for(auto factoryName : factoryNames)
       {
         QualityTestFactory *pFactory(pPluginMgr->create<QualityTestFactory>(factoryName));
         if(nullptr == pFactory)
         {
           dqm_error( "MonitorElementManager::MonitorElementManager: Couldn't create qtest factory '{0}'. This is normally not possible !", factoryName );
           continue;
         }
         m_qualityTestFactoryMap.insert(QualityTestFactoryMap::value_type(factoryName, pFactory));
       }
     }
dqm4hep::core::MonitorElementManager::~MonitorElementManager ()
Destructor.
Definition at line 84 of file MonitorElementManager.cc.
References m_qualityTestFactoryMap, and m_qualityTestMap.
     {
       for(QualityTestFactoryMap::iterator iter = m_qualityTestFactoryMap.begin(), endIter = m_qualityTestFactoryMap.end() ;
           endIter != iter ; ++iter)
         delete iter->second;
       for(QualityTestMap::iterator iter = m_qualityTestMap.begin(), endIter = m_qualityTestMap.end() ;
           endIter != iter ; ++iter)
         delete iter->second;
       m_qualityTestFactoryMap.clear();
       m_qualityTestMap.clear();
     }
Member Function Documentation
StatusCode dqm4hep::core::MonitorElementManager::addMonitorElement (const std::string & path, TObject * pObject, MonitorElement *& pMonitorElement)
Add a monitor element from an external source.
WARNING : The ROOT object is owned by the framework. The caller must NOT delete the object
Definition at line 163 of file MonitorElementManager.cc.
References dqm_error, m_storage, dqm4hep::core::MonitorElement::name(), dqm4hep::core::MonitorElement::setPath(), and THROW_RESULT_IF.
Referenced by bookObject().
     {
       PtrHandler<TObject> ptrObject(pObject, true);
       pMonitorElement = nullptr;
       try
       {
         if(!pObject->Class()->HasDictionary())
         {
           dqm_error( "Couldn't book object of type '{0}', because this class has no dictionnary!", pObject->ClassName() );
           throw StatusCodeException(STATUS_CODE_NOT_ALLOWED);
         }
         if(pObject->Class()->IsForeign())
         {
           dqm_error( "Couldn't book object of type '{0}', because this class is foreign ( does not have a Streamer method))!", pObject->ClassName() );
           throw StatusCodeException(STATUS_CODE_NOT_ALLOWED);
         }
         if(!pObject->InheritsFrom("TNamed"))
         {
           dqm_error( "Couldn't book object of type '{0}', because this class doesn't inherit TNamed (required to call SetName())!", pObject->ClassName() );
           throw StatusCodeException(STATUS_CODE_NOT_ALLOWED);
         }
         pMonitorElement = new MonitorElement(ptrObject);
         if(nullptr != m_storage.findObject(path, [&](MonitorElement *obj){ return obj->name() == pObject->GetName(); }) )
         {
           dqm_error( "Monitor element '{0}' in directory '{1}' already booked !", pObject->GetName(), path );
           throw StatusCodeException(STATUS_CODE_ALREADY_PRESENT);
         }
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_storage.add(path, pMonitorElement));
         pMonitorElement->setPath(path);
       }
       catch(StatusCodeException &e)
       {
         if(nullptr != pMonitorElement)
         {
           delete pMonitorElement;
           pMonitorElement = nullptr;
         }
         else
         {
           // TObject should have been owned by the MonitorElement
           // but creation failed, we need to delete it manually
           delete pObject;
         }
         return e.getStatusCode();
       }
       catch(...)
       {
         if(nullptr != pMonitorElement)
         {
           delete pMonitorElement;
           pMonitorElement = nullptr;
         }
         else
         {
           // TObject should have been owned by the MonitorElement
           // but creation failed, we need to delete it manually
           delete pObject;
         }
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::addQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName)
Add a (already created) quality test to the monitor element.
Definition at line 468 of file MonitorElementManager.cc.
References dqm4hep::core::MonitorElement::addQualityTest(), and RETURN_RESULT_IF.
     {
       QualityTestMap::iterator findIter = m_qualityTestMap.find(qualityTestName);
       if(m_qualityTestMap.end() == findIter)
         return STATUS_CODE_NOT_FOUND;
       MonitorElement *pMonitorElement(nullptr);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, pMonitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->addQualityTest(findIter->second));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::attachReference (MonitorElement * pMonitorElement, const std::string & fileName)
Open root file, find reference object and attach it to the monitor element.
Parameters
pMonitorElement the monitor element to attach the reference
fileName the root file name contaning the reference
Definition at line 337 of file MonitorElementManager.cc.
References dqm_debug, dqm4hep::core::Path::getPath(), dqm4hep::core::MonitorElement::name(), dqm4hep::core::MonitorElement::path(), and dqm4hep::core::MonitorElement::setReferenceObject().
     {
       if(nullptr == pMonitorElement)
         return STATUS_CODE_INVALID_PTR;
       Path fullName = pMonitorElement->path();
       fullName += pMonitorElement->name();
       dqm_debug( "MonitorElementManager::attachReference: looking for element {0}", fullName.getPath() );
       std::unique_ptr<TFile> rootFile(new TFile(fileName.c_str(), "READ"));
       const bool objectStat(TObject::GetObjectStat());
       TObject::SetObjectStat(false);
       TObject *pTObject(nullptr);
       if(pMonitorElement->path() == "/")
         pTObject = (TObject *) rootFile->Get(pMonitorElement->name().c_str());
       else
         pTObject = (TObject *) rootFile->Get(fullName.getPath().c_str());
       TObject::SetObjectStat(objectStat);
       if(!pTObject)
         return STATUS_CODE_NOT_FOUND;
       pMonitorElement->setReferenceObject(pTObject);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::bookMonitorElement (const std::string & className, const std::string & path, const std::string & name, MonitorElement *& pMonitorElement)
Book a monitor element using the ROOT TClass facility.
The className is passed to TClass::GetClass() to get the corresponding TClass object handler. Note that to allocate the TObject:
the default constructor is used
ROOT object is disabled so that object with same can be allocated safely memory leak The resulting monitored TObject is owned by the manager
Definition at line 304 of file MonitorElementManager.cc.
References dqm_debug, and dqm_error.
     {
       pMonitorElement = nullptr;
       TClass *pTClass = TClass::GetClass(className.c_str());
       if(!pTClass->IsTObject())
       {
         dqm_error( "MonitorElementManager::bookMonitorElement: ROOT class '{0}' does not inherit from TObject. Can only handle TObject object type", className );
         return STATUS_CODE_FAILURE;
       }
       const bool objectStat(TObject::GetObjectStat());
       TObject::SetObjectStat(false);
       TObject *pTObject = (TObject*)pTClass->New();
       TObject::SetObjectStat(objectStat);
       if(!pTObject)
       {
         dqm_error( "MonitorElementManager::bookMonitorElement: Couldn't allocate ROOT class '{0}' from TClass facility", className );
         return STATUS_CODE_FAILURE;
       }
       if(pTObject->InheritsFrom("TNamed"))
       {
         dqm_debug( "Set name of object {0} to '{1}'", (void*) pTObject, name );
         ((TNamed*)pTObject)->SetName(name.c_str());
       }
       return this->addMonitorElement(path, pTObject, pMonitorElement);
     }
template<typename ObjectType , typename... Args> StatusCode dqm4hep::core::MonitorElementManager::bookObject (const std::string & path, const std::string & name, MonitorElement *& pMonitorElement, allocator_helper< TObject, ObjectType, Args...> allocator, Args... args)
Book a monitor element.
The objectType must inherit TObject and have a ROOT dictionnary.
Definition at line 274 of file MonitorElementManager.h.
References addMonitorElement(), dqm4hep::core::allocator_helper< BaseType, RealType, Args >::create(), dqm_error, and dqm_warning.
     {
       pMonitorElement = nullptr;
       if(!ObjectType::Class()->HasDictionary())
       {
         dqm_error( "Couldn't book object of type '{0}', because this class has no dictionnary!", ObjectType::Class_name() );
         return STATUS_CODE_NOT_ALLOWED;
       }
       if(ObjectType::Class()->IsForeign())
       {
         dqm_error( "Couldn't book object of type '{0}', because this class is foreign (does not have a Streamer method))!", ObjectType::Class_name() );
         return STATUS_CODE_NOT_ALLOWED;
       }
       if(!ObjectType::Class()->InheritsFrom("TNamed"))
       {
         dqm_error( "Couldn't book object of type '{0}', because this class doesn't inherit TNamed (required to call SetName())!", ObjectType::Class_name() );
         return STATUS_CODE_NOT_ALLOWED;
       }
       const bool objectStat(TObject::GetObjectStat());
       TObject::SetObjectStat(false);
       TObject *pTObject = allocator.create(args...);
       TObject::SetObjectStat(objectStat);
       if(!pTObject)
       {
         dqm_warning( "Couldn't allocate monitor element of type '{0}', path '{1}', name '{2}'", ObjectType::Class_name(), path, name );
         return STATUS_CODE_FAILURE;
       }
       ((TNamed*)pTObject)->SetName(name.c_str());
       return this->addMonitorElement(path, pTObject, pMonitorElement);
     }
void dqm4hep::core::MonitorElementManager::cd ()
Go back to root directory.
Definition at line 100 of file MonitorElementManager.cc.
References m_storage.
     {
       m_storage.cd();
     }
StatusCode dqm4hep::core::MonitorElementManager::cd (const std::string & dirName)
Go to directory 'dirName'.
Definition at line 107 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.cd(dirName);
     }
StatusCode dqm4hep::core::MonitorElementManager::createQualityTest (TiXmlElement *const pXmlElement)
Create a quality test from the xml element.
The xml element must contain the attribute 'type' and 'name'
Definition at line 430 of file MonitorElementManager.cc.
References dqm4hep::core::StatusCodeException::getStatusCode(), dqm4hep::core::QualityTest::init(), dqm4hep::core::QualityTest::readSettings(), RETURN_RESULT_IF, and THROW_RESULT_IF.
     {
       std::string name, type;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "type", type));
       QualityTestMap::iterator findIter = m_qualityTestMap.find(name);
       if(m_qualityTestMap.end() != findIter)
         return STATUS_CODE_ALREADY_PRESENT;
       QualityTestFactoryMap::iterator findFactoryIter = m_qualityTestFactoryMap.find(type);
       if(m_qualityTestFactoryMap.end() == findFactoryIter)
         return STATUS_CODE_NOT_FOUND;
       QualityTest *const pQualityTest = findFactoryIter->second->createQualityTest(name);
       try
       {
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pQualityTest->readSettings(TiXmlHandle(pXmlElement)));
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pQualityTest->init());
         if(!m_qualityTestMap.insert(QualityTestMap::value_type(name, pQualityTest)).second)
           throw StatusCodeException(STATUS_CODE_FAILURE);
       }
       catch(const StatusCodeException &exception)
       {
         delete pQualityTest;
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::core::MonitorElementManager::dirExists (const std::string & dirName) const
Whether the directory exists.
Definition at line 156 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.dirExists(dirName);
     }
const std::string & dqm4hep::core::MonitorElementManager::fullPwd ()
Get the current directory full name.
Definition at line 135 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.current()->fullPath().getPath();
     }
StatusCode dqm4hep::core::MonitorElementManager::getMonitorElement (const std::string & name, MonitorElement *& monitorElement) const
Get the monitor element in the current directory (result by ptr reference)
Definition at line 377 of file MonitorElementManager.cc.
References dqm4hep::core::MonitorElement::name().
     {
       monitorElement = m_storage.findObject(
         [&name](const MonitorElement *elt){
           return (elt->name() == name);
         });
       if(nullptr == monitorElement)
         return STATUS_CODE_NOT_FOUND;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::getMonitorElement (const std::string & dirName, const std::string & name, MonitorElement *& monitorElement) const
Get the monitor element in the given directory (result by ptr reference)
Definition at line 392 of file MonitorElementManager.cc.
References dqm4hep::core::MonitorElement::name().
     {
       monitorElement = m_storage.findObject(dirName,
         [&name](const MonitorElement *elt){
           return (elt->name() == name);
         });
       if(nullptr == monitorElement)
         return STATUS_CODE_NOT_FOUND;
       return STATUS_CODE_SUCCESS;
     }
void dqm4hep::core::MonitorElementManager::getMonitorElements (std::vector< MonitorElement * > & monitorElements) const
Get all the monitor elements already booked by this module in all the directories.
Definition at line 370 of file MonitorElementManager.cc.
     {
       m_storage.getObjects(monitorElements);
     }
const Storage< MonitorElement > & dqm4hep::core::MonitorElementManager::getStorage () const private
Get the monitor element storage.
Definition at line 548 of file MonitorElementManager.cc.
     {
       return m_storage;
     }
StatusCode dqm4hep::core::MonitorElementManager::goUp ()
Navigate backward in the directory structure.
Definition at line 142 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.goUp();
     }
StatusCode dqm4hep::core::MonitorElementManager::handleMonitorElement (const std::string & path, TObject * pObject, MonitorElement *& pMonitorElement)
Add a monitor element from an external source.
WARNING : The ROOT object is NOT owned by the framework. The caller must delete the object on termination
Definition at line 237 of file MonitorElementManager.cc.
References dqm4hep::core::StatusCodeException::getStatusCode(), dqm4hep::core::MonitorElement::setPath(), and THROW_RESULT_IF.
     {
       PtrHandler<TObject> ptrObject(pObject, false);
       pMonitorElement = nullptr;
       try
       {
         pMonitorElement = new MonitorElement(ptrObject);
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_storage.add(path, pMonitorElement));
         pMonitorElement->setPath(path);
       }
       catch(StatusCodeException &e)
       {
         if(nullptr != pMonitorElement)
         {
           delete pMonitorElement;
           pMonitorElement = nullptr;
         }
         return e.getStatusCode();
       }
       catch(...)
       {
         if(nullptr != pMonitorElement)
         {
           delete pMonitorElement;
           pMonitorElement = nullptr;
         }
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::mkdir (const std::string & dirName)
Create the directory 'dirName'.
Definition at line 114 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.mkdir(dirName);
     }
const std::string & dqm4hep::core::MonitorElementManager::pwd ()
List the current directory content.
Get the current directory name
Definition at line 128 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.pwd();
     }
StatusCode dqm4hep::core::MonitorElementManager::readMonitorElement (const std::string & fileName, const std::string & path, const std::string & name, MonitorElement *& pMonitorElement)
Read TObject from file and add it to list.
The ROOT TObject is owned by the manager
Definition at line 274 of file MonitorElementManager.cc.
     {
       pMonitorElement = nullptr;
       std::unique_ptr<TFile> rootFile(new TFile(fileName.c_str(), "READ"));
       return this->readMonitorElement(rootFile.get(), path, name, pMonitorElement);
     }
StatusCode dqm4hep::core::MonitorElementManager::readMonitorElement (TFile * pTFile, const std::string & path, const std::string & name, MonitorElement *& pMonitorElement)
Read TObject from file and add it to list.
The ROOT TObject is owned by the manager
Definition at line 283 of file MonitorElementManager.cc.
References dqm_debug, and dqm4hep::core::Path::getPath().
     {
       pMonitorElement = nullptr;
       Path fullName = path;
       fullName += name;
       dqm_debug( "MonitorElementManager::readMonitorElement: looking for element {0}", fullName.getPath() );
       const bool objectStat(TObject::GetObjectStat());
       TObject::SetObjectStat(false);
       TObject *pTObject = pTFile->Get(fullName.getPath().c_str());
       TObject::SetObjectStat(objectStat);
       if(!pTObject)
         return STATUS_CODE_NOT_FOUND;
       return this->addMonitorElement(path, pTObject, pMonitorElement);
     }
StatusCode dqm4hep::core::MonitorElementManager::removeMonitorElement (const std::string & path, const std::string & name)
Remove the monitor element.
Definition at line 408 of file MonitorElementManager.cc.
References dqm4hep::core::MonitorElement::name(), and RETURN_RESULT_IF.
     {
       MonitorElement *pMonitorElement(nullptr);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, pMonitorElement));
       // look in qtest map first
       auto iter = m_monitorElementToQTestMap.find(pMonitorElement);
       if(m_monitorElementToQTestMap.end() != iter)
         m_monitorElementToQTestMap.erase(iter);
       // remove the element form storage. Call delete operator
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, m_storage.remove(path, [&name](const MonitorElement *pMonitorElement){
         return (pMonitorElement->name() == name);
       }));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::removeQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName)
Remove a quality test from the monitor element.
Definition at line 484 of file MonitorElementManager.cc.
References dqm4hep::core::MonitorElement::removeQualityTest(), and RETURN_RESULT_IF.
     {
       MonitorElement *pMonitorElement(nullptr);
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, pMonitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->removeQualityTest(qualityTestName));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::rmdir (const std::string & dirName)
Remove the directory 'dirName'.
Definition at line 149 of file MonitorElementManager.cc.
References m_storage.
     {
       return m_storage.rmdir(dirName);
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTest (const std::string & path, const std::string & name, const std::string & qualityTestName, QReportStorage & reports)
Definition at line 535 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReport(), RETURN_RESULT_IF, and dqm4hep::core::MonitorElement::runQualityTest().
     {
       MonitorElement *pMonitorElement(nullptr);
       QReport report;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, pMonitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->runQualityTest(qualityTestName, report));
       reports.addReport(report);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTests (QReportStorage & reports)
Definition at line 495 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReports(), dqm_error, dqm4hep::core::StatusCodeException::getStatusCode(), dqm4hep::core::MonitorElement::runQualityTests(), THROW_RESULT_IF, and dqm4hep::core::StatusCodeException::toString().
     {
       try
       {
         m_storage.iterate([&reports](const Directory<MonitorElement> *, MonitorElement *pMonitorElement){
           QReportMap reportMap;
           THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->runQualityTests(reportMap));
           reports.addReports(reportMap);
           return true;
         });
       }
       catch(StatusCodeException &exception)
       {
         dqm_error( "Failed to process qtests: {0}", exception.toString() );
         return exception.getStatusCode();
       }
       catch(...)
       {
         dqm_error( "Failed to process qtests: Unknown exception" );
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MonitorElementManager::runQualityTests (const std::string & path, const std::string & name, QReportStorage & reports)
Definition at line 522 of file MonitorElementManager.cc.
References dqm4hep::core::QReportStorage::addReports(), RETURN_RESULT_IF, and dqm4hep::core::MonitorElement::runQualityTests().
     {
       MonitorElement *pMonitorElement(nullptr);
       QReportMap reportMap;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->getMonitorElement(path, name, pMonitorElement));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, pMonitorElement->runQualityTests(reportMap));
       reports.addReports(reportMap);
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
MonitorElementToQTestMap dqm4hep::core::MonitorElementManager::m_monitorElementToQTestMap private
Definition at line 266 of file MonitorElementManager.h.
QualityTestFactoryMap dqm4hep::core::MonitorElementManager::m_qualityTestFactoryMap private
Definition at line 264 of file MonitorElementManager.h.
Referenced by MonitorElementManager(), and ~MonitorElementManager().
QualityTestMap dqm4hep::core::MonitorElementManager::m_qualityTestMap private
Definition at line 265 of file MonitorElementManager.h.
Referenced by ~MonitorElementManager().
Storage<MonitorElement> dqm4hep::core::MonitorElementManager::m_storage private
Definition at line 263 of file MonitorElementManager.h.
Referenced by addMonitorElement(), cd(), dirExists(), fullPwd(), goUp(), mkdir(), pwd(), and rmdir().
The documentation for this class was generated from the following files:
MonitorElementManager.h
MonitorElementManager.cc