DQMCore: dqm4hep::core::Path Class Reference
dqm4hep::core::Path Class Reference
Path class.
#include <Path.h>
Public Member Functions
Path ()
Constructor.
Path (const std::string &path)
Constructor with path.
std::vector< std::string > getSplitPath () const
Get the path, split by '/' in a vector.
const std::string & getPath () const
Get the path as string.
bool isValid () const
Whether the path is valid.
bool isRelative () const
Whether the path is relative (does not start with '/')
Path & operator+= (const Path &path)
+= operator
Path & operator= (const Path &path)
Assignment operator with path.
Path & operator= (const std::string &path)
Assignment operator with string.
Static Public Member Functions
static std::string & normalize (std::string &path)
Normalize the path.
Private Attributes
std::string m_path
Friends
Path operator+ (const Path &lhs, const Path &rhs)
std::ostream & operator<< (std::ostream &out, const Path &path)
<< operator
bool operator== (const Path &lhs, const Path &rhs)
== operator
Detailed Description
Path class.
Definition at line 42 of file Path.h.
Constructor & Destructor Documentation
dqm4hep::core::Path::Path ()
Constructor.
Definition at line 38 of file Path.cc.
     {
     }
dqm4hep::core::Path::Path (const std::string & path)
Constructor with path.
Definition at line 45 of file Path.cc.
References m_path, and normalize().
                                     :
         m_path(path)
     {
       Path::normalize(m_path);
     }
Member Function Documentation
const std::string & dqm4hep::core::Path::getPath () const
Get the path as string.
Definition at line 66 of file Path.cc.
References m_path.
Referenced by dqm4hep::core::MonitorElementManager::attachReference(), dqm4hep::core::MonitorElementManager::readMonitorElement(), and dqm4hep::core::Storage< T >::rmdir().
     {
       return m_path;
     }
std::vector< std::string > dqm4hep::core::Path::getSplitPath () const
Get the path, split by '/' in a vector.
Definition at line 53 of file Path.cc.
References isValid(), m_path, and dqm4hep::core::tokenize().
Referenced by dqm4hep::core::Storage< T >::cd(), dqm4hep::core::Storage< T >::find(), dqm4hep::core::Storage< T >::mkdir(), and dqm4hep::core::operator==().
     {
       if(!this->isValid())
         return std::vector<std::string>();
       std::vector<std::string> splitPath;
       dqm4hep::core::tokenize(m_path, splitPath, "/");
       return splitPath;
     }
bool dqm4hep::core::Path::isRelative () const
Whether the path is relative (does not start with '/')
Definition at line 86 of file Path.cc.
References isValid(), and m_path.
Referenced by dqm4hep::core::Storage< T >::cd(), dqm4hep::core::Storage< T >::find(), and dqm4hep::core::Storage< T >::mkdir().
     {
       if(!this->isValid())
         return false;
       if(m_path.empty())
         return true;
       if(m_path.at(0) == '/')
         return false;
       return true;
     }
bool dqm4hep::core::Path::isValid () const
Whether the path is valid.
Definition at line 73 of file Path.cc.
References dqm4hep::core::containsSpecialCharacters(), and m_path.
Referenced by dqm4hep::core::Storage< T >::cd(), dqm4hep::core::Storage< T >::find(), getSplitPath(), isRelative(), and dqm4hep::core::Storage< T >::mkdir().
     {
       if(dqm4hep::core::containsSpecialCharacters(m_path))
         return false;
       if(std::string::npos != m_path.find("//"))
         return false;
       return true;
     }
std::string & dqm4hep::core::Path::normalize (std::string & path) static
Normalize the path.
Replace all "//" and "/./" by "/" only characters
Definition at line 102 of file Path.cc.
Referenced by operator+=(), operator=(), and Path().
     {
       size_t pos = path.find("//");
       while(std::string::npos != pos)
       {
         path.replace(pos, 2, "/");
         pos = path.find("//");
       }
       pos = path.find("/./");
       while(std::string::npos != pos)
       {
         path.replace(pos, 3, "/");
         pos = path.find("/./");
       }
       return path;
     }
Path & dqm4hep::core::Path::operator+= (const Path & path)
+= operator
Definition at line 125 of file Path.cc.
References m_path, and normalize().
     {
       if(path.m_path.empty())
         return *this;
       if(m_path.empty())
       {
         m_path = path.m_path;
         return *this;
       }
       size_t pos = std::string::npos;
       pos = m_path.find_last_not_of("/");
       std::string path1 = (pos == std::string::npos) ? m_path : m_path.substr(0, pos+1);
       pos = path.m_path.find_first_not_of("/");
       std::string path2 = (pos == std::string::npos) ? path.m_path : path.m_path.substr(pos);
       m_path = path1 + "/" + path2;
       Path::normalize(m_path);
       return *this;
     }
Path & dqm4hep::core::Path::operator= (const Path & path)
Assignment operator with path.
Definition at line 152 of file Path.cc.
References m_path.
     {
       m_path = path.m_path;
       return *this;
     }
Path & dqm4hep::core::Path::operator= (const std::string & path)
Assignment operator with string.
Definition at line 160 of file Path.cc.
References m_path, and normalize().
     {
       m_path = path;
       Path::normalize(m_path);
       return *this;
     }
Friends And Related Function Documentation
Path operator+ (const Path & lhs, const Path & rhs) friend
operator
Definition at line 104 of file Path.h.
     {
       Path path(lhs.m_path);
       path += rhs;
       return path;
     }
std::ostream& operator<< (std::ostream & out, const Path & path) friend
<< operator
Definition at line 114 of file Path.h.
     {
       out << path.m_path;
       return out;
     }
bool operator== (const Path & lhs, const Path & rhs) friend
== operator
Definition at line 123 of file Path.h.
     {
       return (lhs.getSplitPath() == rhs.getSplitPath());
     }
Member Data Documentation
std::string dqm4hep::core::Path::m_path private
Definition at line 98 of file Path.h.
Referenced by getPath(), getSplitPath(), isRelative(), isValid(), dqm4hep::core::operator+(), operator+=(), dqm4hep::core::operator<<(), operator=(), and Path().
The documentation for this class was generated from the following files:
Path.h
Path.cc