DQMCore: dqm4hep::core::XmlHelper Class Reference
dqm4hep::core::XmlHelper Class Reference
XmlHelper class.
#include <XmlHelper.h>
Public Member Functions
template<>
StatusCode readValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, bool &t)
template<>
StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, std::string &attributeValue)
Static Public Member Functions
static StatusCode readXmlFile (const std::string &fileName, TiXmlDocument &document, StringMap &constants, bool processIncludes=true)
Read XML file.
template<typename T >
static StatusCode readValue (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, T &t)
Read a value from an xml element.
template<typename T >
static StatusCode readVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, std::vector< T > &vector)
Read a vector of values from a (space separated) list in an xml element.
template<typename T >
static StatusCode read2DVectorOfValues (const TiXmlHandle &xmlHandle, const std::string &xmlElementName, const std::string &rowName, std::vector< std::vector< T > > &vector)
Read a two-dimensional array of values into a vector of vectors.
template<typename T >
static StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, T &attributeValue)
Get the attribute of the xml element.
template<typename T , typename Validator >
static StatusCode getAttribute (const TiXmlElement *const pXmlElement, const std::string &attributeName, T &attributeValue, Validator validator)
Get the attribute of the xml element and use a validator to validate the value.
template<typename T >
static StatusCode readParameterValue (const TiXmlHandle &xmlHandle, const std::string &parameterName, T &t)
Read a parameter value from an xml element.
template<typename T , typename Validator >
static StatusCode readParameterValue (const TiXmlHandle &xmlHandle, const std::string &parameterName, T &t, Validator validator)
Read a parameter value from an xml element and use a validator to validate the value.
template<typename T >
static StatusCode readParameterValues (const TiXmlHandle &xmlHandle, const std::string &parameterName, std::vector< T > &vector)
Read a vector of values for a parameter from a (space separated) list in an xml element.
template<typename T , typename Validator >
static StatusCode readParameterValues (const TiXmlHandle &xmlHandle, const std::string &parameterName, std::vector< T > &vector, Validator validator)
Read a vector of values for a parameter from a (space separated) list in an xml element.
static StatusCode replaceAllXmlAttributes (TiXmlElement *pXmlElement, const ParameterMap &parameters)
Create a quality test.
static StatusCode performConstantReplacement (std::string &value, const StringMap &constants)
Perform replace of pattern ${constant} into value string.
Static Private Member Functions
static StatusCode processConstants (const std::string &fileName, TiXmlElement *parent, StringMap &constants, bool parseIncludes=true)
static StatusCode processConstant (TiXmlElement *parent, StringMap &constants)
static StatusCode processIncludeElements (const std::string &fileName, TiXmlElement *element, const StringMap &constants)
static StatusCode processIncludeElement (const std::string &fileName, TiXmlElement *element, const StringMap &constants, TiXmlDocument &document)
static StatusCode replaceConstants (TiXmlElement *element, const StringMap &constants)
Detailed Description
XmlHelper class.
Definition at line 44 of file XmlHelper.h.
Member Function Documentation
template<typename T > StatusCode dqm4hep::core::XmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, T & attributeValue) inline static
Get the attribute of the xml element.
Definition at line 265 of file XmlHelper.h.
References dqm4hep::core::TiXmlElement::Attribute(), and dqm4hep::core::stringToType().
Referenced by readParameterValue(), readParameterValues(), and replaceAllXmlAttributes().
     {
       if(NULL == pXmlElement)
         return STATUS_CODE_INVALID_PTR;
       const char *pAttributePtr(pXmlElement->Attribute(attributeName.c_str()));
       if(NULL == pAttributePtr)
         return STATUS_CODE_NOT_FOUND;
       std::string attributeStr(pAttributePtr);
       if(!dqm4hep::core::stringToType(attributeStr, attributeValue))
         return STATUS_CODE_FAILURE;
       return STATUS_CODE_SUCCESS;
     }
template<typename T , typename Validator > StatusCode dqm4hep::core::XmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, T & attributeValue, Validator validator) inline static
Get the attribute of the xml element and use a validator to validate the value.
Definition at line 286 of file XmlHelper.h.
References RETURN_RESULT_IF.
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute<T>(pXmlElement, attributeName, attributeValue));
       if(!validator(attributeValue))
         return STATUS_CODE_INVALID_PARAMETER;
       return STATUS_CODE_SUCCESS;
     }
template<> StatusCode dqm4hep::core::XmlHelper::getAttribute (const TiXmlElement *const pXmlElement, const std::string & attributeName, std::string & attributeValue) inline
Definition at line 299 of file XmlHelper.h.
References dqm4hep::core::TiXmlElement::Attribute().
     {
       if(NULL == pXmlElement)
         return STATUS_CODE_INVALID_PTR;
       const char *pAttributePtr(pXmlElement->Attribute(attributeName.c_str()));
       if(NULL == pAttributePtr)
         return STATUS_CODE_NOT_FOUND;
       attributeValue = pAttributePtr;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::performConstantReplacement (std::string & value, const StringMap & constants) static
Perform replace of pattern ${constant} into value string.
Definition at line 137 of file XmlHelper.cc.
References dqm_error.
Referenced by processConstant(), processIncludeElement(), and replaceConstants().
     {
       size_t pos = value.find("${") ;
       std::string original(value);
       while( pos != std::string::npos ) {
         size_t pos2 = value.find_first_of( "}", pos+2 ) ;
         if( pos2 == std::string::npos ) {
           dqm_error( "XMLHelper::performConstantReplacement : couldn't parse constant value !" ) ;
           return STATUS_CODE_FAILURE;
         }
         const std::string key( value.substr( pos+2 , pos2-pos-2 )) ;
         auto findConstant = constants.find( key ) ;
         const std::string replacementValue( findConstant != constants.end() ? findConstant->second : "" ) ;
         if( replacementValue.empty() ) {
           dqm_error( "XMLParser::performConstantReplacement : constant \"{0}\" not found in available constants !", key );
           return STATUS_CODE_FAILURE;
         }
         value.replace( pos , (pos2+1-pos) , replacementValue ) ;
         pos2 = pos + replacementValue.size() ; // new end position after replace
         pos = value.find("${", pos2) ; // find next possible key to replace
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::processConstant (TiXmlElement * parent, StringMap & constants) static private
Definition at line 94 of file XmlHelper.cc.
References dqm4hep::core::TiXmlElement::Attribute(), dqm_debug, dqm_error, dqm4hep::core::TiXmlNode::FirstChild(), performConstantReplacement(), RETURN_RESULT_IF, and dqm4hep::core::TiXmlNode::Value().
Referenced by processConstants().
     {
       if( ! element->Attribute("name") ) {
         dqm_error( "XmlHelper::processConstant : constant element without name !" ) ;
         return STATUS_CODE_FAILURE;
       }
       const std::string name( element->Attribute("name") ) ;
       if( name.empty() ) {
         dqm_error( "XmlHelper::processConstant : parsed empty constant name !" ) ;
         return STATUS_CODE_FAILURE;
       }
       if( constants.end() != constants.find( name ) ) {
         dqm_error( "XMLHelper::processConstant : constant \"{0}\" defined twice !", name );
         return STATUS_CODE_ALREADY_PRESENT;
       }
       std::string value ;
       if( element->Attribute("value") ) {
         value = element->Attribute("value") ;
       }
       else {
         if( element->FirstChild() )
           value = element->FirstChild()->Value() ;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::performConstantReplacement( value, constants ) );
       if( ! constants.insert( std::map<std::string, std::string>::value_type( name , value ) ).second ) {
         dqm_error( "XMLHelper::processConstant : couldn't add constant \"{0}\" to constant map !", name );
         return STATUS_CODE_FAILURE;
       }
       dqm_debug( "XMLHelper::processConstant: Read constant \"{0}\" , value = \"{1}\"", name, value) ;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::processConstants (const std::string & fileName, TiXmlElement * parent, StringMap & constants, bool parseIncludes = true) static private
Definition at line 63 of file XmlHelper.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::NextSiblingElement(), processConstant(), processIncludeElement(), and RETURN_RESULT_IF.
Referenced by readXmlFile().
     {
       for( TiXmlElement* child = parent->FirstChildElement() ; child ; child = child->NextSiblingElement() ) {
         if( std::string( child->Value() ) == "constant" ) {
           // process single constant
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processConstant( child , constants ) );
         }
         // need to process includes in constants section since some
         // constants may be defined in includes and could then be
         // used in next constant values
         else if ( std::string( child->Value() ) == "include" && parseIncludes ) {
           // process the include and returns the first and last elements found in the include
           TiXmlDocument document ;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processIncludeElement( fileName, child , constants , document ) );
           for( TiXmlElement *elt = document.FirstChildElement() ; elt ; elt =  elt->NextSiblingElement() ) {
             if ( elt->Value() == std::string( "constant" ) )
               RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processConstant( elt , constants ) );
           }
         }
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::processIncludeElement (const std::string & fileName, TiXmlElement * element, const StringMap & constants, TiXmlDocument & document) static private
Definition at line 217 of file XmlHelper.cc.
References dqm4hep::core::TiXmlElement::Attribute(), dqm_error, dqm4hep::core::TiXmlDocument::ErrorCol(), dqm4hep::core::TiXmlDocument::ErrorDesc(), dqm4hep::core::TiXmlDocument::ErrorRow(), dqm4hep::core::TiXmlDocument::LoadFile(), performConstantReplacement(), RETURN_RESULT_IF, and dqm4hep::core::TiXmlNode::Value().
Referenced by processConstants(), and processIncludeElements().
     {
       std::pair<TiXmlElement*, TiXmlElement*> firstAndLastElements(nullptr, nullptr) ;
       if( ! element->Attribute("ref") ) {
         dqm_error( "XmlHelper::processIncludeElement missing attribute \"ref\" in element <{0}/>", element->Value() );
         return STATUS_CODE_FAILURE;
       }
       std::string ref ( element->Attribute("ref") ) ;
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::performConstantReplacement( ref, constants ) );
       if( ref.size() < 5 || ref.substr( ref.size() - 4 ) != ".xml" ) {
         dqm_error( "XMLParser::processIncludeElement invalid ref file name \"{0}\" in element <{1}/>", ref, element->Value() );
         return STATUS_CODE_FAILURE;
       }
       std::string refFileName ;
       if( ref.at(0) != '/' ) {
           // relative path case
           // prepend with current file path
           size_t idx = fileName.find_last_of("/") ;
           std::string baseFileName ;
           if( idx != std::string::npos )
           {
               baseFileName = fileName.substr( 0 , idx ) + "/" ;
           }
           refFileName = baseFileName + ref ;
       }
       else {
           refFileName = ref ;
       }
       bool loadOkay = document.LoadFile( refFileName ) ;
       if( !loadOkay ) {
         dqm_error( "XMLParser::processIncludeElement error in file [{0}, row: {1}, col: {2}] : {3}", refFileName, document.ErrorRow(), document.ErrorCol(), document.ErrorDesc() );
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::processIncludeElements (const std::string & fileName, TiXmlElement * element, const StringMap & constants) static private
Definition at line 171 of file XmlHelper.cc.
References dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlNode::InsertAfterChild(), dqm4hep::core::TiXmlNode::NextSiblingElement(), processIncludeElement(), dqm4hep::core::TiXmlNode::RemoveChild(), RETURN_RESULT_IF, and dqm4hep::core::TiXmlNode::Value().
Referenced by readXmlFile().
     {
       TiXmlElement* child = element->FirstChildElement() ;
       while( 1 )
       {
           if( ! child )
               break ;
           if( child->Value() == std::string("constants") ) {
               child = child->NextSiblingElement() ;
               continue ;
           }
           if( child->Value() != std::string("include") ) {
               RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processIncludeElements( fileName, child , constants ));
               child = child->NextSiblingElement() ;
               continue ;
           }
           // process the include and returns the first and last elements found in the include
           TiXmlDocument document ;
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processIncludeElement( fileName, child , constants , document ) );
           // add them to the xml tree
           TiXmlNode *includeAfter( child ) ;
           for( TiXmlElement *includeElement = document.FirstChildElement() ; includeElement ; includeElement =  includeElement->NextSiblingElement() ) {
               includeAfter = element->InsertAfterChild( includeAfter, *includeElement ) ;
           }
           // tricky lines :
           // 1) Remove the include element
           element->RemoveChild(child) ;
           // 2) Go to the next sibling element of the last included element to skip nested <include> elements
           child = includeAfter->NextSiblingElement() ;
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::XmlHelper::read2DVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, const std::string & rowName, std::vector< std::vector< T > > & vector) inline static
Read a two-dimensional array of values into a vector of vectors.
Each row of values must be contained within <rowname></rowname> xml tags, whilst the values in the row must be space separated
Definition at line 226 of file XmlHelper.h.
References dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChild(), dqm4hep::core::TiXmlElement::GetText(), dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::stringToType(), and dqm4hep::core::tokenize().
     {
       TiXmlElement *pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
       if (NULL == pXmlElement)
         return STATUS_CODE_NOT_FOUND;
       TiXmlElement *pXmlRowElement = TiXmlHandle(pXmlElement).FirstChild(rowName).Element();
       if (NULL == pXmlRowElement)
         return STATUS_CODE_NOT_FOUND;
       for ( ; NULL != pXmlRowElement; pXmlRowElement = pXmlRowElement->NextSiblingElement(rowName))
       {
         std::vector<T> rowVector;
         StringVector tokens;
         dqm4hep::core::tokenize(pXmlRowElement->GetText(), tokens);
         for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; ++iter)
         {
           T t;
           if (!dqm4hep::core::stringToType(*iter, t))
             return STATUS_CODE_FAILURE;
           rowVector.push_back(t);
         }
         vector.push_back(rowVector);
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::XmlHelper::readParameterValue (const TiXmlHandle & xmlHandle, const std::string & parameterName, T & t) inline static
Read a parameter value from an xml element.
Definition at line 317 of file XmlHelper.h.
References dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::core::TiXmlNode::NextSiblingElement(), RETURN_RESULT_IF, and dqm4hep::core::stringToType().
Referenced by readParameterValue().
     {
       for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("parameter").Element(); NULL != pXmlElement;
           pXmlElement = pXmlElement->NextSiblingElement("parameter"))
       {
         std::string name;
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
         if(name != parameterName)
           continue;
         if (!dqm4hep::core::stringToType(pXmlElement->GetText(), t))
           return STATUS_CODE_FAILURE;
         return STATUS_CODE_SUCCESS;
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T , typename Validator > StatusCode dqm4hep::core::XmlHelper::readParameterValue (const TiXmlHandle & xmlHandle, const std::string & parameterName, T & t, Validator validator) inline static
Read a parameter value from an xml element and use a validator to validate the value.
Definition at line 340 of file XmlHelper.h.
References readParameterValue(), and RETURN_RESULT_IF.
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameterValue(xmlHandle, parameterName, t));
       if( ! validator(t) )
         return STATUS_CODE_INVALID_PARAMETER;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::XmlHelper::readParameterValues (const TiXmlHandle & xmlHandle, const std::string & parameterName, std::vector< T > & vector) inline static
Read a vector of values for a parameter from a (space separated) list in an xml element.
Definition at line 353 of file XmlHelper.h.
References dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChild(), getAttribute(), dqm4hep::core::TiXmlNode::NextSiblingElement(), RETURN_RESULT_IF, dqm4hep::core::stringToType(), and dqm4hep::core::tokenize().
Referenced by readParameterValues().
     {
       for (TiXmlElement *pXmlElement = xmlHandle.FirstChild("parameter").Element(); NULL != pXmlElement;
           pXmlElement = pXmlElement->NextSiblingElement("parameter"))
       {
         std::string name;
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
         if(name != parameterName)
           continue;
         StringVector tokens;
         dqm4hep::core::tokenize(pXmlElement->GetText(), tokens);
         for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; ++iter)
         {
           T t;
           if (!dqm4hep::core::stringToType(*iter, t))
             return STATUS_CODE_FAILURE;
           vector.push_back(t);
         }
         return STATUS_CODE_SUCCESS;
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T , typename Validator > StatusCode dqm4hep::core::XmlHelper::readParameterValues (const TiXmlHandle & xmlHandle, const std::string & parameterName, std::vector< T > & vector, Validator validator) inline static
Read a vector of values for a parameter from a (space separated) list in an xml element.
Definition at line 386 of file XmlHelper.h.
References readParameterValues(), and RETURN_RESULT_IF.
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readParameterValues(xmlHandle, parameterName, vector));
       if( ! validator(vector) )
         return STATUS_CODE_INVALID_PARAMETER;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::XmlHelper::readValue (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, T & t) inline static
Read a value from an xml element.
Definition at line 156 of file XmlHelper.h.
References dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChild(), dqm4hep::core::TiXmlElement::GetText(), and dqm4hep::core::stringToType().
Referenced by dqm4hep::core::MeanWithinExpectedTest::readSettings().
     {
       const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
       if (NULL == pXmlElement)
         return STATUS_CODE_NOT_FOUND;
       if (!dqm4hep::core::stringToType(pXmlElement->GetText(), t))
         return STATUS_CODE_FAILURE;
       return STATUS_CODE_SUCCESS;
     }
template<> StatusCode dqm4hep::core::XmlHelper::readValue (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, bool & t) inline
Definition at line 172 of file XmlHelper.h.
References dqm4hep::core::TiXmlNode::FirstChild(), and dqm4hep::core::TiXmlElement::GetText().
     {
       const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
       if (NULL == pXmlElement)
         return STATUS_CODE_NOT_FOUND;
       const std::string xmlElementString = pXmlElement->GetText();
       if ((xmlElementString == "1") || (xmlElementString == "true"))
       {
         t = true;
       }
       else if ((xmlElementString == "0") || (xmlElementString == "false"))
       {
         t = false;
       }
       else
       {
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::XmlHelper::readVectorOfValues (const TiXmlHandle & xmlHandle, const std::string & xmlElementName, std::vector< T > & vector) inline static
Read a vector of values from a (space separated) list in an xml element.
Definition at line 200 of file XmlHelper.h.
References dqm4hep::core::TiXmlHandle::Element(), dqm4hep::core::TiXmlHandle::FirstChild(), dqm4hep::core::TiXmlElement::GetText(), dqm4hep::core::stringToType(), and dqm4hep::core::tokenize().
     {
       const TiXmlElement *const pXmlElement = xmlHandle.FirstChild(xmlElementName).Element();
       if (NULL == pXmlElement)
         return STATUS_CODE_NOT_FOUND;
       StringVector tokens;
       dqm4hep::core::tokenize(pXmlElement->GetText(), tokens);
       for (StringVector::const_iterator iter = tokens.begin(), iterEnd = tokens.end(); iter != iterEnd; ++iter)
       {
         T t;
         if (!dqm4hep::core::stringToType(*iter, t))
           return STATUS_CODE_FAILURE;
         vector.push_back(t);
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::readXmlFile (const std::string & fileName, TiXmlDocument & document, StringMap & constants, bool processIncludes = true) static
Read XML file.
A constants section could possibly processed in the root element if found and may contains constant elements inside :
<constants>
  <constant name="MyConstant"> 42 <constant>
  <constant name="MySuperConstant"> ${MyConstant} is the answer <constant>
</constants>
Include elements such as :
<include ref="another_file_name.xml">
could be parsed if the flag processIncludes is set to true. The content of this file is processed as a raw replacment
Definition at line 37 of file XmlHelper.cc.
References dqm_error, dqm4hep::core::TiXmlDocument::ErrorCol(), dqm4hep::core::TiXmlDocument::ErrorDesc(), dqm4hep::core::TiXmlDocument::ErrorRow(), dqm4hep::core::TiXmlNode::FirstChildElement(), dqm4hep::core::TiXmlDocument::LoadFile(), processConstants(), processIncludeElements(), replaceConstants(), RETURN_RESULT_IF, and dqm4hep::core::TiXmlDocument::RootElement().
     {
       bool loaded = document.LoadFile(fileName);
       if(!loaded)
       {
         dqm_error( "Couldn't load xml file ['{0}', row: {1}, col: {2}] : {3}", fileName, document.ErrorRow(), document.ErrorCol(), document.ErrorDesc() );
         return STATUS_CODE_FAILURE;
       }
       TiXmlElement *root = document.RootElement();
       TiXmlElement *constantsElt = root->FirstChildElement("constants");
       if(constantsElt)
       {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processConstants( fileName, constantsElt, constants, processIncludes ));
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::processIncludeElements( fileName, root, constants ));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::replaceConstants( root, constants ));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::replaceAllXmlAttributes (TiXmlElement * pXmlElement, const ParameterMap & parameters) static
Create a quality test.
Works if the quality test factory has been registered firstCreate a monitor element from a xml handleCreate a monitor element from a xml handleCreate a monitor element from a xml handleCreate a monitor element from a xml handle and configure name, path and title from parameters (see DQM4HEP::replace())Replace all xml attribute recursively from the parameters map
Definition at line 385 of file XmlHelper.cc.
References dqm4hep::core::TiXmlNode::Clear(), dqm_debug, dqm_error, dqm4hep::core::TiXmlNode::FirstChildElement(), getAttribute(), dqm4hep::core::TiXmlNode::LinkEndChild(), dqm4hep::core::TiXmlNode::NextSiblingElement(), dqm4hep::core::TiXmlNode::NoChildren(), RETURN_RESULT_IF, dqm4hep::core::TiXmlElement::SetAttribute(), dqm4hep::core::stringToType(), and dqm4hep::core::tokenize().
     {
       for(auto paramIter = parameters.begin(), endParamIter = parameters.end() ;
           endParamIter != paramIter ; ++paramIter)
       {
         std::string key(paramIter->first);
         std::string value(paramIter->second);
         StringVector xmlElementNames;
         dqm4hep::core::tokenize(key, xmlElementNames, ".");
         TiXmlElement *pCurrentElement = pXmlElement;
         bool keyIsParameter = false;
         for(unsigned int e=0 ; e<xmlElementNames.size() ; e++)
         {
           std::string subKey(xmlElementNames.at(e));
           unsigned int eltId = 0;
           size_t posStart = subKey.find("[");
           if( posStart != std::string::npos )
           {
             if( subKey.back() != ']' )
             {
               dqm_error( "Missing ']' char in '{0}'", subKey );
               return STATUS_CODE_NOT_FOUND;
             }
             std::string eltIdStr = subKey.substr( posStart+1 , subKey.size() - (posStart+1) -1 );
             if( ! dqm4hep::core::stringToType( eltIdStr , eltId ) )
             {
               dqm_error( "Couldn't convert '{0}' to array id in key '{1}' !", eltIdStr, subKey);
               return STATUS_CODE_FAILURE;
             }
             subKey = subKey.substr( 0 , posStart );
           }
           // last sub key
           if( e == xmlElementNames.size()-1 )
           {
             if( keyIsParameter )
             {
               if( ! pCurrentElement->NoChildren() )
                 pCurrentElement->Clear();
               TiXmlText *pText = new TiXmlText( value );
               pCurrentElement->LinkEndChild(pText);
               dqm_debug( "Parameter key '{0}' set to {1}", key, value );
             }
             else
             {
               pCurrentElement->SetAttribute( subKey , value );
               dqm_debug( "Key attribute '{0}' set to ", key, value );
             }
           }
           else
           {
             if( e == xmlElementNames.size()-2 && subKey == "parameter" )
             {
               bool found = false;
               std::string parameterName( xmlElementNames.at(e+1) );
               for (TiXmlElement *pXmlElement = pCurrentElement->FirstChildElement("parameter"); NULL != pXmlElement;
                   pXmlElement = pXmlElement->NextSiblingElement("parameter"))
               {
                 std::string name;
                 RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::getAttribute(pXmlElement, "name", name));
                 if( name == parameterName )
                 {
                   pCurrentElement = pXmlElement;
                   found = true;
                   break;
                 }
               }
               if( ! found )
               {
                 dqm_error( "Key '{0}', subKey '{1}' xml element not found !", key, subKey );
                 return STATUS_CODE_NOT_FOUND;
               }
               keyIsParameter = true;
             }
             else
             {
               unsigned int currentElt = 0;
               TiXmlElement *pElt = pCurrentElement->FirstChildElement( subKey );
               while( pElt && currentElt < eltId )
               {
                 pElt = pElt->NextSiblingElement( subKey );
                 currentElt++;
               }
               pCurrentElement = pElt;
             }
             if( NULL == pCurrentElement )
             {
               dqm_error( "Key '{0}', subKey '{1}' xml element not found !", key, subKey );
               return STATUS_CODE_NOT_FOUND;
             }
           }
         }
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::XmlHelper::replaceConstants (TiXmlElement * element, const StringMap & constants) static private
Definition at line 266 of file XmlHelper.cc.
References dqm4hep::core::TiXmlElement::FirstAttribute(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlAttribute::Next(), dqm4hep::core::TiXmlNode::NextSibling(), performConstantReplacement(), RETURN_RESULT_IF, dqm4hep::core::TiXmlNode::SetValue(), dqm4hep::core::TiXmlNode::TINYXML_ELEMENT, dqm4hep::core::TiXmlNode::TINYXML_TEXT, dqm4hep::core::TiXmlElement::ToElement(), dqm4hep::core::TiXmlText::ToText(), and dqm4hep::core::TiXmlNode::ValueStr().
Referenced by readXmlFile().
     {
       if(constants.empty())
         return STATUS_CODE_SUCCESS;
       // replace constants in all attributes
       for(TiXmlAttribute *attribute = element->FirstAttribute(); attribute ; attribute = attribute->Next())
       {
         std::string value(attribute->ValueStr());
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::performConstantReplacement(value, constants));
         attribute->SetValue(value);
       }
       for(TiXmlNode *node = element->FirstChild() ; node ; node = node->NextSibling())
       {
         if(node->Type() == TiXmlNode::TINYXML_ELEMENT)
         {
           TiXmlElement *child = node->ToElement();
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::replaceConstants(child, constants));
         }
         else if(node->Type() == TiXmlNode::TINYXML_TEXT)
         {
           TiXmlText *child = node->ToText();
           std::string value(child->ValueStr());
           RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::performConstantReplacement(value, constants));
           child->SetValue(value);
         }
       }
       return STATUS_CODE_SUCCESS;
     }
The documentation for this class was generated from the following files:
XmlHelper.h
XmlHelper.cc