DQMCore: dqm4hep::core::Version Class Reference
dqm4hep::core::Version Class Reference
Version class.
#include <Version.h>
Public Member Functions
Version ()
Constructor.
Version (unsigned int major, unsigned int minor, unsigned int patch)
Constructor with version numbers.
~Version ()
Destructor.
unsigned int getMajor () const
Get the major version number.
unsigned int getMinor () const
Get the minor version number.
unsigned int getPatch () const
Get the patch version number.
void set (unsigned int major, unsigned int minor, unsigned int patch)
Set the complete version numbers.
const std::string & toString () const
Get the version to string.
Version & operator= (const Version &version)
Assignment operator.
xdrstream::Status stream (xdrstream::StreamingMode mode, xdrstream::IODevice *pDevice, xdrstream::xdr_version_t version=0)
Private Attributes
unsigned int m_major
unsigned int m_minor
unsigned int m_patch
std::string m_versionString
Detailed Description
Version class.
Definition at line 45 of file Version.h.
Constructor & Destructor Documentation
dqm4hep::core::Version::Version ()
Constructor.
Definition at line 35 of file Version.cc.
                      :
         m_major( 0 ),
         m_minor( 0 ),
         m_patch( 0 )
     {
       /* nop */
     }
dqm4hep::core::Version::Version (unsigned int major, unsigned int minor, unsigned int patch)
Constructor with version numbers.
Definition at line 45 of file Version.cc.
References m_major, m_minor, m_patch, and set().
     {
       set( m_major, m_minor, m_patch );
     }
dqm4hep::core::Version::~Version ()
Destructor.
Definition at line 52 of file Version.cc.
     {
       /* nop */
     }
Member Function Documentation
unsigned int dqm4hep::core::Version::getMajor () const
Get the major version number.
Definition at line 59 of file Version.cc.
References m_major.
Referenced by dqm4hep::core::operator<(), dqm4hep::core::operator<=(), and dqm4hep::core::operator==().
     {
       return m_major;
     }
unsigned int dqm4hep::core::Version::getMinor () const
Get the minor version number.
Definition at line 66 of file Version.cc.
References m_minor.
Referenced by dqm4hep::core::operator<(), dqm4hep::core::operator<=(), and dqm4hep::core::operator==().
     {
       return m_minor;
     }
unsigned int dqm4hep::core::Version::getPatch () const
Get the patch version number.
Definition at line 73 of file Version.cc.
References m_patch.
Referenced by dqm4hep::core::operator<(), dqm4hep::core::operator<=(), and dqm4hep::core::operator==().
     {
       return m_patch;
     }
Version & dqm4hep::core::Version::operator= (const Version & version)
Assignment operator.
Definition at line 99 of file Version.cc.
References m_major, m_minor, m_patch, m_versionString, and toString().
     {
       m_major = version.m_major;
       m_minor = version.m_minor;
       m_patch = version.m_patch;
       m_versionString = version.toString();
       return *this;
     }
void dqm4hep::core::Version::set (unsigned int major, unsigned int minor, unsigned int patch)
Set the complete version numbers.
Definition at line 80 of file Version.cc.
References m_major, m_minor, m_patch, and m_versionString.
Referenced by stream(), and Version().
     {
       m_major = major;
       m_minor = minor;
       m_patch = patch;
       std::stringstream ss;
       ss << m_major << "." << m_minor << "." << m_patch;
       m_versionString = ss.str();
     }
xdrstream::Status dqm4hep::core::Version::stream (xdrstream::StreamingMode mode, xdrstream::IODevice * pDevice, xdrstream::xdr_version_t version = 0)
Definition at line 172 of file Version.cc.
References m_major, m_minor, m_patch, and set().
     {
       if( xdrstream::XDR_READ_STREAM == mode )
       {
         uint32_t major, minor, patch;
         XDR_STREAM( pDevice->read( & major ) );
         XDR_STREAM( pDevice->read( & minor ) );
         XDR_STREAM( pDevice->read( & patch ) );
         this->set( major, minor, patch );
       }
       else
       {
         XDR_STREAM( pDevice->write<uint32_t>( & m_major ) );
         XDR_STREAM( pDevice->write<uint32_t>( & m_minor ) );
         XDR_STREAM( pDevice->write<uint32_t>( & m_patch ) );
       }
       return xdrstream::XDR_SUCCESS;
     }
const std::string & dqm4hep::core::Version::toString () const
Get the version to string.
Definition at line 92 of file Version.cc.
References m_versionString.
Referenced by operator=().
     {
       return m_versionString;
     }
Member Data Documentation
unsigned int dqm4hep::core::Version::m_major private
Definition at line 89 of file Version.h.
Referenced by getMajor(), operator=(), set(), stream(), and Version().
unsigned int dqm4hep::core::Version::m_minor private
Definition at line 90 of file Version.h.
Referenced by getMinor(), operator=(), set(), stream(), and Version().
unsigned int dqm4hep::core::Version::m_patch private
Definition at line 91 of file Version.h.
Referenced by getPatch(), operator=(), set(), stream(), and Version().
std::string dqm4hep::core::Version::m_versionString private
Definition at line 92 of file Version.h.
Referenced by operator=(), set(), and toString().
The documentation for this class was generated from the following files:
Version.h
Version.cc