DQMCore: dqm4hep::core::QualityTest Class Reference
dqm4hep::core::QualityTest Class Reference abstract
QualityTest class.
#include <QualityTest.h>
Public Member Functions
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *pMonitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle)=0
Read the settings from the xml handle.
virtual StatusCode init ()
Initialize the quality test.
Protected Member Functions
virtual StatusCode userRun (MonitorElement *pMonitorElement, QualityTestReport &report)=0
Runs a quality test on the given monitor element.
virtual bool canRun (MonitorElement *pMonitorElement) const =0
Whether the quality test can be run on the monitor element.
void fillBasicInfo (MonitorElement *pMonitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Protected Attributes
std::string m_description
Quality test description.
Private Attributes
std::string m_type
Quality test type (usually class name)
std::string m_name
Quality test name.
Detailed Description
QualityTest class.
Definition at line 159 of file QualityTest.h.
Constructor & Destructor Documentation
dqm4hep::core::QualityTest::QualityTest (const std::string & type, const std::string & name)
Constructor.
Definition at line 314 of file QualityTest.cc.
                                                                          :
       m_type(type),
       m_name(name),
       m_description("")
     {
       /* nop */
     }
dqm4hep::core::QualityTest::~QualityTest () virtual
Destructor.
Definition at line 324 of file QualityTest.cc.
     {
       /* nop */
     }
Member Function Documentation
virtual bool dqm4hep::core::QualityTest::canRun (MonitorElement * pMonitorElement) const protected pure virtual
Whether the quality test can be run on the monitor element.
Implemented in dqm4hep::core::MeanWithinExpectedTest.
Referenced by run().
const std::string & dqm4hep::core::QualityTest::description () const
Get the quality test description.
Definition at line 345 of file QualityTest.cc.
References m_description.
Referenced by fillBasicInfo().
     {
       return m_description;
     }
void dqm4hep::core::QualityTest::fillBasicInfo (MonitorElement * pMonitorElement, QualityTestReport & report) const protected
Fill basic info in the qtest report.
Must be called at start of qtest run
Definition at line 396 of file QualityTest.cc.
References description(), dqm4hep::core::QualityTestReport::m_extraInfos, dqm4hep::core::QualityTestReport::m_isSuccessful, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_monitorElementName, dqm4hep::core::QualityTestReport::m_monitorElementPath, dqm4hep::core::QualityTestReport::m_monitorElementType, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::QualityTestReport::m_qualityTestDescription, dqm4hep::core::QualityTestReport::m_qualityTestName, dqm4hep::core::QualityTestReport::m_qualityTestType, dqm4hep::core::MonitorElement::name(), name(), dqm4hep::core::MonitorElement::path(), dqm4hep::core::MonitorElement::type(), and type().
Referenced by run().
     {
       report.m_qualityTestName = this->name();
       report.m_qualityTestType = this->type();
       report.m_qualityTestDescription = this->description();
       report.m_monitorElementType = pMonitorElement->type();
       report.m_monitorElementName = pMonitorElement->name();
       report.m_monitorElementPath = pMonitorElement->path();
       report.m_quality = 0.f;
       report.m_message = "";
       report.m_isSuccessful = false;
       report.m_extraInfos.clear();
     }
StatusCode dqm4hep::core::QualityTest::init () inline virtual
Initialize the quality test.
Definition at line 236 of file QualityTest.h.
Referenced by dqm4hep::core::MonitorElementManager::createQualityTest().
     {
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::QualityTest::name () const
Get the quality test name (unique identifier)
Definition at line 338 of file QualityTest.cc.
References m_name.
Referenced by dqm4hep::core::MonitorElement::addQualityTest(), and fillBasicInfo().
     {
       return m_name;
     }
virtual StatusCode dqm4hep::core::QualityTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) pure virtual
Read the settings from the xml handle.
Implemented in dqm4hep::core::MeanWithinExpectedTest.
Referenced by dqm4hep::core::MonitorElementManager::createQualityTest().
void dqm4hep::core::QualityTest::run (MonitorElement * pMonitorElement, QualityTestReport & report)
Perform the quality test result and fill the quality test report.
Definition at line 352 of file QualityTest.cc.
References canRun(), fillBasicInfo(), dqm4hep::core::QualityTestReport::m_isSuccessful, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, THROW_RESULT_IF, dqm4hep::core::StatusCodeException::toString(), and userRun().
     {
       this->fillBasicInfo(pMonitorElement, report);
       if(!this->canRun(pMonitorElement))
       {
         report.m_message = "Couldn't run quality test: canRun() failed";
         report.m_quality = 0.f;
         report.m_isSuccessful = false;
         return;
       }
       try
       {
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->userRun(pMonitorElement, report));
       }
       catch(StatusCodeException &exception)
       {
         const std::string message("Caught StatusCodeException while run QTest: " + exception.toString());
         if(!report.m_message.empty())
           report.m_message + " " + message;
         else
           report.m_message = message;
         report.m_quality = 0.f;
         report.m_isSuccessful = false;
       }
       catch(...)
       {
         const std::string message("Caught unknown exception while run QTest");
         if(!report.m_message.empty())
           report.m_message + " " + message;
         else
           report.m_message = message;
         report.m_quality = 0.f;
         report.m_isSuccessful = false;
       }
     }
const std::string & dqm4hep::core::QualityTest::type () const
Get the quality test type.
Definition at line 331 of file QualityTest.cc.
References m_type.
Referenced by fillBasicInfo().
     {
       return m_type;
     }
virtual StatusCode dqm4hep::core::QualityTest::userRun (MonitorElement * pMonitorElement, QualityTestReport & report) protected pure virtual
Runs a quality test on the given monitor element.
Implemented in dqm4hep::core::MeanWithinExpectedTest.
Referenced by run().
Member Data Documentation
std::string dqm4hep::core::QualityTest::m_description protected
Quality test description.
Definition at line 213 of file QualityTest.h.
Referenced by description(), and dqm4hep::core::MeanWithinExpectedTest::MeanWithinExpectedTest().
std::string dqm4hep::core::QualityTest::m_name private
Quality test name.
Definition at line 210 of file QualityTest.h.
Referenced by name().
std::string dqm4hep::core::QualityTest::m_type private
Quality test type (usually class name)
Definition at line 209 of file QualityTest.h.
Referenced by type().
The documentation for this class was generated from the following files:
QualityTest.h
QualityTest.cc