DQMCore: dqm4hep::core::DBInterface Class Reference
dqm4hep::core::DBInterface Class Reference
DBInterface class.
#include <DBInterface.h>
Public Member Functions
DBInterface ()
Constructor.
DBInterface (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Constructor.
virtual ~DBInterface ()
Destructor.
StatusCode connect ()
Connect to the mysql server.
StatusCode disconnect ()
Disconnect from the database.
StatusCode connect (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Connect to the database.
StatusCode set (const std::string &host, const std::string &user, const std::string &password, const std::string &database)
Set host, user, password and database.
const std::string & getHost () const
Get the host.
const std::string & getUser () const
Get the user name.
const std::string & getPassword () const
Get the password.
const std::string & getDataBase () const
Get the data base name.
StatusCode queryRaw (const std::string &query, void *&pResult)
Send query to database The result is not converted.
template<typename T >
StatusCode query (const std::string &query, T &result)
Send query to database.
template<typename T >
StatusCode queryVector (const std::string &query, std::vector< T > &result)
Send query to database.
template<typename Handler >
StatusCode queryAndHandle (const std::string &query, Handler handler)
Send query to database The result is passed in the handler function for user parsing.
StatusCode execute (const std::string &query)
Execute the query (no result expected)
bool isConnected ()
Whether a connection is being handled.
StatusCode queryConfigFileContent (const std::string &configFileName, std::string &fileContents)
Query a config file content stored in the DQM4HEP data base (table CONFIG_FILES)
StatusCode queryConfigFileDescription (const std::string &configFileName, std::string &fileDescription)
Query a config file description.
StatusCode insertConfigFile (const std::string &localFileName, const std::string &fileNameEntry, const std::string &fileDescription="", bool forceReplace=false)
Insert a new new config file entry in the database.
Private Attributes
MYSQL * m_pMySQL
std::string m_host
std::string m_user
std::string m_password
std::string m_database
bool m_isConnected
Detailed Description
DBInterface class.
Definition at line 45 of file DBInterface.h.
Constructor & Destructor Documentation
dqm4hep::core::DBInterface::DBInterface ()
Constructor.
Definition at line 38 of file DBInterface.cc.
                              :
         m_pMySQL(NULL),
         m_isConnected(false)
     {
     }
dqm4hep::core::DBInterface::DBInterface (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Constructor.
Connect to data base
Definition at line 47 of file DBInterface.cc.
References connect(), and set().
                                                                                                                                :
         m_pMySQL(NULL),
         m_isConnected(false)
     {
       this->set(host, user, password, database);
       this->connect();
     }
dqm4hep::core::DBInterface::~DBInterface () virtual
Destructor.
Definition at line 57 of file DBInterface.cc.
References disconnect(), and isConnected().
     {
       if(this->isConnected())
         this->disconnect();
     }
Member Function Documentation
StatusCode dqm4hep::core::DBInterface::connect ()
Connect to the mysql server.
Definition at line 65 of file DBInterface.cc.
References dqm_error, execute(), dqm4hep::core::StatusCodeException::getStatusCode(), isConnected(), m_database, m_host, m_isConnected, m_password, m_pMySQL, m_user, query(), and THROW_RESULT_IF.
Referenced by connect(), and DBInterface().
     {
       if(this->isConnected())
         return STATUS_CODE_ALREADY_INITIALIZED;
       try
       {
         // create mysql instance
         m_pMySQL = mysql_init(NULL);
         if(!m_pMySQL)
         {
           dqm_error( "Couldn't create mysql instance : {0}", mysql_error(m_pMySQL) );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         // create connection to database
         if(NULL == mysql_real_connect(m_pMySQL, m_host.c_str(), m_user.c_str(), m_password.c_str(),
             NULL, 0, NULL, 0))
         {
           dqm_error( "Couldn't initialize mysql connection : {0}", mysql_error(m_pMySQL) );
           throw StatusCodeException(STATUS_CODE_FAILURE);
         }
         m_isConnected = true;
         // select data base
         std::stringstream query;
         query << "USE " << m_database << " ;";
         THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(query.str()));
       }
       catch(const StatusCodeException &exception)
       {
         if(m_pMySQL)
           mysql_close(m_pMySQL);
         m_isConnected = false;
         return exception.getStatusCode();
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::connect (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Connect to the database.
Not possible if a connection is being handled. Use disconnect() first and then connect()
Definition at line 127 of file DBInterface.cc.
References connect(), RETURN_RESULT_IF, and set().
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->set(host, user, password, database));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->connect());
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::disconnect ()
Disconnect from the database.
Definition at line 112 of file DBInterface.cc.
References isConnected(), m_isConnected, and m_pMySQL.
Referenced by ~DBInterface().
     {
       if(this->isConnected())
         return STATUS_CODE_UNCHANGED;
       if(m_pMySQL)
         mysql_close(m_pMySQL);
       m_isConnected = false;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::execute (const std::string & query)
Execute the query (no result expected)
Definition at line 215 of file DBInterface.cc.
References dqm_error, isConnected(), and m_pMySQL.
Referenced by connect(), insertConfigFile(), queryConfigFileContent(), and queryConfigFileDescription().
     {
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       if(mysql_query(m_pMySQL, query.c_str()))
       {
         dqm_error( "MySQL query failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       return STATUS_CODE_SUCCESS;
     }
const std::string & dqm4hep::core::DBInterface::getDataBase () const
Get the data base name.
Definition at line 173 of file DBInterface.cc.
References m_database.
     {
       return m_database;
     }
const std::string & dqm4hep::core::DBInterface::getHost () const
Get the host.
Definition at line 152 of file DBInterface.cc.
References m_host.
     {
       return m_host;
     }
const std::string & dqm4hep::core::DBInterface::getPassword () const
Get the password.
Definition at line 166 of file DBInterface.cc.
References m_password.
     {
       return m_password;
     }
const std::string & dqm4hep::core::DBInterface::getUser () const
Get the user name.
Definition at line 159 of file DBInterface.cc.
References m_user.
     {
       return m_user;
     }
StatusCode dqm4hep::core::DBInterface::insertConfigFile (const std::string & localFileName, const std::string & fileNameEntry, const std::string & fileDescription = "", bool forceReplace = false)
Insert a new new config file entry in the database.
Definition at line 314 of file DBInterface.cc.
References dqm_error, execute(), isConnected(), m_database, query(), and RETURN_RESULT_IF.
     {
       if(localFileName.empty() || fileNameEntry.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       std::ifstream ifile;
       ifile.open(localFileName.c_str(), std::ios::in);
       if(!ifile.is_open())
       {
         dqm_error( "Couln't open file '{0}' !", localFileName );
         return STATUS_CODE_FAILURE;
       }
       std::string fileContents;
       while(!ifile.eof())
       {
         std::string str;
         getline(ifile, str);
         fileContents += str + "\n";
       }
       if(fileContents.empty())
         return STATUS_CODE_FAILURE;
       std::string queryUse = "USE " + m_database + " ;";
       // construct the mysql query
       std::stringstream query;
       if(forceReplace)
         query << "REPLACE ";
       else
         query << "INSERT ";
       query << "INTO CONFIG_FILES VALUES "
           << "('" << fileNameEntry << "' ,"
           << "'" << fileDescription << "' ,"
           << "'" << fileContents << "') ;";
       // select DQM4HEP database
       if(m_database != "dqm4hep")
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
       StatusCode statusCode = this->execute(query.str());
       if(STATUS_CODE_SUCCESS != statusCode)
       {
         // select again the current database
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
         return statusCode;
       }
       // select again the current database
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
       return STATUS_CODE_SUCCESS;
     }
bool dqm4hep::core::DBInterface::isConnected ()
Whether a connection is being handled.
Definition at line 231 of file DBInterface.cc.
References m_isConnected.
Referenced by connect(), disconnect(), execute(), insertConfigFile(), query(), queryAndHandle(), queryConfigFileContent(), queryConfigFileDescription(), queryRaw(), queryVector(), set(), and ~DBInterface().
     {
       return m_isConnected;
     }
template<typename T > StatusCode dqm4hep::core::DBInterface::query (const std::string & query, T & result) inline
Send query to database.
The result is streamed in type T using DQM4HEP::stringToType()
Definition at line 162 of file DBInterface.h.
References dqm_error, isConnected(), m_pMySQL, and dqm4hep::core::stringToType().
Referenced by connect(), insertConfigFile(), queryConfigFileContent(), and queryConfigFileDescription().
     {
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       if(mysql_query(m_pMySQL, query.c_str()))
       {
         dqm_error( "MySQL query failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
       if(!pMySQLResult)
       {
         dqm_error( "MySQL store result failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_ROW row = mysql_fetch_row(pMySQLResult);
       if(!dqm4hep::core::stringToType(row[0], result))
       {
         mysql_free_result(pMySQLResult);
         return STATUS_CODE_FAILURE;
       }
       mysql_free_result(pMySQLResult);
       return STATUS_CODE_SUCCESS;
     }
template<typename Handler > StatusCode dqm4hep::core::DBInterface::queryAndHandle (const std::string & query, Handler handler) inline
Send query to database The result is passed in the handler function for user parsing.
Definition at line 236 of file DBInterface.h.
References dqm_error, isConnected(), and m_pMySQL.
     {
       if( ! this->isConnected() )
         return STATUS_CODE_NOT_INITIALIZED;
       if(mysql_query(m_pMySQL, query.c_str()))
       {
         dqm_error( "MySQL query failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
       if(!pMySQLResult)
       {
         dqm_error( "MySQL store result failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       handler( pMySQLResult );
       mysql_free_result(pMySQLResult);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::queryConfigFileContent (const std::string & configFileName, std::string & fileContents)
Query a config file content stored in the DQM4HEP data base (table CONFIG_FILES)
Definition at line 238 of file DBInterface.cc.
References execute(), isConnected(), m_database, query(), queryRaw(), and RETURN_RESULT_IF.
     {
       if(configFileName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       // select DQM4HEP database
       if(m_database != "dqm4hep")
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
       std::string queryUse = "USE " + m_database + " ;";
       std::stringstream query;
       query << "SELECT CONTENTS FROM CONFIG_FILES WHERE FILE_NAME=\"" << configFileName << "\" ;";
       void *pFileContent = NULL;
       StatusCode statusCode = this->queryRaw(query.str(), pFileContent);
       if(statusCode != STATUS_CODE_SUCCESS)
       {
         // select again the current database
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
         return statusCode;
       }
       fileContents = (char *) pFileContent;
       // select again the current database
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::queryConfigFileDescription (const std::string & configFileName, std::string & fileDescription)
Query a config file description.
Definition at line 276 of file DBInterface.cc.
References execute(), isConnected(), m_database, query(), queryRaw(), and RETURN_RESULT_IF.
     {
       if(configFileName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       // select DQM4HEP database
       if(m_database != "dqm4hep")
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute("USE DQM4HEP ;"));
       std::string queryUse = "USE " + m_database + " ;";
       std::stringstream query;
       query << "SELECT DESCRIPTION FROM CONFIG_FILES WHERE FILE_NAME=\"" << configFileName << "\" ;";
       void *pFileDescription = NULL;
       StatusCode statusCode = this->queryRaw(query.str(), pFileDescription);
       if(statusCode != STATUS_CODE_SUCCESS)
       {
         // select again the current database
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
         return statusCode;
       }
       fileDescription = (char *) pFileDescription;
       // select again the current database
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->execute(queryUse));
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::queryRaw (const std::string & query, void *& pResult)
Send query to database The result is not converted.
Definition at line 180 of file DBInterface.cc.
References dqm_error, isConnected(), and m_pMySQL.
Referenced by queryConfigFileContent(), and queryConfigFileDescription().
     {
       pResult = NULL;
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       if(mysql_query(m_pMySQL, query.c_str()))
       {
         dqm_error( "MySQL query failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
       if(!pMySQLResult)
       {
         dqm_error( "MySQL store result failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_ROW row = mysql_fetch_row(pMySQLResult);
       pResult = (void *) row[0];
       mysql_free_result(pMySQLResult);
       if(NULL == pResult)
         return STATUS_CODE_FAILURE;
       return STATUS_CODE_SUCCESS;
     }
template<typename T > StatusCode dqm4hep::core::DBInterface::queryVector (const std::string & query, std::vector< T > & result) inline
Send query to database.
The result is streamed in a vector. Each value of the vector is streamed using DQM4HEP::stringToType()
Definition at line 197 of file DBInterface.h.
References dqm_error, isConnected(), m_pMySQL, and dqm4hep::core::stringToType().
     {
       if(!this->isConnected())
         return STATUS_CODE_NOT_INITIALIZED;
       if(mysql_query(m_pMySQL, query.c_str()))
       {
         dqm_error( "MySQL query failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_RES *pMySQLResult = mysql_store_result(m_pMySQL);
       if(!pMySQLResult)
       {
         dqm_error( "MySQL store result failed : {0}", mysql_error(m_pMySQL) );
         return STATUS_CODE_FAILURE;
       }
       MYSQL_ROW row;
       while( (row = mysql_fetch_row(pMySQLResult)) )
       {
         T value = T();
         if(!dqm4hep::core::stringToType(row[0], value))
           continue;
         result.push_back(value);
       }
       mysql_free_result(pMySQLResult);
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::DBInterface::set (const std::string & host, const std::string & user, const std::string & password, const std::string & database)
Set host, user, password and database.
Not possible if a connection is being handled. Use disconnect() first and then connect()
Definition at line 137 of file DBInterface.cc.
References isConnected(), m_database, m_host, m_password, and m_user.
Referenced by connect(), and DBInterface().
     {
       if(this->isConnected())
         return STATUS_CODE_NOT_ALLOWED;
       m_host = host;
       m_user = user;
       m_password = password;
       m_database = database;
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
std::string dqm4hep::core::DBInterface::m_database private
Definition at line 153 of file DBInterface.h.
Referenced by connect(), getDataBase(), insertConfigFile(), queryConfigFileContent(), queryConfigFileDescription(), and set().
std::string dqm4hep::core::DBInterface::m_host private
Definition at line 150 of file DBInterface.h.
Referenced by connect(), getHost(), and set().
bool dqm4hep::core::DBInterface::m_isConnected private
Definition at line 155 of file DBInterface.h.
Referenced by connect(), disconnect(), and isConnected().
std::string dqm4hep::core::DBInterface::m_password private
Definition at line 152 of file DBInterface.h.
Referenced by connect(), getPassword(), and set().
MYSQL* dqm4hep::core::DBInterface::m_pMySQL private
Definition at line 148 of file DBInterface.h.
Referenced by connect(), disconnect(), execute(), query(), queryAndHandle(), queryRaw(), and queryVector().
std::string dqm4hep::core::DBInterface::m_user private
Definition at line 151 of file DBInterface.h.
Referenced by connect(), getUser(), and set().
The documentation for this class was generated from the following files:
DBInterface.h
DBInterface.cc