DQMCore: TCLAP::ValueArg< T > Class Template Reference
TCLAP::ValueArg< T > Class Template Reference
The basic labeled argument that parses a value.
#include <ValueArg.h>
Public Member Functions
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, CmdLineInterface &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, CmdLineInterface &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, Visitor *v=NULL)
Labeled ValueArg constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
T & getValue ()
Returns the value of the argument.
virtual std::string shortID (const std::string &val="val") const
Specialization of shortID.
virtual std::string longID (const std::string &val="val") const
Specialization of longID.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
virtual void addToList (std::list< Arg * > &argList) const
Adds this to the specified list of Args.
virtual bool operator== (const Arg &a) const
Operator ==.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
void forceRequired ()
Sets _required to true.
void xorSet ()
Sets the _alreadySet value to true.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
void setRequireLabel (const std::string &s)
Sets the requireLabel.
virtual bool allowMore ()
Used for MultiArgs and XorHandler to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
Protected Member Functions
void _extractValue (const std::string &val)
Extracts the value from the string.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Vistitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes
T _value
The value parsed from the command line.
T _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
std::string _typeDesc
A human readable description of the type to be parsed.
Constraint< T > * _constraint
A Constraint this Arg must conform to.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single work namd indentifying the argument.
std::string _description
Description of the argument.
bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
Visitor * _visitor
A pointer to a vistitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _xorSet
Indicates that the arg was set as part of an XOR and not on the command line.
bool _acceptsMultipleValues
Private Member Functions
ValueArg (const ValueArg< T > &rhs)
Prevent accidental copying.
ValueArg< T > & operator= (const ValueArg< T > &rhs)
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static void beginIgnoring ()
Begin ignoring arguments since the "--" argument was specified.
static bool ignoreRest ()
Whether to ignore the rest.
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Detailed Description
template<class T>
class TCLAP::ValueArg< T >
The basic labeled argument that parses a value.
This is a template class, which means the type T defines the type that a given object will attempt to parse when the flag/name is matched on the command line. While there is nothing stopping you from creating an unflagged ValueArg, it is unwise and would cause significant problems. Instead use an UnlabeledValueArg.
Definition at line 43 of file ValueArg.h.
Constructor & Destructor Documentation
template<class T > TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, Visitor * v = NULL)
Labeled ValueArg constructor.
Constructor implementation.
You could conceivably call this constructor with a blank flag, but that would make you a bad person. It would also cause an exception to be thrown. If you want an unlabeled argument, use the other constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 252 of file ValueArg.h.
 : Arg(flag, name, desc, req, true, v),
   _value( val ),
   _default( val ),
   _typeDesc( typeDesc ),
   _constraint( NULL )
 { }
template<class T > TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, CmdLineInterface & parser, Visitor * v = NULL)
Labeled ValueArg constructor.
You could conceivably call this constructor with a blank flag, but that would make you a bad person. It would also cause an exception to be thrown. If you want an unlabeled argument, use the other constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 267 of file ValueArg.h.
References TCLAP::CmdLineInterface::add().
 : Arg(flag, name, desc, req, true, v),
   _value( val ),
   _default( val ),
   _typeDesc( typeDesc ),
   _constraint( NULL )
 {
     parser.add( this );
 }
template<class T > TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, Constraint< T > * constraint, CmdLineInterface & parser, Visitor * v = NULL)
Labeled ValueArg constructor.
You could conceivably call this constructor with a blank flag, but that would make you a bad person. It would also cause an exception to be thrown. If you want an unlabeled argument, use the other constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 300 of file ValueArg.h.
References TCLAP::CmdLineInterface::add().
 : Arg(flag, name, desc, req, true, v),
   _value( val ),
   _default( val ),
   _typeDesc( constraint->shortID() ),
   _constraint( constraint )
 {
     parser.add( this );
 }
template<class T > TCLAP::ValueArg< T >::ValueArg (const std::string & flag, const std::string & name, const std::string & desc, bool req, T value, Constraint< T > * constraint, Visitor * v = NULL)
Labeled ValueArg constructor.
You could conceivably call this constructor with a blank flag, but that would make you a bad person. It would also cause an exception to be thrown. If you want an unlabeled argument, use the other constructor.
Parameters
flag - The one character flag that identifies this argument on the command line.
name - A one word name for the argument. Can be used as a long flag on the command line.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
v - An optional visitor. You probably should not use this unless you have a very good reason.
Definition at line 285 of file ValueArg.h.
 : Arg(flag, name, desc, req, true, v),
   _value( val ),
   _default( val ),
   _typeDesc( constraint->shortID() ),
   _constraint( constraint )
 { }
template<class T> TCLAP::ValueArg< T >::ValueArg (const ValueArg< T > & rhs) private
Prevent accidental copying.
Member Function Documentation
template<class T > void TCLAP::ValueArg< T >::_extractValue (const std::string & val) protected
Extracts the value from the string.
Attempts to parse string as type T, if this fails an exception is thrown.
Parameters
val - value to be parsed.
Definition at line 400 of file ValueArg.h.
References TCLAP::ArgException::error(), and TCLAP::ExtractValue().
 {
     try {
   ExtractValue(_value, val, typename ArgTraits<T>::ValueCategory());
     } catch( ArgParseException &e) {
   throw ArgParseException(e.error(), toString());
     }
     if ( _constraint != NULL )
   if ( ! _constraint->check( _value ) )
       throw( CmdLineParseException( "Value '" + val +
             + "' does not meet constraint: "
             + _constraint->description(),
             toString() ) );
 }
template<class T > T & TCLAP::ValueArg< T >::getValue ()
Returns the value of the argument.
Implementation of getValue().
Definition at line 322 of file ValueArg.h.
 { return _value; }
template<class T > std::string TCLAP::ValueArg< T >::longID (const std::string & val = "val") const virtual
Specialization of longID.
Implementation of longID.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 393 of file ValueArg.h.
References TCLAP::Arg::longID().
 {
   static_cast<void>(val); // Ignore input, don't warn
   return Arg::longID( _typeDesc );
 }
template<class T> ValueArg<T>& TCLAP::ValueArg< T >::operator= (const ValueArg< T > & rhs) private
template<class T > bool TCLAP::ValueArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument.
Implementation of processArg().
This re-implements the Arg version of this method to set the _value of the argument appropriately. It knows the difference between labeled and unlabeled.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings. Passed in from main().
Implements TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 328 of file ValueArg.h.
References TCLAP::Arg::delimiter(), and TCLAP::Arg::ignoreRest().
 {
     if ( _ignoreable && Arg::ignoreRest() )
     return false;
     if ( _hasBlanks( args[*i] ) )
     return false;
     std::string flag = args[*i];
     std::string value = "";
     trimFlag( flag, value );
     if ( argMatches( flag ) )
     {
         if ( _alreadySet )
     {
       if ( _xorSet )
         throw( CmdLineParseException(
                "Mutually exclusive argument already set!",
                                      toString()) );
       else
         throw( CmdLineParseException("Argument already set!",
                                      toString()) );
     }
         if ( Arg::delimiter() != ' ' && value == "" )
       throw( ArgParseException(
               "Couldn't find delimiter for this argument!",
                              toString() ) );
         if ( value == "" )
         {
             (*i)++;
             if ( static_cast<unsigned int>(*i) < args.size() )
         _extractValue( args[*i] );
             else
         throw( ArgParseException("Missing a value for this argument!",
                                                     toString() ) );
         }
         else
       _extractValue( value );
         _alreadySet = true;
         _checkWithVisitor();
         return true;
     }
     else
     return false;
 }
template<class T > void TCLAP::ValueArg< T >::reset () virtual
Clears the Arg object and allows it to be reused by new command lines.
Reimplemented from TCLAP::Arg.
Definition at line 417 of file ValueArg.h.
References TCLAP::Arg::reset().
 {
   Arg::reset();
   _value = _default;
 }
template<class T > std::string TCLAP::ValueArg< T >::shortID (const std::string & val = "val") const virtual
Specialization of shortID.
Implementation of shortID.
Parameters
val - value to be used.
Reimplemented from TCLAP::Arg.
Reimplemented in TCLAP::UnlabeledValueArg< T >.
Definition at line 383 of file ValueArg.h.
References TCLAP::Arg::shortID().
 {
   static_cast<void>(val); // Ignore input, don't warn
   return Arg::shortID( _typeDesc );
 }
Member Data Documentation
template<class T> Constraint<T>* TCLAP::ValueArg< T >::_constraint protected
A Constraint this Arg must conform to.
Definition at line 72 of file ValueArg.h.
template<class T> T TCLAP::ValueArg< T >::_default protected
Used to support the reset() method so that ValueArg can be reset to their constructed value.
Definition at line 58 of file ValueArg.h.
template<class T> std::string TCLAP::ValueArg< T >::_typeDesc protected
A human readable description of the type to be parsed.
This is a hack, plain and simple. Ideally we would use RTTI to return the name of type T, but until there is some sort of consistent support for human readable names, we are left to our own devices.
Definition at line 67 of file ValueArg.h.
template<class T> T TCLAP::ValueArg< T >::_value protected
The value parsed from the command line.
Can be of any type, as long as the >> operator for the type is defined.
Definition at line 52 of file ValueArg.h.
The documentation for this class was generated from the following file:
ValueArg.h