DQMCore: dqm4hep::core::TiXmlString Class Reference
dqm4hep::core::TiXmlString Class Reference
#include <tinystr.h>
Classes
struct Rep
Public Types
typedef size_t size_type
Public Member Functions
TiXmlString ()
TiXmlString (const TiXmlString &copy)
TIXML_EXPLICIT TiXmlString (const char *copy)
TIXML_EXPLICIT TiXmlString (const char *str, size_type len)
~TiXmlString ()
TiXmlString & operator= (const char *copy)
TiXmlString & operator= (const TiXmlString &copy)
TiXmlString & operator+= (const char *suffix)
TiXmlString & operator+= (char single)
TiXmlString & operator+= (const TiXmlString &suffix)
const char * c_str () const
const char * data () const
size_type length () const
size_type size () const
bool empty () const
size_type capacity () const
const char & at (size_type index) const
char & operator[] (size_type index) const
size_type find (char lookup) const
size_type find (char tofind, size_type offset) const
void clear ()
void reserve (size_type cap)
TiXmlString & assign (const char *str, size_type len)
TiXmlString & append (const char *str, size_type len)
void swap (TiXmlString &other)
Static Public Attributes
static const size_type npos = static_cast< TiXmlString::size_type >(-1)
Private Member Functions
void init (size_type sz)
void set_size (size_type sz)
char * start () const
char * finish () const
void init (size_type sz, size_type cap)
void quit ()
Private Attributes
Rep * rep_
Static Private Attributes
static Rep nullrep_ = { 0, 0, { '\0' } }
Detailed Description
Definition at line 70 of file tinystr.h.
Member Typedef Documentation
typedef size_t dqm4hep::core::TiXmlString::size_type
Definition at line 74 of file tinystr.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlString::TiXmlString () inline
Definition at line 81 of file tinystr.h.
                      : rep_(&nullrep_)
       {
       }
dqm4hep::core::TiXmlString::TiXmlString (const TiXmlString & copy) inline
Definition at line 86 of file tinystr.h.
References data(), init(), length(), and start().
                                               : rep_(0)
       {
         init(copy.length());
         memcpy(start(), copy.data(), length());
       }
TIXML_EXPLICIT dqm4hep::core::TiXmlString::TiXmlString (const char * copy) inline
Definition at line 93 of file tinystr.h.
References init(), length(), and start().
                                                       : rep_(0)
       {
         init( static_cast<size_type>( strlen(copy) ));
         memcpy(start(), copy, length());
       }
TIXML_EXPLICIT dqm4hep::core::TiXmlString::TiXmlString (const char * str, size_type len) inline
Definition at line 100 of file tinystr.h.
References init(), and start().
                                                                     : rep_(0)
       {
         init(len);
         memcpy(start(), str, len);
       }
dqm4hep::core::TiXmlString::~TiXmlString () inline
Definition at line 107 of file tinystr.h.
References quit().
       {
         quit();
       }
Member Function Documentation
TiXmlString & dqm4hep::core::TiXmlString::append (const char * str, size_type len)
Definition at line 77 of file tinystr.cc.
References capacity(), finish(), length(), reserve(), and set_size().
Referenced by dqm4hep::core::operator+(), and operator+=().
     {
       size_type newsize = length() + len;
       if (newsize > capacity())
       {
         reserve (newsize + capacity());
       }
       memmove(finish(), str, len);
       set_size(newsize);
       return *this;
     }
TiXmlString & dqm4hep::core::TiXmlString::assign (const char * str, size_type len)
Definition at line 58 of file tinystr.cc.
References capacity(), init(), set_size(), start(), and swap().
Referenced by operator=().
     {
       size_type cap = capacity();
       if (len > cap || cap > 3*(len + 8))
       {
         TiXmlString tmp;
         tmp.init(len);
         memcpy(tmp.start(), str, len);
         swap(tmp);
       }
       else
       {
         memmove(start(), str, len);
         set_size(len);
       }
       return *this;
     }
const char& dqm4hep::core::TiXmlString::at (size_type index) const inline
Definition at line 164 of file tinystr.h.
References length(), rep_, and dqm4hep::core::TiXmlString::Rep::str.
       {
         assert( index < length() );
         return rep_->str[ index ];
       }
const char* dqm4hep::core::TiXmlString::c_str () const inline
Definition at line 145 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::str.
Referenced by find(), dqm4hep::core::operator<(), and dqm4hep::core::operator==().
 { return rep_->str; }
size_type dqm4hep::core::TiXmlString::capacity () const inline
Definition at line 160 of file tinystr.h.
References dqm4hep::core::TiXmlString::Rep::capacity, and rep_.
Referenced by append(), assign(), and reserve().
 { return rep_->capacity; }
void dqm4hep::core::TiXmlString::clear () inline
Definition at line 195 of file tinystr.h.
References init(), and quit().
       {
         //Lee:
         //The original was just too strange, though correct:
         //  TiXmlString().swap(*this);
         //Instead use the quit & re-init:
         quit();
         init(0,0);
       }
const char* dqm4hep::core::TiXmlString::data () const inline
Definition at line 148 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::str.
Referenced by operator+=(), reserve(), and TiXmlString().
 { return rep_->str; }
bool dqm4hep::core::TiXmlString::empty () const inline
Definition at line 157 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::size.
 { return rep_->size == 0; }
size_type dqm4hep::core::TiXmlString::find (char lookup) const inline
Definition at line 178 of file tinystr.h.
       {
         return find(lookup, 0);
       }
size_type dqm4hep::core::TiXmlString::find (char tofind, size_type offset) const inline
Definition at line 184 of file tinystr.h.
References c_str(), length(), and npos.
       {
         if (offset >= length()) return npos;
         for (const char* p = c_str() + offset; *p != '\0'; ++p)
         {
           if (*p == tofind) return static_cast< size_type >( p - c_str() );
         }
         return npos;
       }
char* dqm4hep::core::TiXmlString::finish () const inline private
Definition at line 226 of file tinystr.h.
References rep_, dqm4hep::core::TiXmlString::Rep::size, and dqm4hep::core::TiXmlString::Rep::str.
Referenced by append().
 { return rep_->str + rep_->size; }
void dqm4hep::core::TiXmlString::init (size_type sz) inline private
Definition at line 223 of file tinystr.h.
References init().
Referenced by assign(), clear(), init(), reserve(), and TiXmlString().
 { init(sz, sz); }
void dqm4hep::core::TiXmlString::init (size_type sz, size_type cap) inline private
Definition at line 234 of file tinystr.h.
References dqm4hep::core::TiXmlString::Rep::capacity, nullrep_, rep_, dqm4hep::core::TiXmlString::Rep::size, and dqm4hep::core::TiXmlString::Rep::str.
       {
         if (cap)
         {
           // Lee: the original form:
           //  rep_ = static_cast<Rep*>(operator new(sizeof(Rep) + cap));
           // doesn't work in some cases of new being overloaded. Switching
           // to the normal allocation, although use an 'int' for systems
           // that are overly picky about structure alignment.
           const size_type bytesNeeded = sizeof(Rep) + cap;
           const size_type intsNeeded = ( bytesNeeded + sizeof(int) - 1 ) / sizeof( int );
           rep_ = reinterpret_cast<Rep*>( new int[ intsNeeded ] );
           rep_->str[ rep_->size = sz ] = '\0';
           rep_->capacity = cap;
         }
         else
         {
           rep_ = &nullrep_;
         }
       }
size_type dqm4hep::core::TiXmlString::length () const inline
Definition at line 151 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::size.
Referenced by append(), at(), find(), dqm4hep::core::operator+(), operator+=(), operator=(), dqm4hep::core::operator==(), operator[](), reserve(), and TiXmlString().
 { return rep_->size; }
TiXmlString& dqm4hep::core::TiXmlString::operator+= (const char * suffix) inline
Definition at line 126 of file tinystr.h.
References append().
       {
         return append(suffix, static_cast<size_type>( strlen(suffix) ));
       }
TiXmlString& dqm4hep::core::TiXmlString::operator+= (char single) inline
Definition at line 132 of file tinystr.h.
References append().
       {
         return append(&single, 1);
       }
TiXmlString& dqm4hep::core::TiXmlString::operator+= (const TiXmlString & suffix) inline
Definition at line 138 of file tinystr.h.
References append(), data(), and length().
       {
         return append(suffix.data(), suffix.length());
       }
TiXmlString& dqm4hep::core::TiXmlString::operator= (const char * copy) inline
Definition at line 113 of file tinystr.h.
References assign().
       {
         return assign( copy, (size_type)strlen(copy));
       }
TiXmlString& dqm4hep::core::TiXmlString::operator= (const TiXmlString & copy) inline
Definition at line 119 of file tinystr.h.
References assign(), length(), and start().
       {
         return assign(copy.start(), copy.length());
       }
char& dqm4hep::core::TiXmlString::operator[] (size_type index) const inline
Definition at line 171 of file tinystr.h.
References length(), rep_, and dqm4hep::core::TiXmlString::Rep::str.
       {
         assert( index < length() );
         return rep_->str[ index ];
       }
void dqm4hep::core::TiXmlString::quit () inline private
Definition at line 256 of file tinystr.h.
References nullrep_, and rep_.
Referenced by clear(), and ~TiXmlString().
       {
         if (rep_ != &nullrep_)
         {
           // The rep_ is really an array of ints. (see the allocator, above).
           // Cast it back before delete, so the compiler won't incorrectly call destructors.
           delete [] ( reinterpret_cast<int*>( rep_ ) );
         }
       }
void dqm4hep::core::TiXmlString::reserve (size_type cap)
Definition at line 46 of file tinystr.cc.
References capacity(), data(), init(), length(), start(), and swap().
Referenced by append(), and dqm4hep::core::operator+().
     {
       if (cap > capacity())
       {
         TiXmlString tmp;
         tmp.init(length(), cap);
         memcpy(tmp.start(), data(), length());
         swap(tmp);
       }
     }
void dqm4hep::core::TiXmlString::set_size (size_type sz) inline private
Definition at line 224 of file tinystr.h.
References rep_, dqm4hep::core::TiXmlString::Rep::size, and dqm4hep::core::TiXmlString::Rep::str.
Referenced by append(), and assign().
 { rep_->str[ rep_->size = sz ] = '\0'; }
size_type dqm4hep::core::TiXmlString::size () const inline
Definition at line 154 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::size.
 { return rep_->size; }
char* dqm4hep::core::TiXmlString::start () const inline private
Definition at line 225 of file tinystr.h.
References rep_, and dqm4hep::core::TiXmlString::Rep::str.
Referenced by assign(), operator=(), reserve(), and TiXmlString().
 { return rep_->str; }
void dqm4hep::core::TiXmlString::swap (TiXmlString & other) inline
Definition at line 214 of file tinystr.h.
References rep_.
Referenced by assign(), and reserve().
       {
         Rep* r = rep_;
         rep_ = other.rep_;
         other.rep_ = r;
       }
Member Data Documentation
const TiXmlString::size_type dqm4hep::core::TiXmlString::npos = static_cast< TiXmlString::size_type >(-1) static
Definition at line 77 of file tinystr.h.
Referenced by find().
TiXmlString::Rep dqm4hep::core::TiXmlString::nullrep_ = { 0, 0, { '\0' } } static private
Definition at line 267 of file tinystr.h.
Referenced by init(), and quit().
Rep* dqm4hep::core::TiXmlString::rep_ private
Definition at line 266 of file tinystr.h.
Referenced by at(), c_str(), capacity(), data(), empty(), finish(), init(), length(), operator[](), quit(), set_size(), size(), start(), and swap().
The documentation for this class was generated from the following files:
tinystr.h
tinystr.cc