DQMCore: dqm4hep::core::TiXmlPrinter Class Reference
dqm4hep::core::TiXmlPrinter Class Reference
Print to memory functionality.
#include <tinyxml.h>
Public Member Functions
TiXmlPrinter ()
virtual bool VisitEnter (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitExit (const TiXmlDocument &doc)
Visit a document.
virtual bool VisitEnter (const TiXmlElement &element, const TiXmlAttribute *firstAttribute)
Visit an element.
virtual bool VisitExit (const TiXmlElement &element)
Visit an element.
virtual bool Visit (const TiXmlDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const TiXmlText &text)
Visit a text node.
virtual bool Visit (const TiXmlComment &comment)
Visit a comment node.
virtual bool Visit (const TiXmlUnknown &unknown)
Visit an unknow node.
void SetIndent (const char *_indent)
Set the indent characters for printing.
const char * Indent ()
Query the indention string.
void SetLineBreak (const char *_lineBreak)
Set the line breaking string.
const char * LineBreak ()
Query the current line breaking string.
void SetStreamPrinting ()
Switch over to "stream printing" which is the most dense formatting without linebreaks.
const char * CStr ()
Return the result.
size_t Size ()
Return the length of the result string.
const std::string & Str ()
Return the result.
Public Member Functions inherited from dqm4hep::core::TiXmlVisitor
virtual ~TiXmlVisitor ()
Private Member Functions
void DoIndent ()
void DoLineBreak ()
Private Attributes
int depth
bool simpleTextPrint
TIXML_STRING buffer
TIXML_STRING indent
TIXML_STRING lineBreak
Detailed Description
Print to memory functionality.
The TiXmlPrinter is useful when you need to:
Print to memory (especially in non-STL mode)
Control formatting (line endings, etc.)
When constructed, the TiXmlPrinter is in its default "pretty printing" mode. Before calling Accept() you can call methods to control the printing of the XML document. After TiXmlNode::Accept() is called, the printed document can be accessed via the CStr(), Str(), and Size() methods.
TiXmlPrinter uses the Visitor API.
TiXmlPrinter printer;
printer.SetIndent("\t");
doc.Accept(&printer);
fprintf(stdout, "%s", printer.CStr());
Definition at line 1737 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlPrinter::TiXmlPrinter () inline
Definition at line 1740 of file tinyxml.h.
                      : depth( 0 ), simpleTextPrint( false ),
       buffer(), indent( "    " ), lineBreak( "\n" ) {}
Member Function Documentation
const char* dqm4hep::core::TiXmlPrinter::CStr () inline
Return the result.
Definition at line 1775 of file tinyxml.h.
References buffer.
 { return buffer.c_str(); }
void dqm4hep::core::TiXmlPrinter::DoIndent () inline private
Definition at line 1785 of file tinyxml.h.
References buffer, depth, and indent.
Referenced by Visit(), VisitEnter(), and VisitExit().
                       {
         for( int i=0; i<depth; ++i )
           buffer += indent;
       }
void dqm4hep::core::TiXmlPrinter::DoLineBreak () inline private
Definition at line 1789 of file tinyxml.h.
References buffer, and lineBreak.
Referenced by Visit(), VisitEnter(), and VisitExit().
{
         buffer += lineBreak;
       }
const char* dqm4hep::core::TiXmlPrinter::Indent () inline
Query the indention string.
Definition at line 1759 of file tinyxml.h.
References indent.
 { return indent.c_str(); }
const char* dqm4hep::core::TiXmlPrinter::LineBreak () inline
Query the current line breaking string.
Definition at line 1766 of file tinyxml.h.
References lineBreak.
 { return lineBreak.c_str(); }
void dqm4hep::core::TiXmlPrinter::SetIndent (const char * _indent) inline
Set the indent characters for printing.
By default 4 spaces but tab () is also useful, or null/empty string for no indentation.
Definition at line 1757 of file tinyxml.h.
References indent.
 { indent = _indent ? _indent : "" ; }
void dqm4hep::core::TiXmlPrinter::SetLineBreak (const char * _lineBreak) inline
Set the line breaking string.
By default set to newline (
). Some operating systems prefer other characters, or can be set to the null/empty string for no indenation.
Definition at line 1764 of file tinyxml.h.
References lineBreak.
 { lineBreak = _lineBreak ? _lineBreak : ""; }
void dqm4hep::core::TiXmlPrinter::SetStreamPrinting () inline
Switch over to "stream printing" which is the most dense formatting without linebreaks.
Common when the XML is needed for network transmission.
Definition at line 1771 of file tinyxml.h.
References indent, and lineBreak.
                                           { indent = "";
       lineBreak = "";
       }
size_t dqm4hep::core::TiXmlPrinter::Size () inline
Return the length of the result string.
Definition at line 1777 of file tinyxml.h.
References buffer.
 { return buffer.size(); }
const std::string& dqm4hep::core::TiXmlPrinter::Str () inline
Return the result.
Definition at line 1781 of file tinyxml.h.
 { return buffer; }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlDeclaration &) virtual
Visit a declaration.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1814 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlDeclaration::Print().
     {
       DoIndent();
       declaration.Print( 0, 0, &buffer );
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlText &) virtual
Visit a text node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1786 of file tinyxml.cc.
References buffer, dqm4hep::core::TiXmlText::CDATA(), DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlBase::EncodeString(), simpleTextPrint, TIXML_STRING, dqm4hep::core::TiXmlNode::Value(), and dqm4hep::core::TiXmlNode::ValueTStr().
     {
       if ( text.CDATA() )
       {
         DoIndent();
         buffer += "<![CDATA[";
         buffer += text.Value();
         buffer += "]]>";
         DoLineBreak();
       }
       else if ( simpleTextPrint )
       {
         TIXML_STRING str;
         TiXmlBase::EncodeString( text.ValueTStr(), &str );
         buffer += str;
       }
       else
       {
         DoIndent();
         TIXML_STRING str;
         TiXmlBase::EncodeString( text.ValueTStr(), &str );
         buffer += str;
         DoLineBreak();
       }
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlComment &) virtual
Visit a comment node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1823 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlNode::Value().
     {
       DoIndent();
       buffer += "<!--";
       buffer += comment.Value();
       buffer += "-->";
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::Visit (const TiXmlUnknown &) virtual
Visit an unknow node.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1834 of file tinyxml.cc.
References buffer, DoIndent(), DoLineBreak(), and dqm4hep::core::TiXmlNode::Value().
     {
       DoIndent();
       buffer += "<";
       buffer += unknown.Value();
       buffer += ">";
       DoLineBreak();
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitEnter (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1713 of file tinyxml.cc.
     {
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitEnter (const TiXmlElement & , const TiXmlAttribute *) virtual
Visit an element.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1723 of file tinyxml.cc.
References buffer, dqm4hep::core::TiXmlText::CDATA(), depth, DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlNode::FirstChild(), dqm4hep::core::TiXmlNode::LastChild(), dqm4hep::core::TiXmlAttribute::Next(), simpleTextPrint, dqm4hep::core::TiXmlNode::ToText(), and dqm4hep::core::TiXmlNode::Value().
     {
       DoIndent();
       buffer += "<";
       buffer += element.Value();
       for( const TiXmlAttribute* attrib = firstAttribute; attrib; attrib = attrib->Next() )
       {
         buffer += " ";
         attrib->Print( 0, 0, &buffer );
       }
       if ( !element.FirstChild() )
       {
         buffer += " />";
         DoLineBreak();
       }
       else
       {
         buffer += ">";
         if (    element.FirstChild()->ToText()
             && element.LastChild() == element.FirstChild()
             && element.FirstChild()->ToText()->CDATA() == false )
         {
           simpleTextPrint = true;
           // no DoLineBreak()!
         }
         else
         {
           DoLineBreak();
         }
       }
       ++depth;
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitExit (const TiXmlDocument &) virtual
Visit a document.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1718 of file tinyxml.cc.
     {
       return true;
     }
bool dqm4hep::core::TiXmlPrinter::VisitExit (const TiXmlElement &) virtual
Visit an element.
Reimplemented from dqm4hep::core::TiXmlVisitor.
Definition at line 1760 of file tinyxml.cc.
References buffer, depth, DoIndent(), DoLineBreak(), dqm4hep::core::TiXmlNode::FirstChild(), simpleTextPrint, and dqm4hep::core::TiXmlNode::Value().
     {
       --depth;
       if ( !element.FirstChild() )
       {
         // nothing.
       }
       else
       {
         if ( simpleTextPrint )
         {
           simpleTextPrint = false;
         }
         else
         {
           DoIndent();
         }
         buffer += "</";
         buffer += element.Value();
         buffer += ">";
         DoLineBreak();
       }
       return true;
     }
Member Data Documentation
TIXML_STRING dqm4hep::core::TiXmlPrinter::buffer private
Definition at line 1795 of file tinyxml.h.
Referenced by CStr(), DoIndent(), DoLineBreak(), Size(), Visit(), VisitEnter(), and VisitExit().
int dqm4hep::core::TiXmlPrinter::depth private
Definition at line 1793 of file tinyxml.h.
Referenced by DoIndent(), VisitEnter(), and VisitExit().
TIXML_STRING dqm4hep::core::TiXmlPrinter::indent private
Definition at line 1796 of file tinyxml.h.
Referenced by DoIndent(), Indent(), SetIndent(), and SetStreamPrinting().
TIXML_STRING dqm4hep::core::TiXmlPrinter::lineBreak private
Definition at line 1797 of file tinyxml.h.
Referenced by DoLineBreak(), LineBreak(), SetLineBreak(), and SetStreamPrinting().
bool dqm4hep::core::TiXmlPrinter::simpleTextPrint private
Definition at line 1794 of file tinyxml.h.
Referenced by Visit(), VisitEnter(), and VisitExit().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc