DQMCore: dqm4hep::core::MeanWithinExpectedTest Class Reference
dqm4hep::core::MeanWithinExpectedTest Class Reference
MeanWithinExpectedTest class.
Classes
class Factory
Public Member Functions
MeanWithinExpectedTest (const std::string &name)
~MeanWithinExpectedTest ()
StatusCode readSettings (const dqm4hep::core::TiXmlHandle xmlHandle)
Read the settings from the xml handle.
StatusCode userRun (MonitorElement *pMonitorElement, QualityTestReport &report)
Runs a quality test on the given monitor element.
bool canRun (MonitorElement *pMonitorElement) const
Whether the quality test can be run on the monitor element.
Public Member Functions inherited from dqm4hep::core::QualityTest
QualityTest (const std::string &type, const std::string &name)
Constructor.
virtual ~QualityTest ()
Destructor.
const std::string & type () const
Get the quality test type.
const std::string & name () const
Get the quality test name (unique identifier)
const std::string & description () const
Get the quality test description.
void run (MonitorElement *pMonitorElement, QualityTestReport &report)
Perform the quality test result and fill the quality test report.
virtual StatusCode init ()
Initialize the quality test.
Protected Attributes
float m_expectedMean
float m_meanDeviationLower
float m_meanDeviationUpper
Protected Attributes inherited from dqm4hep::core::QualityTest
std::string m_description
Quality test description.
Additional Inherited Members
Protected Member Functions inherited from dqm4hep::core::QualityTest
void fillBasicInfo (MonitorElement *pMonitorElement, QualityTestReport &report) const
Fill basic info in the qtest report.
Detailed Description
MeanWithinExpectedTest class.
Definition at line 47 of file MeanWithinExpectedTest.cc.
Constructor & Destructor Documentation
dqm4hep::core::MeanWithinExpectedTest::MeanWithinExpectedTest (const std::string & name)
Definition at line 81 of file MeanWithinExpectedTest.cc.
References dqm4hep::core::QualityTest::m_description.
Referenced by dqm4hep::core::MeanWithinExpectedTest::Factory::createQualityTest().
                                                                         :
       QualityTest("MeanWithinExpected", name),
       m_expectedMean(0.f),
       m_meanDeviationLower(0.f),
       m_meanDeviationUpper(0.f)
     {
       m_description = "Test if the mean of the histogram if contained in the expected user range. The quality is defined as the probability to be close to mean : 1 at the mean, 0 infinitely far from the mean (using TMath::Prob(chi2,1))";
     }
dqm4hep::core::MeanWithinExpectedTest::~MeanWithinExpectedTest () inline
Definition at line 57 of file MeanWithinExpectedTest.cc.
 {}
Member Function Documentation
bool dqm4hep::core::MeanWithinExpectedTest::canRun (MonitorElement * pMonitorElement) const virtual
Whether the quality test can be run on the monitor element.
Implements dqm4hep::core::QualityTest.
Definition at line 136 of file MeanWithinExpectedTest.cc.
References dqm4hep::core::MonitorElement::objectTo().
     {
       if(nullptr == pMonitorElement)
         return false;
       TH1 *pHistogram = pMonitorElement->objectTo<TH1>();
       if(nullptr == pHistogram)
         return false;
       return true;
     }
StatusCode dqm4hep::core::MeanWithinExpectedTest::readSettings (const dqm4hep::core::TiXmlHandle xmlHandle) virtual
Read the settings from the xml handle.
Implements dqm4hep::core::QualityTest.
Definition at line 92 of file MeanWithinExpectedTest.cc.
References m_expectedMean, m_meanDeviationLower, m_meanDeviationUpper, dqm4hep::core::XmlHelper::readValue(), and RETURN_RESULT_IF.
     {
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readValue(xmlHandle,
           "ExpectedMean", m_expectedMean));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readValue(xmlHandle,
           "MeanDeviationLower", m_meanDeviationLower));
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, XmlHelper::readValue(xmlHandle,
           "MeanDeviationUpper", m_meanDeviationUpper));
       if(m_meanDeviationLower > m_expectedMean || m_meanDeviationUpper < m_expectedMean)
         return STATUS_CODE_INVALID_PARAMETER;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::MeanWithinExpectedTest::userRun (MonitorElement * pMonitorElement, QualityTestReport & report) virtual
Runs a quality test on the given monitor element.
Implements dqm4hep::core::QualityTest.
Definition at line 111 of file MeanWithinExpectedTest.cc.
References m_expectedMean, dqm4hep::core::QualityTestReport::m_isSuccessful, m_meanDeviationLower, m_meanDeviationUpper, dqm4hep::core::QualityTestReport::m_message, dqm4hep::core::QualityTestReport::m_quality, dqm4hep::core::MonitorElement::objectTo(), and dqm4hep::core::typeToString().
     {
       TH1 *pHistogram = pMonitorElement->objectTo<TH1>();
       const float mean(pHistogram->GetMean());
       const float range(fabs(m_meanDeviationUpper - m_meanDeviationLower));
       if(m_meanDeviationLower < mean && mean < m_meanDeviationUpper)
       {
         report.m_message = "Within expected range: expected " + typeToString(m_expectedMean) + ", got " + typeToString(mean);
       }
       else
       {
         report.m_message = "Out of expected range: expected " + typeToString(m_expectedMean) + ", got " + typeToString(mean);
       }
       const float chi = (mean - m_expectedMean)/range;
       const float probability = TMath::Prob(chi*chi, 1);
       report.m_quality = probability;
       report.m_isSuccessful = true;
       return STATUS_CODE_SUCCESS;
     }
Member Data Documentation
float dqm4hep::core::MeanWithinExpectedTest::m_expectedMean protected
Definition at line 63 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::MeanWithinExpectedTest::m_meanDeviationLower protected
Definition at line 64 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
float dqm4hep::core::MeanWithinExpectedTest::m_meanDeviationUpper protected
Definition at line 65 of file MeanWithinExpectedTest.cc.
Referenced by readSettings(), and userRun().
The documentation for this class was generated from the following file:
MeanWithinExpectedTest.cc