DQMCore: dqm4hep::core::TiXmlText Class Reference
dqm4hep::core::TiXmlText Class Reference
XML text.
#include <tinyxml.h>
Public Member Functions
TiXmlText (const char *initValue)
Constructor for text element.
virtual ~TiXmlText ()
TiXmlText (const std::string &initValue)
Constructor.
TiXmlText (const TiXmlText &copy)
void operator= (const TiXmlText &base)
virtual void Print (FILE *cfile, int depth) const
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
bool CDATA () const
Queries whether this represents text using a CDATA section.
void SetCDATA (bool _cdata)
Turns on or off a CDATA representation of text.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null not of the requested type.
virtual bool Accept (TiXmlVisitor *content) const
Walk the XML tree visiting this node and all of its children.
Public Member Functions inherited from dqm4hep::core::TiXmlNode
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const std::string & ValueStr () const
Return Value() as a std::string.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'.
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
Protected Member Functions
virtual TiXmlNode * Clone () const
[internal use] Creates a new Element and returns it.
void CopyTo (TiXmlText *target) const
bool Blank () const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)
Protected Member Functions inherited from dqm4hep::core::TiXmlNode
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Private Attributes
bool cdata
Friends
class TiXmlElement
Additional Inherited Members
Public Types inherited from dqm4hep::core::TiXmlNode
enum NodeType {
TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN,
TINYXML_TEXT, TINYXML_DECLARATION, TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes inherited from dqm4hep::core::TiXmlNode
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
XML text.
A text node can have 2 ways to output the next. "normal" output and CDATA. It will default to the mode it was parsed from the XML file and you generally want to leave it alone, but you can change the output mode with SetCDATA() and query it with CDATA().
Definition at line 1212 of file tinyxml.h.
Constructor & Destructor Documentation
dqm4hep::core::TiXmlText::TiXmlText (const char * initValue) inline
Constructor for text element.
By default, it is treated as normal, encoded text. If you want it be output as a CDATA text element, set the parameter _cdata to 'true'
Definition at line 1220 of file tinyxml.h.
References cdata, and dqm4hep::core::TiXmlNode::SetValue().
Referenced by Clone().
                                           : TiXmlNode (TiXmlNode::TINYXML_TEXT)
     {
         SetValue( initValue );
         cdata = false;
     }
virtual dqm4hep::core::TiXmlText::~TiXmlText () inline virtual
Definition at line 1225 of file tinyxml.h.
 {}
dqm4hep::core::TiXmlText::TiXmlText (const std::string & initValue) inline
Constructor.
Definition at line 1229 of file tinyxml.h.
                                               : TiXmlNode (TiXmlNode::TINYXML_TEXT)
       {
         SetValue( initValue );
         cdata = false;
       }
dqm4hep::core::TiXmlText::TiXmlText (const TiXmlText & copy) inline
Definition at line 1236 of file tinyxml.h.
References CopyTo().
 : TiXmlNode( TiXmlNode::TINYXML_TEXT )  { copy.CopyTo( this ); }
Member Function Documentation
bool dqm4hep::core::TiXmlText::Accept (TiXmlVisitor * content) const virtual
Walk the XML tree visiting this node and all of its children.
Implements dqm4hep::core::TiXmlNode.
Definition at line 1318 of file tinyxml.cc.
References dqm4hep::core::TiXmlVisitor::Visit().
     {
       return visitor->Visit( *this );
     }
bool dqm4hep::core::TiXmlText::Blank () const protected
Definition at line 1632 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlBase::IsWhiteSpace(), and dqm4hep::core::TiXmlNode::value.
Referenced by dqm4hep::core::TiXmlElement::ReadValue().
     {
       for ( unsigned i=0; i<value.length(); i++ )
         if ( !IsWhiteSpace( value[i] ) )
           return false;
       return true;
     }
bool dqm4hep::core::TiXmlText::CDATA () const inline
Queries whether this represents text using a CDATA section.
Definition at line 1243 of file tinyxml.h.
References cdata.
Referenced by dqm4hep::core::TiXmlPrinter::Visit(), and dqm4hep::core::TiXmlPrinter::VisitEnter().
 { return cdata; }
TiXmlNode * dqm4hep::core::TiXmlText::Clone () const protected virtual
[internal use] Creates a new Element and returns it.
Implements dqm4hep::core::TiXmlNode.
Definition at line 1324 of file tinyxml.cc.
References CopyTo(), and TiXmlText().
     {
       TiXmlText* clone = 0;
       clone = new TiXmlText( "" );
       if ( !clone )
         return 0;
       CopyTo( clone );
       return clone;
     }
void dqm4hep::core::TiXmlText::CopyTo (TiXmlText * target) const protected
Definition at line 1311 of file tinyxml.cc.
References cdata, and dqm4hep::core::TiXmlNode::CopyTo().
Referenced by Clone(), operator=(), and TiXmlText().
     {
       TiXmlNode::CopyTo( target );
       target->cdata = cdata;
     }
void dqm4hep::core::TiXmlText::operator= (const TiXmlText & base) inline
Definition at line 1237 of file tinyxml.h.
References CopyTo().
 { base.CopyTo( this ); }
const char * dqm4hep::core::TiXmlText::Parse (const char * p, TiXmlParsingData * data, TiXmlEncoding encoding) virtual
Implements dqm4hep::core::TiXmlBase.
Definition at line 1499 of file tinyxmlparser.cc.
References cdata, dqm4hep::core::TiXmlParsingData::Cursor(), dqm4hep::core::TiXmlNode::GetDocument(), dqm4hep::core::TiXmlBase::location, dqm4hep::core::TiXmlBase::ReadText(), dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TiXmlParsingData::Stamp(), dqm4hep::core::TiXmlBase::StringEqual(), dqm4hep::core::TiXmlBase::TIXML_ERROR_PARSING_CDATA, TIXML_STRING, and dqm4hep::core::TiXmlNode::value.
Referenced by dqm4hep::core::TiXmlElement::ReadValue().
     {
       value = "";
       TiXmlDocument* document = GetDocument();
       if ( data )
       {
         data->Stamp( p, encoding );
         location = data->Cursor();
       }
       const char* const startTag = "<![CDATA[";
       const char* const endTag   = "]]>";
       if ( cdata || StringEqual( p, startTag, false, encoding ) )
       {
         cdata = true;
         if ( !StringEqual( p, startTag, false, encoding ) )
         {
           document->SetError( TIXML_ERROR_PARSING_CDATA, p, data, encoding );
           return 0;
         }
         p += strlen( startTag );
         // Keep all the white space, ignore the encoding, etc.
         while (    p && *p
             && !StringEqual( p, endTag, false, encoding )
         )
         {
           value += *p;
           ++p;
         }
         TIXML_STRING dummy;
         p = ReadText( p, &dummy, false, endTag, false, encoding );
         return p;
       }
       else
       {
         bool ignoreWhite = true;
         const char* end = "<";
         p = ReadText( p, &value, ignoreWhite, end, false, encoding );
         if ( p )
           return p-1; // don't truncate the '<'
         return 0;
       }
     }
void dqm4hep::core::TiXmlText::Print (FILE * cfile, int depth) const virtual
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
This is a formatted print, and will insert tabs and newlines.
(For an unformatted stream, use the << operator.)
Implements dqm4hep::core::TiXmlBase.
Definition at line 1290 of file tinyxml.cc.
References cdata, dqm4hep::core::TiXmlBase::EncodeString(), TIXML_STRING, and dqm4hep::core::TiXmlNode::value.
     {
       assert( cfile );
       if ( cdata )
       {
         int i;
         fprintf( cfile, "\n" );
         for ( i=0; i<depth; i++ ) {
           fprintf( cfile, "    " );
         }
         fprintf( cfile, "<![CDATA[%s]]>\n", value.c_str() );  // unformatted output
       }
       else
       {
         TIXML_STRING buffer;
         EncodeString( value, &buffer );
         fprintf( cfile, "%s", buffer.c_str() );
       }
     }
void dqm4hep::core::TiXmlText::SetCDATA (bool _cdata) inline
Turns on or off a CDATA representation of text.
Definition at line 1245 of file tinyxml.h.
References cdata.
Referenced by dqm4hep::core::TiXmlNode::Identify().
 { cdata = _cdata; }
virtual void dqm4hep::core::TiXmlText::StreamIn (std::istream * in, TIXML_STRING * tag) protected virtual
Implements dqm4hep::core::TiXmlNode.
virtual const TiXmlText* dqm4hep::core::TiXmlText::ToText () const inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1249 of file tinyxml.h.
Referenced by dqm4hep::core::XmlHelper::replaceConstants().
virtual TiXmlText* dqm4hep::core::TiXmlText::ToText () inline virtual
Cast to a more defined type. Will return null not of the requested type.
Reimplemented from dqm4hep::core::TiXmlNode.
Definition at line 1250 of file tinyxml.h.
Friends And Related Function Documentation
friend class TiXmlElement friend
Definition at line 1214 of file tinyxml.h.
Member Data Documentation
bool dqm4hep::core::TiXmlText::cdata private
Definition at line 1268 of file tinyxml.h.
Referenced by CDATA(), CopyTo(), Parse(), Print(), SetCDATA(), and TiXmlText().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc