DQMCore: TCLAP::UnlabeledValueArg< T > Class Template Reference
TCLAP::UnlabeledValueArg< T > Class Template Reference
The basic unlabeled argument that parses a value.
#include <UnlabeledValueArg.h>
Public Member Functions
UnlabeledValueArg (const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, bool ignoreable=false, Visitor *v=NULL)
UnlabeledValueArg constructor.
UnlabeledValueArg (const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
UnlabeledValueArg constructor.
UnlabeledValueArg (const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, bool ignoreable=false, Visitor *v=NULL)
UnlabeledValueArg constructor.
UnlabeledValueArg (const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, CmdLineInterface &parser, bool ignoreable=false, Visitor *v=NULL)
UnlabeledValueArg constructor.
virtual bool processArg (int *i, std::vector< std::string > &args)
Handles the processing of the argument.
virtual std::string shortID (const std::string &val="val") const
Overrides shortID for specific behavior.
virtual std::string longID (const std::string &val="val") const
Overrides longID for specific behavior.
virtual bool operator== (const Arg &a) const
Overrides operator== for specific behavior.
virtual void addToList (std::list< Arg * > &argList) const
Instead of pushing to the front of list, push to the back.
Public Member Functions inherited from TCLAP::ValueArg< T >
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, const std::string &typeDesc, CmdLineInterface &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, CmdLineInterface &parser, Visitor *v=NULL)
Labeled ValueArg constructor.
ValueArg (const std::string &flag, const std::string &name, const std::string &desc, bool req, T value, Constraint< T > *constraint, Visitor *v=NULL)
Labeled ValueArg constructor.
T & getValue ()
Returns the value of the argument.
virtual void reset ()
Clears the Arg object and allows it to be reused by new command lines.
Public Member Functions inherited from TCLAP::Arg
virtual ~Arg ()
Destructor.
const std::string & getFlag () const
Returns the argument flag.
const std::string & getName () const
Returns the argument name.
std::string getDescription () const
Returns the argument description.
virtual bool isRequired () const
Indicates whether the argument is required.
void forceRequired ()
Sets _required to true.
void xorSet ()
Sets the _alreadySet value to true.
bool isValueRequired () const
Indicates whether a value must be specified for argument.
bool isSet () const
Indicates whether the argument has already been set.
bool isIgnoreable () const
Indicates whether the argument can be ignored, if desired.
virtual bool argMatches (const std::string &s) const
A method that tests whether a string matches this argument.
virtual std::string toString () const
Returns a simple string representation of the argument.
virtual void trimFlag (std::string &flag, std::string &value) const
Trims a value off of the flag.
bool _hasBlanks (const std::string &s) const
Checks whether a given string has blank chars, indicating that it is a combined SwitchArg.
void setRequireLabel (const std::string &s)
Sets the requireLabel.
virtual bool allowMore ()
Used for MultiArgs and XorHandler to determine whether args can still be set.
virtual bool acceptsMultipleValues ()
Use by output classes to determine whether an Arg accepts multiple values.
Additional Inherited Members
Static Public Member Functions inherited from TCLAP::Arg
static void beginIgnoring ()
Begin ignoring arguments since the "--" argument was specified.
static bool ignoreRest ()
Whether to ignore the rest.
static char delimiter ()
The delimiter that separates an argument flag/name from the value.
static char blankChar ()
The char used as a place holder when SwitchArgs are combined.
static char flagStartChar ()
static const std::string flagStartString ()
static const std::string nameStartString ()
static const std::string ignoreNameString ()
The name used to identify the ignore rest argument.
static void setDelimiter (char c)
Sets the delimiter for all arguments.
Protected Member Functions inherited from TCLAP::ValueArg< T >
void _extractValue (const std::string &val)
Extracts the value from the string.
Protected Member Functions inherited from TCLAP::Arg
void _checkWithVisitor () const
Performs the special handling described by the Vistitor.
Arg (const std::string &flag, const std::string &name, const std::string &desc, bool req, bool valreq, Visitor *v=NULL)
Primary constructor.
Protected Attributes inherited from TCLAP::ValueArg< T >
T _value
The value parsed from the command line.
T _default
Used to support the reset() method so that ValueArg can be reset to their constructed value.
std::string _typeDesc
A human readable description of the type to be parsed.
Constraint< T > * _constraint
A Constraint this Arg must conform to.
Protected Attributes inherited from TCLAP::Arg
std::string _flag
The single char flag used to identify the argument.
std::string _name
A single work namd indentifying the argument.
std::string _description
Description of the argument.
bool _required
Indicating whether the argument is required.
std::string _requireLabel
Label to be used in usage description.
bool _valueRequired
Indicates whether a value is required for the argument.
bool _alreadySet
Indicates whether the argument has been set.
Visitor * _visitor
A pointer to a vistitor object.
bool _ignoreable
Whether this argument can be ignored, if desired.
bool _xorSet
Indicates that the arg was set as part of an XOR and not on the command line.
bool _acceptsMultipleValues
Detailed Description
template<class T>
class TCLAP::UnlabeledValueArg< T >
The basic unlabeled argument that parses a value.
This is a template class, which means the type T defines the type that a given object will attempt to parse when an UnlabeledValueArg is reached in the list of args that the CmdLine iterates over.
Definition at line 43 of file UnlabeledValueArg.h.
Constructor & Destructor Documentation
template<class T > TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg (const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, bool ignoreable = false, Visitor * v = NULL)
UnlabeledValueArg constructor.
Constructor implemenation.
Parameters
name - A one word name for the argument. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
ignoreable - Allows you to specify that this argument can be ignored if the '–' flag is set. This defaults to false (cannot be ignored) and should generally stay that way unless you have some special need for certain arguments to be ignored.
v - Optional Vistor. You should leave this blank unless you have a very good reason.
Definition at line 213 of file UnlabeledValueArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
 : ValueArg<T>("", name, desc, req, val, typeDesc, v)
 {
   _ignoreable = ignoreable;
   OptionalUnlabeledTracker::check(req, toString());
 }
template<class T > TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg (const std::string & name, const std::string & desc, bool req, T value, const std::string & typeDesc, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
UnlabeledValueArg constructor.
Parameters
name - A one word name for the argument. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
typeDesc - A short, human readable description of the type that this object expects. This is used in the generation of the USAGE statement. The goal is to be helpful to the end user of the program.
parser - A CmdLine parser object to add this Arg to
ignoreable - Allows you to specify that this argument can be ignored if the '–' flag is set. This defaults to false (cannot be ignored) and should generally stay that way unless you have some special need for certain arguments to be ignored.
v - Optional Vistor. You should leave this blank unless you have a very good reason.
Definition at line 229 of file UnlabeledValueArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
 : ValueArg<T>("", name, desc, req, val, typeDesc, v)
 {
   _ignoreable = ignoreable;
   OptionalUnlabeledTracker::check(req, toString());
   parser.add( this );
 }
template<class T > TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg (const std::string & name, const std::string & desc, bool req, T value, Constraint< T > * constraint, bool ignoreable = false, Visitor * v = NULL)
UnlabeledValueArg constructor.
Constructor implemenation.
Parameters
name - A one word name for the argument. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
ignoreable - Allows you to specify that this argument can be ignored if the '–' flag is set. This defaults to false (cannot be ignored) and should generally stay that way unless you have some special need for certain arguments to be ignored.
v - Optional Vistor. You should leave this blank unless you have a very good reason.
Definition at line 248 of file UnlabeledValueArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
 : ValueArg<T>("", name, desc, req, val, constraint, v)
 {
   _ignoreable = ignoreable;
   OptionalUnlabeledTracker::check(req, toString());
 }
template<class T > TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg (const std::string & name, const std::string & desc, bool req, T value, Constraint< T > * constraint, CmdLineInterface & parser, bool ignoreable = false, Visitor * v = NULL)
UnlabeledValueArg constructor.
Parameters
name - A one word name for the argument. Note that this is used for identification, not as a long flag.
desc - A description of what the argument is for or does.
req - Whether the argument is required on the command line.
value - The default value assigned to this argument if it is not present on the command line.
constraint - A pointer to a Constraint object used to constrain this Arg.
parser - A CmdLine parser object to add this Arg to
ignoreable - Allows you to specify that this argument can be ignored if the '–' flag is set. This defaults to false (cannot be ignored) and should generally stay that way unless you have some special need for certain arguments to be ignored.
v - Optional Vistor. You should leave this blank unless you have a very good reason.
Definition at line 262 of file UnlabeledValueArg.h.
References TCLAP::Arg::_ignoreable, TCLAP::CmdLineInterface::add(), TCLAP::OptionalUnlabeledTracker::check(), and TCLAP::Arg::toString().
 : ValueArg<T>("", name, desc, req, val, constraint,  v)
 {
   _ignoreable = ignoreable;
   OptionalUnlabeledTracker::check(req, toString());
   parser.add( this );
 }
Member Function Documentation
template<class T > void TCLAP::UnlabeledValueArg< T >::addToList (std::list< Arg * > & argList) const virtual
Instead of pushing to the front of list, push to the back.
Parameters
argList - The list to add this to.
Reimplemented from TCLAP::Arg.
Definition at line 334 of file UnlabeledValueArg.h.
 {
   argList.push_back( const_cast<Arg*>(static_cast<const Arg* const>(this)) );
 }
template<class T > std::string TCLAP::UnlabeledValueArg< T >::longID (const std::string & val = "val") const virtual
Overrides longID for specific behavior.
Overriding longID for specific output.
Reimplemented from TCLAP::ValueArg< T >.
Definition at line 311 of file UnlabeledValueArg.h.
 {
   static_cast<void>(val); // Ignore input, don't warn
   // Ideally we would like to be able to use RTTI to return the name
   // of the type required for this argument.  However, g++ at least,
   // doesn't appear to return terribly useful "names" of the types.
   return std::string("<") + _typeDesc + ">";
 }
template<class T > bool TCLAP::UnlabeledValueArg< T >::operator== (const Arg & a) const virtual
Overrides operator== for specific behavior.
Overriding operator== for specific behavior.
Reimplemented from TCLAP::Arg.
Definition at line 325 of file UnlabeledValueArg.h.
References TCLAP::Arg::getDescription(), and TCLAP::Arg::getName().
 {
   if ( _name == a.getName() || _description == a.getDescription() )
     return true;
   else
     return false;
 }
template<class T > bool TCLAP::UnlabeledValueArg< T >::processArg (int * i, std::vector< std::string > & args) virtual
Handles the processing of the argument.
Implementation of processArg().
This re-implements the Arg version of this method to set the _value of the argument appropriately. Handling specific to unlabled arguments.
Parameters
i - Pointer the the current argument in the list.
args - Mutable list of strings.
Reimplemented from TCLAP::ValueArg< T >.
Definition at line 281 of file UnlabeledValueArg.h.
 {
   if ( _alreadySet )
     return false;
   if ( _hasBlanks( args[*i] ) )
     return false;
   // never ignore an unlabeled arg
   _extractValue( args[*i] );
   _alreadySet = true;
   return true;
 }
template<class T > std::string TCLAP::UnlabeledValueArg< T >::shortID (const std::string & val = "val") const virtual
Overrides shortID for specific behavior.
Overriding shortID for specific output.
Reimplemented from TCLAP::ValueArg< T >.
Definition at line 301 of file UnlabeledValueArg.h.
 {
   static_cast<void>(val); // Ignore input, don't warn
   return std::string("<") + _typeDesc + ">";
 }
The documentation for this class was generated from the following file:
UnlabeledValueArg.h