DQMCore: dqm4hep::core::Archiver Class Reference
dqm4hep::core::Archiver Class Reference
Archiver class.
#include <Archiver.h>
Public Member Functions
Archiver ()
Constructor.
Archiver (const std::string &archiveFileName, const std::string &openingMode="RECREATE", bool allowSuffix=true)
Constructor with file name and opening mode.
virtual ~Archiver ()
Destructor.
StatusCode open (const std::string &archiveFileName, const std::string &openingMode="RECREATE", bool allowSuffix=true)
Open a new archive.
StatusCode close ()
Close the current archive.
StatusCode archive (Storage< MonitorElement > *pStorage, const std::string &dirName="")
Archive the current state of the storage in the root TDirectory.
const std::string & getFileName () const
Get the file name.
bool isOpened () const
Whether the archive is opened.
const std::string & getOpeningMode () const
Get the opening mode of this archive.
Static Private Member Functions
static StatusCode recursiveFill (Directory< MonitorElement > *pDirectory, TDirectory *pROOTDir)
Fill recursively the TDirectory with the Directory.
static StatusCode createTDirectories (Directory< MonitorElement > *pDirectory, TDirectory *pROOTDir)
Create TDirectories as labeled in the Directory.
static StatusCode writeMonitorElements (Directory< MonitorElement > *pDirectory, TDirectory *pROOTDir)
Write the monitor elements contained in the Directory in the TDirectory.
Private Attributes
std::string m_fileName
The root file name.
std::string m_openingMode
The root file opening mode.
bool m_isOpened
Whether the archive is opened.
TFile * m_pArchiveFile
The actual archive implementation (root file)
Friends
class MonitorElementManager
Detailed Description
Archiver class.
Definition at line 50 of file Archiver.h.
Constructor & Destructor Documentation
dqm4hep::core::Archiver::Archiver ()
Constructor.
Definition at line 44 of file Archiver.cc.
                        :
         m_fileName(""),
         m_openingMode(""),
         m_pArchiveFile(NULL),
         m_isOpened(false)
     {
       /* nop */
     }
dqm4hep::core::Archiver::Archiver (const std::string & archiveFileName, const std::string & openingMode = "RECREATE", bool allowSuffix = true)
Constructor with file name and opening mode.
Definition at line 55 of file Archiver.cc.
References open(), and THROW_RESULT_IF.
     {
       THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->open(archiveFileName, openingMode, allowSuffix));
     }
dqm4hep::core::Archiver::~Archiver () virtual
Destructor.
Definition at line 62 of file Archiver.cc.
References close(), and m_isOpened.
     {
       if(m_isOpened)
         close();
     }
Member Function Documentation
StatusCode dqm4hep::core::Archiver::archive (Storage< MonitorElement > * pStorage, const std::string & dirName = "")
Archive the current state of the storage in the root TDirectory.
Definition at line 147 of file Archiver.cc.
References isOpened(), m_pArchiveFile, recursiveFill(), RETURN_RESULT_IF, and dqm4hep::core::Storage< T >::root().
     {
       if(!this->isOpened())
         return STATUS_CODE_NOT_ALLOWED;
       TDirectory *pDirectory(nullptr);
       if(!dirName.empty())
       {
         pDirectory = m_pArchiveFile->mkdir(dirName.c_str());
         if(!pDirectory)
           return STATUS_CODE_FAILURE;
       }
       else
       {
         // TFile inherits from TDirectory ...
         pDirectory = m_pArchiveFile;
       }
       RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, recursiveFill(pStorage->root(), pDirectory));
       m_pArchiveFile->cd();
       m_pArchiveFile->Write();
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::close ()
Close the current archive.
Definition at line 129 of file Archiver.cc.
References m_isOpened, m_openingMode, and m_pArchiveFile.
Referenced by open(), and ~Archiver().
     {
       if(!m_isOpened)
         return STATUS_CODE_FAILURE;
       m_pArchiveFile->Close();
       delete m_pArchiveFile;
       m_pArchiveFile = NULL;
       m_isOpened = false;
       m_openingMode = "";
       return STATUS_CODE_SUCCESS;
     }
static StatusCode dqm4hep::core::Archiver::createTDirectories (Directory< MonitorElement > * pDirectory, TDirectory * pROOTDir) static private
Create TDirectories as labeled in the Directory.
const std::string & dqm4hep::core::Archiver::getFileName () const
Get the file name.
Definition at line 177 of file Archiver.cc.
References m_fileName.
     {
       return m_fileName;
     }
const std::string & dqm4hep::core::Archiver::getOpeningMode () const
Get the opening mode of this archive.
Definition at line 191 of file Archiver.cc.
References m_openingMode.
     {
       return m_openingMode;
     }
bool dqm4hep::core::Archiver::isOpened () const
Whether the archive is opened.
Definition at line 184 of file Archiver.cc.
References m_isOpened.
Referenced by archive().
     {
       return m_isOpened;
     }
StatusCode dqm4hep::core::Archiver::open (const std::string & archiveFileName, const std::string & openingMode = "RECREATE", bool allowSuffix = true)
Open a new archive.
Close the current file if opened. Supported opening mode are the TFile opening mode option (see TFile)
Definition at line 70 of file Archiver.cc.
References close(), dqm_error, dqm_info, m_fileName, m_isOpened, m_openingMode, m_pArchiveFile, and RETURN_RESULT_IF.
Referenced by Archiver().
     {
       // if already open write the archive if not done
       // and close it before to re-open
       if(m_isOpened)
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, close());
       if(archiveFileName.empty())
         return STATUS_CODE_INVALID_PARAMETER;
       if(allowSuffix)
       {
         int fileId(0);
         size_t pos = archiveFileName.rfind(".root");
         if(std::string::npos == pos)
         {
           dqm_error( "Couldn't open archive '{0}' ! Must be a root file !", archiveFileName );
           return STATUS_CODE_INVALID_PARAMETER;
         }
         std::string baseArchiveName = archiveFileName.substr(0, pos);
         std::string fullArchiveName = archiveFileName;
         while(!gSystem->AccessPathName(fullArchiveName.c_str()))
         {
           std::stringstream ss;
           ss << baseArchiveName << "_" << fileId << ".root";
           fullArchiveName = ss.str();
           fileId ++;
         }
         m_fileName = fullArchiveName;
       }
       else
       {
         m_fileName = archiveFileName;
       }
       m_openingMode = openingMode;
       dqm_info( "Archiver::open: Opening archive {0}", m_fileName );
       m_pArchiveFile = new TFile(m_fileName.c_str(), openingMode.c_str());
       if(NULL == m_pArchiveFile)
       {
         dqm_error( "Couldn't open archive '{0}' !", m_fileName );
         return STATUS_CODE_FAILURE;
       }
       m_isOpened = true;
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::recursiveFill (Directory< MonitorElement > * pDirectory, TDirectory * pROOTDir) static private
Fill recursively the TDirectory with the Directory.
Definition at line 198 of file Archiver.cc.
References dqm4hep::core::Directory< T >::isEmpty(), RETURN_RESULT_IF, dqm4hep::core::Directory< T >::subdirs(), and writeMonitorElements().
Referenced by archive().
     {
       if(nullptr == pDirectory || nullptr == pROOTDir)
         return STATUS_CODE_INVALID_PTR;
       pROOTDir->cd();
       const std::vector<Directory<MonitorElement>*> &subDirList(pDirectory->subdirs());
       if(!subDirList.empty())
       {
         for(auto iter = subDirList.begin(), endIter = subDirList.end() ; endIter != iter ; ++iter)
         {
           auto *pSubDir = *iter;
           TDirectory *pROOTSubDir = pROOTDir->mkdir(pSubDir->name().c_str());
           if(nullptr != pROOTSubDir)
           {
             RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, Archiver::recursiveFill(pSubDir, pROOTSubDir));
           }
         }
       }
       // write the monitor elements
       if( ! pDirectory->isEmpty() )
       {
         RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, Archiver::writeMonitorElements(pDirectory, pROOTDir));
       }
       return STATUS_CODE_SUCCESS;
     }
StatusCode dqm4hep::core::Archiver::writeMonitorElements (Directory< MonitorElement > * pDirectory, TDirectory * pROOTDir) static private
Write the monitor elements contained in the Directory in the TDirectory.
Definition at line 232 of file Archiver.cc.
References dqm4hep::core::Directory< T >::contents().
Referenced by recursiveFill().
     {
       if(nullptr == pDirectory || nullptr == pROOTDir)
         return STATUS_CODE_INVALID_PTR;
       pROOTDir->cd();
       const auto &monitorElementList(pDirectory->contents());
       for(auto iter = monitorElementList.begin(), endIter = monitorElementList.end() ; endIter != iter ; ++iter)
       {
         TObject *pObject = (*iter)->object();
         pROOTDir->WriteObjectAny(pObject, pObject->IsA(), (*iter)->name().c_str());
       }
       return STATUS_CODE_SUCCESS;
     }
Friends And Related Function Documentation
friend class MonitorElementManager friend
Definition at line 52 of file Archiver.h.
Member Data Documentation
std::string dqm4hep::core::Archiver::m_fileName private
The root file name.
Definition at line 106 of file Archiver.h.
Referenced by getFileName(), and open().
bool dqm4hep::core::Archiver::m_isOpened private
Whether the archive is opened.
Definition at line 108 of file Archiver.h.
Referenced by close(), isOpened(), open(), and ~Archiver().
std::string dqm4hep::core::Archiver::m_openingMode private
The root file opening mode.
Definition at line 107 of file Archiver.h.
Referenced by close(), getOpeningMode(), and open().
TFile* dqm4hep::core::Archiver::m_pArchiveFile private
The actual archive implementation (root file)
Definition at line 109 of file Archiver.h.
Referenced by archive(), close(), and open().
The documentation for this class was generated from the following files:
Archiver.h
Archiver.cc