DQMCore: TCLAP::OptionalUnlabeledTracker Class Reference
TCLAP::OptionalUnlabeledTracker Class Reference
#include <OptionalUnlabeledTracker.h>
Static Public Member Functions
static void check (bool req, const std::string &argName)
static void gotOptional ()
static bool & alreadyOptional ()
Static Private Member Functions
static bool & alreadyOptionalRef ()
Detailed Description
Definition at line 31 of file OptionalUnlabeledTracker.h.
Member Function Documentation
static bool& TCLAP::OptionalUnlabeledTracker::alreadyOptional () inline static
Definition at line 40 of file OptionalUnlabeledTracker.h.
References alreadyOptionalRef().
Referenced by check().
 { return alreadyOptionalRef(); }
static bool& TCLAP::OptionalUnlabeledTracker::alreadyOptionalRef () inline static private
Definition at line 44 of file OptionalUnlabeledTracker.h.
Referenced by alreadyOptional(), and gotOptional().
 { static bool ct = false; return ct; }
void TCLAP::OptionalUnlabeledTracker::check (bool req, const std::string & argName) inline static
Definition at line 48 of file OptionalUnlabeledTracker.h.
References alreadyOptional(), and gotOptional().
Referenced by TCLAP::UnlabeledMultiArg< T >::UnlabeledMultiArg(), and TCLAP::UnlabeledValueArg< T >::UnlabeledValueArg().
 {
     if ( OptionalUnlabeledTracker::alreadyOptional() )
         throw( SpecificationException(
   "You can't specify ANY Unlabeled Arg following an optional Unlabeled Arg",
                   argName ) );
     if ( !req )
         OptionalUnlabeledTracker::gotOptional();
 }
static void TCLAP::OptionalUnlabeledTracker::gotOptional () inline static
Definition at line 38 of file OptionalUnlabeledTracker.h.
References alreadyOptionalRef().
Referenced by check().
 { alreadyOptionalRef() = true; }
The documentation for this class was generated from the following file:
OptionalUnlabeledTracker.h