DQMCore: dqm4hep::core::TiXmlNode Class Reference
dqm4hep::core::TiXmlNode Class Reference abstract
The parent class for everything in the Document Object Model.
#include <tinyxml.h>
Public Types
enum NodeType {
TINYXML_DOCUMENT, TINYXML_ELEMENT, TINYXML_COMMENT, TINYXML_UNKNOWN,
TINYXML_TEXT, TINYXML_DECLARATION, TINYXML_TYPECOUNT
}
The types of XML nodes supported by TinyXml.
Public Types inherited from dqm4hep::core::TiXmlBase
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_PARSING_ELEMENT,
TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES, TIXML_ERROR_PARSING_EMPTY,
TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT, TIXML_ERROR_PARSING_DECLARATION,
TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA, TIXML_ERROR_DOCUMENT_TOP_ONLY,
TIXML_ERROR_STRING_COUNT
}
Public Member Functions
virtual ~TiXmlNode ()
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
const std::string & ValueStr () const
Return Value() as a std::string.
const TIXML_STRING & ValueTStr () const
void SetValue (const char *_value)
Changes the value of the node.
void SetValue (const std::string &_value)
STL std::string form.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'.
TiXmlNode * FirstChild (const char *_value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *_value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * FirstChild (const std::string &_value) const
STL std::string form.
TiXmlNode * FirstChild (const std::string &_value)
STL std::string form.
const TiXmlNode * LastChild (const std::string &_value) const
STL std::string form.
TiXmlNode * LastChild (const std::string &_value)
STL std::string form.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *_value, const TiXmlNode *previous)
const TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous) const
STL std::string form.
TiXmlNode * IterateChildren (const std::string &_value, const TiXmlNode *previous)
STL std::string form.
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *_prev)
const TiXmlNode * PreviousSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * PreviousSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling (const std::string &_value) const
STL std::string form.
TiXmlNode * NextSibling (const std::string &_value)
STL std::string form.
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *_next)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *_next)
const TiXmlElement * NextSiblingElement (const std::string &_value) const
STL std::string form.
TiXmlElement * NextSiblingElement (const std::string &_value)
STL std::string form.
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *_value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *_value)
const TiXmlElement * FirstChildElement (const std::string &_value) const
STL std::string form.
TiXmlElement * FirstChildElement (const std::string &_value)
STL std::string form.
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlNode * Clone () const =0
Create an exact duplicate of this node and return it.
virtual bool Accept (TiXmlVisitor *visitor) const =0
Accept a hierchical visit the nodes in the TinyXML DOM.
Public Member Functions inherited from dqm4hep::core::TiXmlBase
TiXmlBase ()
virtual ~TiXmlBase ()
virtual void Print (FILE *cfile, int depth) const =0
All TinyXml classes can print themselves to a filestream or the string class (TiXmlString in non-STL mode, std::string in STL mode.) Either or both cfile and str can be null.
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
Set a pointer to arbitrary user data.
void * GetUserData ()
Get a pointer to arbitrary user data.
const void * GetUserData () const
Get a pointer to arbitrary user data.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)=0
Protected Member Functions
TiXmlNode (NodeType _type)
void CopyTo (TiXmlNode *target) const
virtual void StreamIn (std::istream *in, TIXML_STRING *tag)=0
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Protected Attributes
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
Protected Attributes inherited from dqm4hep::core::TiXmlBase
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Private Member Functions
TiXmlNode (const TiXmlNode &)
void operator= (const TiXmlNode &base)
Friends
class TiXmlDocument
class TiXmlElement
std::istream & operator>> (std::istream &in, TiXmlNode &base)
An input stream operator, for every class.
std::ostream & operator<< (std::ostream &out, const TiXmlNode &base)
An output stream operator, for every class.
std::string & operator<< (std::string &out, const TiXmlNode &base)
Appends the XML node or attribute to a std::string.
Additional Inherited Members
Static Public Member Functions inherited from dqm4hep::core::TiXmlBase
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
static void EncodeString (const TIXML_STRING &str, TIXML_STRING *out)
Expands entities in a string.
Static Public Attributes inherited from dqm4hep::core::TiXmlBase
static const int utf8ByteTable [256]
Static Protected Member Functions inherited from dqm4hep::core::TiXmlBase
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static bool StreamWhiteSpace (std::istream *in, TIXML_STRING *tag)
static bool StreamTo (std::istream *in, int character, TIXML_STRING *tag)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Static Protected Attributes inherited from dqm4hep::core::TiXmlBase
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Detailed Description
The parent class for everything in the Document Object Model.
(Except for attributes). Nodes have siblings, a parent, and children. A node can be in a document, or stand on its own. The type of a TiXmlNode can be queried, and it can be cast to its more defined type.
Definition at line 430 of file tinyxml.h.
Member Enumeration Documentation
enum dqm4hep::core::TiXmlNode::NodeType
The types of XML nodes supported by TinyXml.
(All the unsupported types are picked up by UNKNOWN.)
Enumerator
TINYXML_DOCUMENT
TINYXML_ELEMENT
TINYXML_COMMENT
TINYXML_UNKNOWN
TINYXML_TEXT
TINYXML_DECLARATION
TINYXML_TYPECOUNT
Definition at line 469 of file tinyxml.h.
       {
         TINYXML_DOCUMENT,
         TINYXML_ELEMENT,
         TINYXML_COMMENT,
         TINYXML_UNKNOWN,
         TINYXML_TEXT,
         TINYXML_DECLARATION,
         TINYXML_TYPECOUNT
       };
Constructor & Destructor Documentation
dqm4hep::core::TiXmlNode::~TiXmlNode () virtual
Definition at line 151 of file tinyxml.cc.
References firstChild, and next.
     {
       TiXmlNode* node = firstChild;
       TiXmlNode* temp = 0;
       while ( node )
       {
         temp = node;
         node = node->next;
         delete temp;
       }
     }
dqm4hep::core::TiXmlNode::TiXmlNode (NodeType _type) protected
Definition at line 140 of file tinyxml.cc.
References firstChild, lastChild, next, parent, prev, and type.
                                          : TiXmlBase()
     {
       parent = 0;
       type = _type;
       firstChild = 0;
       lastChild = 0;
       prev = 0;
       next = 0;
     }
dqm4hep::core::TiXmlNode::TiXmlNode (const TiXmlNode &) private
Member Function Documentation
virtual bool dqm4hep::core::TiXmlNode::Accept (TiXmlVisitor * visitor) const pure virtual
Accept a hierchical visit the nodes in the TinyXML DOM.
Every node in the XML tree will be conditionally visited and the host will be called back via the TiXmlVisitor interface.
This is essentially a SAX interface for TinyXML. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
TiXmlPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implemented in dqm4hep::core::TiXmlDocument, dqm4hep::core::TiXmlUnknown, dqm4hep::core::TiXmlDeclaration, dqm4hep::core::TiXmlText, dqm4hep::core::TiXmlComment, and dqm4hep::core::TiXmlElement.
void dqm4hep::core::TiXmlNode::Clear ()
Delete all the children of this node. Does not affect 'this'.
Definition at line 173 of file tinyxml.cc.
References firstChild, lastChild, and next.
Referenced by dqm4hep::core::TiXmlElement::ClearThis(), dqm4hep::core::TiXmlDocument::LoadFile(), dqm4hep::core::TiXmlComment::operator=(), dqm4hep::core::TiXmlDeclaration::operator=(), dqm4hep::core::TiXmlDocument::operator=(), and dqm4hep::core::XmlHelper::replaceAllXmlAttributes().
     {
       TiXmlNode* node = firstChild;
       TiXmlNode* temp = 0;
       while ( node )
       {
         temp = node;
         node = node->next;
         delete temp;
       }
       firstChild = 0;
       lastChild = 0;
     }
virtual TiXmlNode* dqm4hep::core::TiXmlNode::Clone () const pure virtual
Create an exact duplicate of this node and return it.
The memory must be deleted by the caller.
Implemented in dqm4hep::core::TiXmlDocument, dqm4hep::core::TiXmlUnknown, dqm4hep::core::TiXmlDeclaration, dqm4hep::core::TiXmlText, dqm4hep::core::TiXmlComment, and dqm4hep::core::TiXmlElement.
Referenced by dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlDocument::CopyTo(), InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and ReplaceChild().
void dqm4hep::core::TiXmlNode::CopyTo (TiXmlNode * target) const protected
Definition at line 165 of file tinyxml.cc.
References dqm4hep::core::TiXmlBase::location, SetValue(), dqm4hep::core::TiXmlBase::userData, and value.
Referenced by dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlComment::CopyTo(), dqm4hep::core::TiXmlText::CopyTo(), dqm4hep::core::TiXmlDeclaration::CopyTo(), dqm4hep::core::TiXmlUnknown::CopyTo(), and dqm4hep::core::TiXmlDocument::CopyTo().
     {
       target->SetValue (value.c_str() );
       target->userData = userData;
       target->location = location;
     }
const TiXmlNode* dqm4hep::core::TiXmlNode::FirstChild () const inline
The first child of this node. Will be null if there are no children.
Definition at line 529 of file tinyxml.h.
References firstChild.
Referenced by dqm4hep::core::TiXmlElement::Accept(), dqm4hep::core::TiXmlDocument::Accept(), dqm4hep::core::TiXmlHandle::Child(), dqm4hep::core::TiXmlHandle::FirstChild(), FirstChildElement(), dqm4hep::core::TiXmlElement::GetText(), IterateChildren(), dqm4hep::core::TiXmlDocument::Print(), dqm4hep::core::XmlHelper::processConstant(), dqm4hep::core::XmlHelper::readValue(), dqm4hep::core::XmlHelper::replaceConstants(), dqm4hep::core::TiXmlPrinter::VisitEnter(), and dqm4hep::core::TiXmlPrinter::VisitExit().
TiXmlNode* dqm4hep::core::TiXmlNode::FirstChild () inline
Definition at line 530 of file tinyxml.h.
References firstChild.
 { return firstChild; }
const TiXmlNode * dqm4hep::core::TiXmlNode::FirstChild (const char * value) const
The first child of this node with the matching 'value'.
Will be null if none found.
Definition at line 361 of file tinyxml.cc.
References firstChild, next, and Value().
     {
       const TiXmlNode* node;
       for ( node = firstChild; node; node = node->next )
       {
         if ( strcmp( node->Value(), _value ) == 0 )
           return node;
       }
       return 0;
     }
TiXmlNode* dqm4hep::core::TiXmlNode::FirstChild (const char * _value) inline
The first child of this node with the matching 'value'. Will be null if none found.
Definition at line 533 of file tinyxml.h.
{
         // Call through to the const version - safe since nothing is changed. Exiting syntax: cast this to a const (always safe)
         // call the method, cast the return back to non-const.
         return const_cast< TiXmlNode* > ((const_cast< const TiXmlNode* >(this))->FirstChild( _value ));
       }
const TiXmlNode* dqm4hep::core::TiXmlNode::FirstChild (const std::string & _value) const inline
STL std::string form.
Definition at line 547 of file tinyxml.h.
References FirstChild().
Referenced by FirstChild().
TiXmlNode* dqm4hep::core::TiXmlNode::FirstChild (const std::string & _value) inline
STL std::string form.
Definition at line 548 of file tinyxml.h.
References FirstChild().
Referenced by FirstChild().
const TiXmlElement * dqm4hep::core::TiXmlNode::FirstChildElement () const
Convenience function to get through elements.
Definition at line 452 of file tinyxml.cc.
References FirstChild(), NextSibling(), and ToElement().
Referenced by dqm4hep::core::TiXmlHandle::ChildElement(), dqm4hep::core::TiXmlHandle::FirstChildElement(), dqm4hep::core::XmlHelper::processConstants(), dqm4hep::core::XmlHelper::processIncludeElements(), dqm4hep::core::XmlHelper::readXmlFile(), dqm4hep::core::XmlHelper::replaceAllXmlAttributes(), and dqm4hep::core::TiXmlDocument::RootElement().
     {
       const TiXmlNode* node;
       for ( node = FirstChild();
           node;
           node = node->NextSibling() )
       {
         if ( node->ToElement() )
           return node->ToElement();
       }
       return 0;
     }
TiXmlElement* dqm4hep::core::TiXmlNode::FirstChildElement () inline
Definition at line 672 of file tinyxml.h.
{
         return const_cast< TiXmlElement* >( (const_cast< const TiXmlNode* >(this))->FirstChildElement() );
       }
const TiXmlElement * dqm4hep::core::TiXmlNode::FirstChildElement (const char * _value) const
Convenience function to get through elements.
Definition at line 467 of file tinyxml.cc.
References FirstChild(), NextSibling(), and ToElement().
     {
       const TiXmlNode* node;
       for ( node = FirstChild( _value );
           node;
           node = node->NextSibling( _value ) )
       {
         if ( node->ToElement() )
           return node->ToElement();
       }
       return 0;
     }
TiXmlElement* dqm4hep::core::TiXmlNode::FirstChildElement (const char * _value) inline
Definition at line 678 of file tinyxml.h.
{
         return const_cast< TiXmlElement* >( (const_cast< const TiXmlNode* >(this))->FirstChildElement( _value ) );
       }
const TiXmlElement* dqm4hep::core::TiXmlNode::FirstChildElement (const std::string & _value) const inline
STL std::string form.
Definition at line 683 of file tinyxml.h.
References FirstChildElement().
Referenced by FirstChildElement().
TiXmlElement* dqm4hep::core::TiXmlNode::FirstChildElement (const std::string & _value) inline
STL std::string form.
Definition at line 684 of file tinyxml.h.
References FirstChildElement().
Referenced by FirstChildElement().
const TiXmlDocument * dqm4hep::core::TiXmlNode::GetDocument () const
Return a pointer to the Document this node lives in.
Returns null if not in a document.
Definition at line 512 of file tinyxml.cc.
References parent, and ToDocument().
Referenced by InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), LinkEndChild(), dqm4hep::core::TiXmlElement::Parse(), dqm4hep::core::TiXmlComment::Parse(), dqm4hep::core::TiXmlText::Parse(), dqm4hep::core::TiXmlDeclaration::Parse(), dqm4hep::core::TiXmlUnknown::Parse(), dqm4hep::core::TiXmlElement::ReadValue(), and ReplaceChild().
     {
       const TiXmlNode* node;
       for( node = this; node; node = node->parent )
       {
         if ( node->ToDocument() )
           return node->ToDocument();
       }
       return 0;
     }
TiXmlDocument* dqm4hep::core::TiXmlNode::GetDocument () inline
Definition at line 697 of file tinyxml.h.
{
         return const_cast< TiXmlDocument* >( (const_cast< const TiXmlNode* >(this))->GetDocument() );
       }
TiXmlNode * dqm4hep::core::TiXmlNode::Identify (const char * start, TiXmlEncoding encoding) protected
Definition at line 822 of file tinyxmlparser.cc.
References dqm4hep::core::TiXmlBase::IsAlpha(), parent, dqm4hep::core::TiXmlText::SetCDATA(), dqm4hep::core::TiXmlBase::SkipWhiteSpace(), dqm4hep::core::TiXmlBase::StringEqual(), and TiXmlElement.
Referenced by dqm4hep::core::TiXmlDocument::Parse(), and dqm4hep::core::TiXmlElement::ReadValue().
     {
       TiXmlNode* returnNode = 0;
       p = SkipWhiteSpace( p, encoding );
       if( !p || !*p || *p != '<' )
       {
         return 0;
       }
       p = SkipWhiteSpace( p, encoding );
       if ( !p || !*p )
       {
         return 0;
       }
       // What is this thing?
       // - Elements start with a letter or underscore, but xml is reserved.
       // - Comments: <!--
       // - Decleration: <?xml
       // - Everthing else is unknown to tinyxml.
       //
       const char* xmlHeader = { "<?xml" };
       const char* commentHeader = { "<!--" };
       const char* dtdHeader = { "<!" };
       const char* cdataHeader = { "<![CDATA[" };
       if ( StringEqual( p, xmlHeader, true, encoding ) )
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing Declaration\n" );
 #endif
         returnNode = new TiXmlDeclaration();
       }
       else if ( StringEqual( p, commentHeader, false, encoding ) )
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing Comment\n" );
 #endif
         returnNode = new TiXmlComment();
       }
       else if ( StringEqual( p, cdataHeader, false, encoding ) )
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing CDATA\n" );
 #endif
         TiXmlText* text = new TiXmlText( "" );
         text->SetCDATA( true );
         returnNode = text;
       }
       else if ( StringEqual( p, dtdHeader, false, encoding ) )
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing Unknown(1)\n" );
 #endif
         returnNode = new TiXmlUnknown();
       }
       else if (    IsAlpha( *(p+1), encoding )
           || *(p+1) == '_' )
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing Element\n" );
 #endif
         returnNode = new TiXmlElement( "" );
       }
       else
       {
 #ifdef DEBUG_PARSER
         TIXML_LOG( "XML parsing Unknown(2)\n" );
 #endif
         returnNode = new TiXmlUnknown();
       }
       if ( returnNode )
       {
         // Set the parent, so it can report errors
         returnNode->parent = this;
       }
       return returnNode;
     }
TiXmlNode * dqm4hep::core::TiXmlNode::InsertAfterChild (TiXmlNode * afterThis, const TiXmlNode & addThis)
Add a new node related to this.
Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 264 of file tinyxml.cc.
References Clone(), GetDocument(), lastChild, next, parent, prev, dqm4hep::core::TiXmlDocument::SetError(), TINYXML_DOCUMENT, dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by dqm4hep::core::XmlHelper::processIncludeElements().
     {
       if ( !afterThis || afterThis->parent != this ) {
         return 0;
       }
       if ( addThis.Type() == TiXmlNode::TINYXML_DOCUMENT )
       {
         if ( GetDocument() ) GetDocument()->SetError( TIXML_ERROR_DOCUMENT_TOP_ONLY, 0, 0, TIXML_ENCODING_UNKNOWN );
         return 0;
       }
       TiXmlNode* node = addThis.Clone();
       if ( !node )
         return 0;
       node->parent = this;
       node->prev = afterThis;
       node->next = afterThis->next;
       if ( afterThis->next )
       {
         afterThis->next->prev = node;
       }
       else
       {
         assert( lastChild == afterThis );
         lastChild = node;
       }
       afterThis->next = node;
       return node;
     }
TiXmlNode * dqm4hep::core::TiXmlNode::InsertBeforeChild (TiXmlNode * beforeThis, const TiXmlNode & addThis)
Add a new node related to this.
Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 232 of file tinyxml.cc.
References Clone(), firstChild, GetDocument(), next, parent, prev, dqm4hep::core::TiXmlDocument::SetError(), TINYXML_DOCUMENT, dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
     {
       if ( !beforeThis || beforeThis->parent != this ) {
         return 0;
       }
       if ( addThis.Type() == TiXmlNode::TINYXML_DOCUMENT )
       {
         if ( GetDocument() ) GetDocument()->SetError( TIXML_ERROR_DOCUMENT_TOP_ONLY, 0, 0, TIXML_ENCODING_UNKNOWN );
         return 0;
       }
       TiXmlNode* node = addThis.Clone();
       if ( !node )
         return 0;
       node->parent = this;
       node->next = beforeThis;
       node->prev = beforeThis->prev;
       if ( beforeThis->prev )
       {
         beforeThis->prev->next = node;
       }
       else
       {
         assert( firstChild == beforeThis );
         firstChild = node;
       }
       beforeThis->prev = node;
       return node;
     }
TiXmlNode * dqm4hep::core::TiXmlNode::InsertEndChild (const TiXmlNode & addThis)
Add a new node related to this.
Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
Definition at line 217 of file tinyxml.cc.
References Clone(), GetDocument(), LinkEndChild(), dqm4hep::core::TiXmlDocument::SetError(), TINYXML_DOCUMENT, dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
     {
       if ( addThis.Type() == TiXmlNode::TINYXML_DOCUMENT )
       {
         if ( GetDocument() ) GetDocument()->SetError( TIXML_ERROR_DOCUMENT_TOP_ONLY, 0, 0, TIXML_ENCODING_UNKNOWN );
         return 0;
       }
       TiXmlNode* node = addThis.Clone();
       if ( !node )
         return 0;
       return LinkEndChild( node );
     }
const TiXmlNode * dqm4hep::core::TiXmlNode::IterateChildren (const TiXmlNode * previous) const
An alternate way to walk the children of a node.
One way to iterate over nodes is:
  for( child = parent->FirstChild(); child; child = child->NextSibling() )
IterateChildren does the same thing with the syntax:
  child = 0;
  while( child = parent->IterateChildren( child ) )
IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
Definition at line 385 of file tinyxml.cc.
References FirstChild(), NextSibling(), and parent.
     {
       if ( !previous )
       {
         return FirstChild();
       }
       else
       {
         assert( previous->parent == this );
         return previous->NextSibling();
       }
     }
TiXmlNode* dqm4hep::core::TiXmlNode::IterateChildren (const TiXmlNode * previous) inline
Definition at line 570 of file tinyxml.h.
{
         return const_cast< TiXmlNode* >( (const_cast< const TiXmlNode* >(this))->IterateChildren( previous ) );
       }
const TiXmlNode * dqm4hep::core::TiXmlNode::IterateChildren (const char * value, const TiXmlNode * previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
Definition at line 399 of file tinyxml.cc.
References FirstChild(), NextSibling(), and parent.
     {
       if ( !previous )
       {
         return FirstChild( val );
       }
       else
       {
         assert( previous->parent == this );
         return previous->NextSibling( val );
       }
     }
TiXmlNode* dqm4hep::core::TiXmlNode::IterateChildren (const char * _value, const TiXmlNode * previous) inline
Definition at line 576 of file tinyxml.h.
{
         return const_cast< TiXmlNode* >( (const_cast< const TiXmlNode* >(this))->IterateChildren( _value, previous ) );
       }
const TiXmlNode* dqm4hep::core::TiXmlNode::IterateChildren (const std::string & _value, const TiXmlNode * previous) const inline
STL std::string form.
Definition at line 581 of file tinyxml.h.
References IterateChildren().
Referenced by IterateChildren().
TiXmlNode* dqm4hep::core::TiXmlNode::IterateChildren (const std::string & _value, const TiXmlNode * previous) inline
STL std::string form.
Definition at line 582 of file tinyxml.h.
References IterateChildren().
Referenced by IterateChildren().
const TiXmlNode* dqm4hep::core::TiXmlNode::LastChild () const inline
Definition at line 538 of file tinyxml.h.
References lastChild.
Referenced by dqm4hep::core::TiXmlPrinter::VisitEnter().
 { return lastChild; }
TiXmlNode* dqm4hep::core::TiXmlNode::LastChild () inline
The last child of this node. Will be null if there are no children.
Definition at line 539 of file tinyxml.h.
References lastChild.
 { return lastChild; }
const TiXmlNode * dqm4hep::core::TiXmlNode::LastChild (const char * value) const
Definition at line 373 of file tinyxml.cc.
References lastChild, prev, and Value().
     {
       const TiXmlNode* node;
       for ( node = lastChild; node; node = node->prev )
       {
         if ( strcmp( node->Value(), _value ) == 0 )
           return node;
       }
       return 0;
     }
TiXmlNode* dqm4hep::core::TiXmlNode::LastChild (const char * _value) inline
The last child of this node matching 'value'. Will be null if there are no children.
Definition at line 542 of file tinyxml.h.
{
         return const_cast< TiXmlNode* > ((const_cast< const TiXmlNode* >(this))->LastChild( _value ));
       }
const TiXmlNode* dqm4hep::core::TiXmlNode::LastChild (const std::string & _value) const inline
STL std::string form.
Definition at line 549 of file tinyxml.h.
References LastChild().
Referenced by LastChild().
TiXmlNode* dqm4hep::core::TiXmlNode::LastChild (const std::string & _value) inline
STL std::string form.
Definition at line 550 of file tinyxml.h.
References LastChild().
Referenced by LastChild().
TiXmlNode * dqm4hep::core::TiXmlNode::LinkEndChild (TiXmlNode * addThis)
Add a new node related to this.
Adds a child past the LastChild.
NOTE: the node to be added is passed by pointer, and will be henceforth owned (and deleted) by tinyXml. This method is efficient and avoids an extra copy, but should be used with care as it uses a different memory model than the other insert functions.
See Also
InsertEndChild
Definition at line 190 of file tinyxml.cc.
References firstChild, GetDocument(), lastChild, next, parent, prev, dqm4hep::core::TiXmlDocument::SetError(), TINYXML_DOCUMENT, dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and Type().
Referenced by dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlDocument::CopyTo(), InsertEndChild(), dqm4hep::core::TiXmlDocument::Parse(), dqm4hep::core::TiXmlElement::ReadValue(), and dqm4hep::core::XmlHelper::replaceAllXmlAttributes().
     {
       assert( node->parent == 0 || node->parent == this );
       assert( node->GetDocument() == 0 || node->GetDocument() == this->GetDocument() );
       if ( node->Type() == TiXmlNode::TINYXML_DOCUMENT )
       {
         delete node;
         if ( GetDocument() ) GetDocument()->SetError( TIXML_ERROR_DOCUMENT_TOP_ONLY, 0, 0, TIXML_ENCODING_UNKNOWN );
         return 0;
       }
       node->parent = this;
       node->prev = lastChild;
       node->next = 0;
       if ( lastChild )
         lastChild->next = node;
       else
         firstChild = node;      // it was an empty list.
       lastChild = node;
       return node;
     }
const TiXmlNode* dqm4hep::core::TiXmlNode::NextSibling (const std::string & _value) const inline
STL std::string form.
Definition at line 633 of file tinyxml.h.
References NextSibling().
Referenced by dqm4hep::core::TiXmlElement::Accept(), dqm4hep::core::TiXmlDocument::Accept(), dqm4hep::core::TiXmlHandle::Child(), dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlDocument::CopyTo(), FirstChildElement(), IterateChildren(), NextSibling(), NextSiblingElement(), dqm4hep::core::TiXmlElement::Print(), dqm4hep::core::TiXmlDocument::Print(), and dqm4hep::core::XmlHelper::replaceConstants().
TiXmlNode* dqm4hep::core::TiXmlNode::NextSibling (const std::string & _value) inline
STL std::string form.
Definition at line 634 of file tinyxml.h.
References NextSibling().
Referenced by NextSibling().
const TiXmlNode* dqm4hep::core::TiXmlNode::NextSibling () const inline
Navigate to a sibling node.
Definition at line 638 of file tinyxml.h.
References next.
Referenced by NextSiblingElement().
 { return next; }
TiXmlNode* dqm4hep::core::TiXmlNode::NextSibling () inline
Definition at line 639 of file tinyxml.h.
References next.
 { return next; }
const TiXmlNode * dqm4hep::core::TiXmlNode::NextSibling (const char * _value) const
Navigate to a sibling node with the given 'value'.
Definition at line 413 of file tinyxml.cc.
References next, and Value().
     {
       const TiXmlNode* node;
       for ( node = next; node; node = node->next )
       {
         if ( strcmp( node->Value(), _value ) == 0 )
           return node;
       }
       return 0;
     }
TiXmlNode* dqm4hep::core::TiXmlNode::NextSibling (const char * _next) inline
Definition at line 643 of file tinyxml.h.
{
         return const_cast< TiXmlNode* >( (const_cast< const TiXmlNode* >(this))->NextSibling( _next ) );
       }
const TiXmlElement * dqm4hep::core::TiXmlNode::NextSiblingElement () const
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 482 of file tinyxml.cc.
References NextSibling(), and ToElement().
Referenced by dqm4hep::core::TiXmlHandle::ChildElement(), dqm4hep::core::XmlHelper::processConstants(), dqm4hep::core::XmlHelper::processIncludeElements(), dqm4hep::core::XmlHelper::read2DVectorOfValues(), dqm4hep::core::XmlHelper::readParameterValue(), dqm4hep::core::XmlHelper::readParameterValues(), and dqm4hep::core::XmlHelper::replaceAllXmlAttributes().
     {
       const TiXmlNode* node;
       for ( node = NextSibling();
           node;
           node = node->NextSibling() )
       {
         if ( node->ToElement() )
           return node->ToElement();
       }
       return 0;
     }
TiXmlElement* dqm4hep::core::TiXmlNode::NextSiblingElement () inline
Definition at line 652 of file tinyxml.h.
{
         return const_cast< TiXmlElement* >( (const_cast< const TiXmlNode* >(this))->NextSiblingElement() );
       }
const TiXmlElement * dqm4hep::core::TiXmlNode::NextSiblingElement (const char * _value) const
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 497 of file tinyxml.cc.
References NextSibling(), and ToElement().
     {
       const TiXmlNode* node;
       for ( node = NextSibling( _value );
           node;
           node = node->NextSibling( _value ) )
       {
         if ( node->ToElement() )
           return node->ToElement();
       }
       return 0;
     }
TiXmlElement* dqm4hep::core::TiXmlNode::NextSiblingElement (const char * _next) inline
Definition at line 661 of file tinyxml.h.
{
         return const_cast< TiXmlElement* >( (const_cast< const TiXmlNode* >(this))->NextSiblingElement( _next ) );
       }
const TiXmlElement* dqm4hep::core::TiXmlNode::NextSiblingElement (const std::string & _value) const inline
STL std::string form.
Definition at line 666 of file tinyxml.h.
References NextSiblingElement().
Referenced by NextSiblingElement().
TiXmlElement* dqm4hep::core::TiXmlNode::NextSiblingElement (const std::string & _value) inline
STL std::string form.
Definition at line 667 of file tinyxml.h.
References NextSiblingElement().
Referenced by NextSiblingElement().
bool dqm4hep::core::TiXmlNode::NoChildren () const inline
Returns true if this node has no children.
Definition at line 702 of file tinyxml.h.
References firstChild.
Referenced by dqm4hep::core::XmlHelper::replaceAllXmlAttributes().
 { return !firstChild; }
void dqm4hep::core::TiXmlNode::operator= (const TiXmlNode & base) private
TiXmlNode* dqm4hep::core::TiXmlNode::Parent () inline
One step up the DOM.
Definition at line 526 of file tinyxml.h.
References parent.
 { return parent; }
const TiXmlNode* dqm4hep::core::TiXmlNode::Parent () const inline
Definition at line 527 of file tinyxml.h.
References parent.
 { return parent; }
const TiXmlNode* dqm4hep::core::TiXmlNode::PreviousSibling () const inline
Navigate to a sibling node.
Definition at line 621 of file tinyxml.h.
References prev.
 { return prev; }
TiXmlNode* dqm4hep::core::TiXmlNode::PreviousSibling () inline
Definition at line 622 of file tinyxml.h.
References prev.
 { return prev; }
const TiXmlNode * dqm4hep::core::TiXmlNode::PreviousSibling (const char * _value) const
Navigate to a sibling node.
Definition at line 425 of file tinyxml.cc.
References prev, and Value().
     {
       const TiXmlNode* node;
       for ( node = prev; node; node = node->prev )
       {
         if ( strcmp( node->Value(), _value ) == 0 )
           return node;
       }
       return 0;
     }
TiXmlNode* dqm4hep::core::TiXmlNode::PreviousSibling (const char * _prev) inline
Definition at line 626 of file tinyxml.h.
{
         return const_cast< TiXmlNode* >( (const_cast< const TiXmlNode* >(this))->PreviousSibling( _prev ) );
       }
const TiXmlNode* dqm4hep::core::TiXmlNode::PreviousSibling (const std::string & _value) const inline
STL std::string form.
Definition at line 631 of file tinyxml.h.
References PreviousSibling().
Referenced by PreviousSibling().
TiXmlNode* dqm4hep::core::TiXmlNode::PreviousSibling (const std::string & _value) inline
STL std::string form.
Definition at line 632 of file tinyxml.h.
References PreviousSibling().
Referenced by PreviousSibling().
bool dqm4hep::core::TiXmlNode::RemoveChild (TiXmlNode * removeThis)
Delete a child of this node.
Definition at line 335 of file tinyxml.cc.
References firstChild, lastChild, next, parent, and prev.
Referenced by dqm4hep::core::XmlHelper::processIncludeElements().
     {
       if ( !removeThis ) {
         return false;
       }
       if ( removeThis->parent != this )
       {
         assert( 0 );
         return false;
       }
       if ( removeThis->next )
         removeThis->next->prev = removeThis->prev;
       else
         lastChild = removeThis->prev;
       if ( removeThis->prev )
         removeThis->prev->next = removeThis->next;
       else
         firstChild = removeThis->next;
       delete removeThis;
       return true;
     }
TiXmlNode * dqm4hep::core::TiXmlNode::ReplaceChild (TiXmlNode * replaceThis, const TiXmlNode & withThis)
Replace a child of this node.
Returns a pointer to the new object or NULL if an error occured.
Definition at line 296 of file tinyxml.cc.
References Clone(), firstChild, GetDocument(), lastChild, next, parent, prev, dqm4hep::core::TiXmlDocument::SetError(), dqm4hep::core::TIXML_ENCODING_UNKNOWN, dqm4hep::core::TiXmlBase::TIXML_ERROR_DOCUMENT_TOP_ONLY, and ToDocument().
     {
       if ( !replaceThis )
         return 0;
       if ( replaceThis->parent != this )
         return 0;
       if ( withThis.ToDocument() ) {
         // A document can never be a child. Thanks to Noam.
         TiXmlDocument* document = GetDocument();
         if ( document )
           document->SetError( TIXML_ERROR_DOCUMENT_TOP_ONLY, 0, 0, TIXML_ENCODING_UNKNOWN );
         return 0;
       }
       TiXmlNode* node = withThis.Clone();
       if ( !node )
         return 0;
       node->next = replaceThis->next;
       node->prev = replaceThis->prev;
       if ( replaceThis->next )
         replaceThis->next->prev = node;
       else
         lastChild = node;
       if ( replaceThis->prev )
         replaceThis->prev->next = node;
       else
         firstChild = node;
       delete replaceThis;
       node->parent = this;
       return node;
     }
void dqm4hep::core::TiXmlNode::SetValue (const char * _value) inline
Changes the value of the node.
Defined as:
Document: filename of the xml file
Element:  name of the element
Comment:  the comment text
Unknown:  the tag contents
Text:   the text string
Definition at line 515 of file tinyxml.h.
References value.
Referenced by CopyTo(), dqm4hep::core::XmlHelper::replaceConstants(), dqm4hep::core::TiXmlComment::TiXmlComment(), and dqm4hep::core::TiXmlText::TiXmlText().
 { value = _value;}
void dqm4hep::core::TiXmlNode::SetValue (const std::string & _value) inline
STL std::string form.
Definition at line 519 of file tinyxml.h.
 { value = _value; }
virtual void dqm4hep::core::TiXmlNode::StreamIn (std::istream * in, TIXML_STRING * tag) protected pure virtual
Implemented in dqm4hep::core::TiXmlDocument, dqm4hep::core::TiXmlUnknown, dqm4hep::core::TiXmlDeclaration, dqm4hep::core::TiXmlText, dqm4hep::core::TiXmlComment, and dqm4hep::core::TiXmlElement.
virtual const TiXmlComment* dqm4hep::core::TiXmlNode::ToComment () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlComment.
Definition at line 706 of file tinyxml.h.
virtual TiXmlComment* dqm4hep::core::TiXmlNode::ToComment () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlComment.
Definition at line 713 of file tinyxml.h.
virtual const TiXmlDeclaration* dqm4hep::core::TiXmlNode::ToDeclaration () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlDeclaration.
Definition at line 709 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlDocument::Parse().
virtual TiXmlDeclaration* dqm4hep::core::TiXmlNode::ToDeclaration () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlDeclaration.
Definition at line 716 of file tinyxml.h.
virtual const TiXmlDocument* dqm4hep::core::TiXmlNode::ToDocument () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlDocument.
Definition at line 704 of file tinyxml.h.
Referenced by GetDocument(), and ReplaceChild().
virtual TiXmlDocument* dqm4hep::core::TiXmlNode::ToDocument () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlDocument.
Definition at line 711 of file tinyxml.h.
virtual const TiXmlElement* dqm4hep::core::TiXmlNode::ToElement () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlElement.
Definition at line 705 of file tinyxml.h.
Referenced by FirstChildElement(), NextSiblingElement(), and dqm4hep::core::TiXmlHandle::ToElement().
virtual TiXmlElement* dqm4hep::core::TiXmlNode::ToElement () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlElement.
Definition at line 712 of file tinyxml.h.
virtual const TiXmlText* dqm4hep::core::TiXmlNode::ToText () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlText.
Definition at line 708 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlElement::GetText(), dqm4hep::core::TiXmlElement::Print(), dqm4hep::core::TiXmlHandle::ToText(), and dqm4hep::core::TiXmlPrinter::VisitEnter().
virtual TiXmlText* dqm4hep::core::TiXmlNode::ToText () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlText.
Definition at line 715 of file tinyxml.h.
virtual const TiXmlUnknown* dqm4hep::core::TiXmlNode::ToUnknown () const inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlUnknown.
Definition at line 707 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlHandle::ToUnknown().
virtual TiXmlUnknown* dqm4hep::core::TiXmlNode::ToUnknown () inline virtual
Cast to a more defined type. Will return null if not of the requested type.
Reimplemented in dqm4hep::core::TiXmlUnknown.
Definition at line 714 of file tinyxml.h.
int dqm4hep::core::TiXmlNode::Type () const inline
Query the type (as an enumerated value, above) of this node.
The possible types are: DOCUMENT, ELEMENT, COMMENT, UNKNOWN, TEXT, and DECLARATION.
Definition at line 691 of file tinyxml.h.
References type.
Referenced by InsertAfterChild(), InsertBeforeChild(), InsertEndChild(), and LinkEndChild().
 { return type; }
const char* dqm4hep::core::TiXmlNode::Value () const inline
The meaning of 'value' changes for the specific type of TiXmlNode.
Document: filename of the xml file
Element:  name of the element
Comment:  the comment text
Unknown:  the tag contents
Text:   the text string
The subclasses will wrap this function.
Definition at line 494 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::TiXmlElement::Clone(), FirstChild(), dqm4hep::core::TiXmlElement::GetText(), LastChild(), dqm4hep::core::TiXmlDocument::LoadFile(), NextSibling(), PreviousSibling(), dqm4hep::core::XmlHelper::processConstant(), dqm4hep::core::XmlHelper::processIncludeElement(), dqm4hep::core::XmlHelper::processIncludeElements(), dqm4hep::core::TiXmlDocument::SaveFile(), dqm4hep::core::TiXmlPrinter::Visit(), dqm4hep::core::TiXmlPrinter::VisitEnter(), and dqm4hep::core::TiXmlPrinter::VisitExit().
 { return value.c_str (); }
const std::string& dqm4hep::core::TiXmlNode::ValueStr () const inline
Return Value() as a std::string.
If you only use STL, this is more efficient than calling Value(). Only available in STL mode.
Definition at line 501 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::XmlHelper::replaceConstants().
 { return value; }
const TIXML_STRING& dqm4hep::core::TiXmlNode::ValueTStr () const inline
Definition at line 504 of file tinyxml.h.
References value.
Referenced by dqm4hep::core::TiXmlPrinter::Visit().
 { return value; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const TiXmlNode & base) friend
An output stream operator, for every class.
Note that this outputs without any newlines or formatting, as opposed to Print(), which includes tabs and new lines.
The operator<< and operator>> are not completely symmetric. Writing a node to a stream is very well defined. You'll get a nice stream of output, without any extra whitespace or newlines.
But reading is not as well defined. (As it always is.) If you create a TiXmlElement (for example) and read that from an input stream, the text needs to define an element or junk will result. This is true of all input streams, but it's worth keeping in mind.
A TiXmlDocument will read nodes until it reads a root element, and all the children of that root element.
std::string& operator<< (std::string & out, const TiXmlNode & base) friend
Appends the XML node or attribute to a std::string.
std::istream& operator>> (std::istream & in, TiXmlNode & base) friend
An input stream operator, for every class.
Tolerant of newlines and formatting, but doesn't expect them.
friend class TiXmlDocument friend
Definition at line 432 of file tinyxml.h.
friend class TiXmlElement friend
Definition at line 433 of file tinyxml.h.
Referenced by Identify().
Member Data Documentation
TiXmlNode* dqm4hep::core::TiXmlNode::firstChild protected
Definition at line 765 of file tinyxml.h.
Referenced by Clear(), dqm4hep::core::TiXmlElement::CopyTo(), dqm4hep::core::TiXmlDocument::CopyTo(), FirstChild(), InsertBeforeChild(), LinkEndChild(), NoChildren(), dqm4hep::core::TiXmlDocument::Parse(), dqm4hep::core::TiXmlElement::Print(), RemoveChild(), ReplaceChild(), dqm4hep::core::TiXmlElement::TiXmlElement(), TiXmlNode(), and ~TiXmlNode().
TiXmlNode* dqm4hep::core::TiXmlNode::lastChild protected
Definition at line 766 of file tinyxml.h.
Referenced by Clear(), InsertAfterChild(), LastChild(), LinkEndChild(), dqm4hep::core::TiXmlElement::Print(), RemoveChild(), ReplaceChild(), dqm4hep::core::TiXmlElement::TiXmlElement(), and TiXmlNode().
TiXmlNode* dqm4hep::core::TiXmlNode::next protected
Definition at line 771 of file tinyxml.h.
Referenced by Clear(), FirstChild(), InsertAfterChild(), InsertBeforeChild(), LinkEndChild(), NextSibling(), RemoveChild(), ReplaceChild(), TiXmlNode(), and ~TiXmlNode().
TiXmlNode* dqm4hep::core::TiXmlNode::parent protected
Definition at line 762 of file tinyxml.h.
Referenced by GetDocument(), Identify(), InsertAfterChild(), InsertBeforeChild(), IterateChildren(), LinkEndChild(), Parent(), RemoveChild(), ReplaceChild(), and TiXmlNode().
TiXmlNode* dqm4hep::core::TiXmlNode::prev protected
Definition at line 770 of file tinyxml.h.
Referenced by InsertAfterChild(), InsertBeforeChild(), LastChild(), LinkEndChild(), PreviousSibling(), RemoveChild(), ReplaceChild(), and TiXmlNode().
NodeType dqm4hep::core::TiXmlNode::type protected
Definition at line 763 of file tinyxml.h.
Referenced by TiXmlNode(), and Type().
TIXML_STRING dqm4hep::core::TiXmlNode::value protected
Definition at line 768 of file tinyxml.h.
Referenced by dqm4hep::core::TiXmlText::Blank(), CopyTo(), dqm4hep::core::TiXmlDocument::LoadFile(), dqm4hep::core::TiXmlElement::Parse(), dqm4hep::core::TiXmlComment::Parse(), dqm4hep::core::TiXmlText::Parse(), dqm4hep::core::TiXmlUnknown::Parse(), dqm4hep::core::TiXmlElement::Print(), dqm4hep::core::TiXmlComment::Print(), dqm4hep::core::TiXmlText::Print(), dqm4hep::core::TiXmlUnknown::Print(), SetValue(), dqm4hep::core::TiXmlDocument::TiXmlDocument(), dqm4hep::core::TiXmlElement::TiXmlElement(), Value(), ValueStr(), and ValueTStr().
The documentation for this class was generated from the following files:
tinyxml.h
tinyxml.cc
tinyxmlparser.cc