DQMCore: dqm4hep::core::Plugin Class Reference
dqm4hep::core::Plugin Class Reference abstract
Plugin class.
#include <Plugin.h>
Public Member Functions
Plugin (const std::string &pluginName)
Constructor.
virtual ~Plugin ()
Destructor.
const std::string & pluginName () const
Returns the plug-in name.
virtual Plugin * create () const =0
Create a new instance of the wrapped class.
virtual std::string className () const =0
Returns the class name.
Protected Member Functions
StatusCode registerMe ()
Private Attributes
const std::string m_pluginName
Friends
class PluginManager
Detailed Description
Plugin class.
Definition at line 43 of file Plugin.h.
Constructor & Destructor Documentation
dqm4hep::core::Plugin::Plugin (const std::string & pluginName)
Constructor.
Definition at line 37 of file Plugin.cc.
                                               :
         m_pluginName( pluginName )
     {
       /* nop */
     }
dqm4hep::core::Plugin::~Plugin () virtual
Destructor.
Definition at line 45 of file Plugin.cc.
     {
       /* nop */
     }
Member Function Documentation
virtual std::string dqm4hep::core::Plugin::className () const pure virtual
Returns the class name.
virtual Plugin* dqm4hep::core::Plugin::create () const pure virtual
Create a new instance of the wrapped class.
Referenced by dqm4hep::core::PluginManager::create().
const std::string & dqm4hep::core::Plugin::pluginName () const
Returns the plug-in name.
Definition at line 52 of file Plugin.cc.
References m_pluginName.
Referenced by dqm4hep::core::PluginManager::registerPlugin().
     {
       return m_pluginName;
     }
StatusCode dqm4hep::core::Plugin::registerMe () protected
Definition at line 59 of file Plugin.cc.
References dqm4hep::core::Singleton< PluginManager >::instance(), and dqm4hep::core::PluginManager::registerPlugin().
     {
       return PluginManager::instance()->registerPlugin( this );
     }
Friends And Related Function Documentation
friend class PluginManager friend
Definition at line 45 of file Plugin.h.
Member Data Documentation
const std::string dqm4hep::core::Plugin::m_pluginName private
Definition at line 71 of file Plugin.h.
Referenced by pluginName().
The documentation for this class was generated from the following files:
Plugin.h
Plugin.cc