DQMCore: dqm4hep::core::Directory< T > Class Template Reference
dqm4hep::core::Directory< T > Class Template Reference
Directory class.
#include <Archiver.h>
Public Types
typedef std::vector< T * > ObjectList
Public Member Functions
Directory ()
Default constructor.
Directory (const std::string &name, Directory< T > *pParentDir=NULL)
Constructor with name and parent dir.
~Directory ()
Destructor.
Directory< T > * mkdir (const std::string &dirName)
Create a new directory.
const std::string & name () const
Returns the directory name.
Directory< T > * parent () const
Returns the parent directory.
const std::vector< Directory
< T > * > & subdirs () const
Get the sub directory list.
bool hasChild (const std::string &dirName) const
Whether the directory contains the sub dir.
StatusCode find (const std::string &dirName, Directory< T > *&pDirectory) const
Find the sub directory by name.
StatusCode add (T *pObject)
Add an object to the directory.
template<typename F >
T * find (F function) const
Find a monitor element with a given name in the directory.
bool containsObject (const T *pObject) const
Whether the directory contains the monitor element (search by ptr compare)
template<typename F >
bool contains (F function) const
Whether the directory contains the monitor element (search by name compare)
StatusCode remove (T *pObject)
Remove the monitor element from the directory.
template<typename F >
StatusCode remove (F function)
Remove the monitor element from the directory.
const ObjectList & contents () const
Get the monitor element list.
StatusCode rmdir (const std::string &dirName)
Remove the directory and its contents.
void clear ()
Clear the directory.
Path fullPath () const
Get the full path name of the directory.
bool isRoot () const
Whether the directory is a root directory.
bool isEmpty () const
Whether the directory is empty.
Private Attributes
std::string m_name
Directory * m_pParent
std::vector< Directory< T > * > m_subdirs
ObjectList m_contents
Detailed Description
template<typename T>
class dqm4hep::core::Directory< T >
Directory class.
A directory is the owner of its sub-directories. Unit owning depends on how the method are called (default : not owner)
This interface doesn't allow moving sub-directories
Definition at line 44 of file Archiver.h.
Member Typedef Documentation
template<typename T> typedef std::vector<T*> dqm4hep::core::Directory< T >::ObjectList
Definition at line 53 of file Directory.h.
Constructor & Destructor Documentation
template<typename T > dqm4hep::core::Directory< T >::Directory () inline
Default constructor.
Definition at line 155 of file Directory.h.
                                    :
       m_name(""),
       m_pParent(nullptr),
       m_subdirs(),
       m_contents()
     {
       /* nop */
     }
template<typename T> dqm4hep::core::Directory< T >::Directory (const std::string & name, Directory< T > * pParentDir = NULL) inline
Constructor with name and parent dir.
Definition at line 167 of file Directory.h.
                                                                                :
       m_name(name),
       m_pParent(pParent),
       m_subdirs(),
       m_contents()
     {
       /* nop */
     }
template<typename T > dqm4hep::core::Directory< T >::~Directory () inline
Destructor.
Delete the subdirectories but not the contents
Definition at line 179 of file Directory.h.
     {
       this->clear();
     }
Member Function Documentation
template<typename T> StatusCode dqm4hep::core::Directory< T >::add (T * pObject) inline
Add an object to the directory.
Definition at line 274 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::add().
     {
       if(nullptr == pObject)
         return STATUS_CODE_INVALID_PTR;
       if(this->containsObject(pObject))
         return STATUS_CODE_ALREADY_PRESENT;
       m_contents.push_back(pObject);
       return STATUS_CODE_SUCCESS;
     }
template<typename T > void dqm4hep::core::Directory< T >::clear () inline
Clear the directory.
The operation is done recursively
Definition at line 406 of file Directory.h.
     {
       for(typename std::vector<Directory<T>*>::iterator iter = m_subdirs.begin(), endIter = m_subdirs.end() ;
           endIter != iter ; ++iter)
       {
         (*iter)->clear();
         delete *iter;
       }
       for(typename ObjectList::iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
         delete *iter;
       m_subdirs.clear();
       m_contents.clear();
     }
template<typename T > template<typename F > bool dqm4hep::core::Directory< T >::contains (F function) const inline
Whether the directory contains the monitor element (search by name compare)
Definition at line 321 of file Directory.h.
     {
       for(typename ObjectList::const_iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
         if(function(*iter))
           return true;
       return false;
     }
template<typename T> bool dqm4hep::core::Directory< T >::containsObject (const T * pObject) const inline
Whether the directory contains the monitor element (search by ptr compare)
Definition at line 304 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::containsObject().
     {
       if(nullptr == pObject)
         return false;
       for(typename ObjectList::const_iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
         if(pObject == *iter)
           return true;
       return false;
     }
template<typename T > const Directory< T >::ObjectList & dqm4hep::core::Directory< T >::contents () const inline
Get the monitor element list.
Definition at line 377 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::iterate(), and dqm4hep::core::Archiver::writeMonitorElements().
     {
       return m_contents;
     }
template<typename T> StatusCode dqm4hep::core::Directory< T >::find (const std::string & dirName, Directory< T > *& pDirectory) const inline
Find the sub directory by name.
Definition at line 252 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::cd(), dqm4hep::core::Storage< T >::find(), dqm4hep::core::Storage< T >::findObject(), and dqm4hep::core::Storage< T >::mkdir().
     {
       pDirectory = nullptr;
       for(typename std::vector<Directory<T>*>::const_iterator iter = m_subdirs.begin(), endIter = m_subdirs.end() ;
           endIter != iter ; ++iter)
       {
         Directory<T> *pDir = *iter;
         if(pDir->name() == dirName)
         {
           pDirectory = pDir;
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > template<typename F > T * dqm4hep::core::Directory< T >::find (F function) const inline
Find a monitor element with a given name in the directory.
Definition at line 291 of file Directory.h.
     {
       for(typename ObjectList::const_iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
         if(function(*iter))
           return *iter;
       return nullptr;
     }
template<typename T > Path dqm4hep::core::Directory< T >::fullPath () const inline
Get the full path name of the directory.
Definition at line 426 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::rmdir().
     {
       Path fullPath = this->name();
       const Directory<T> *pDir = this;
       while(1)
       {
         const Directory<T> *pParentDir = pDir->parent();
         if(nullptr != pParentDir)
         {
           fullPath = pParentDir->name() + fullPath;
           pDir = pParentDir;
         }
         else
         {
           fullPath = Path("/") + fullPath;
           break;
         }
       }
       return fullPath;
     }
template<typename T > bool dqm4hep::core::Directory< T >::hasChild (const std::string & dirName) const inline
Whether the directory contains the sub dir.
Definition at line 232 of file Directory.h.
References dqm4hep::core::containsSpecialCharacters().
Referenced by dqm4hep::core::Storage< T >::mkdir().
     {
       if(dirName.find("/") != std::string::npos || dqm4hep::core::containsSpecialCharacters(dirName) || dirName.empty())
         return false;
       for(typename std::vector<Directory<T>*>::const_iterator iter = m_subdirs.begin(), endIter = m_subdirs.end() ;
           endIter != iter ; ++iter)
       {
         Directory<T> *pDirectory = *iter;
         if(pDirectory->name() == dirName)
           return true;
       }
       return false;
     }
template<typename T > bool dqm4hep::core::Directory< T >::isEmpty () const inline
Whether the directory is empty.
Definition at line 461 of file Directory.h.
Referenced by dqm4hep::core::Archiver::recursiveFill().
     {
       return (m_subdirs.empty() && m_contents.empty());
     }
template<typename T > bool dqm4hep::core::Directory< T >::isRoot () const inline
Whether the directory is a root directory.
Definition at line 453 of file Directory.h.
     {
       return (nullptr == m_pParent);
     }
template<typename T > Directory< T > * dqm4hep::core::Directory< T >::mkdir (const std::string & dirName) inline
Create a new directory.
Definition at line 211 of file Directory.h.
References dqm4hep::core::containsSpecialCharacters().
Referenced by dqm4hep::core::Storage< T >::mkdir().
     {
       Directory<T> *pDirectory = nullptr;
       this->find(dirName, pDirectory);
       if(nullptr != pDirectory)
         return pDirectory;
       if(dirName.find("/") != std::string::npos || dqm4hep::core::containsSpecialCharacters(dirName) || dirName.empty())
         return nullptr;
       Directory<T> *pNewDirectory = new Directory<T>(dirName, this);
       m_subdirs.push_back(pNewDirectory);
       return pNewDirectory;
     }
template<typename T > const std::string & dqm4hep::core::Directory< T >::name () const inline
Returns the directory name.
Definition at line 187 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::rmdir().
     {
       return m_name;
     }
template<typename T > Directory< T > * dqm4hep::core::Directory< T >::parent () const inline
Returns the parent directory.
Definition at line 195 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::cd(), dqm4hep::core::Storage< T >::find(), dqm4hep::core::Storage< T >::mkdir(), and dqm4hep::core::Storage< T >::rmdir().
     {
       return m_pParent;
     }
template<typename T> StatusCode dqm4hep::core::Directory< T >::remove (T * pObject) inline
Remove the monitor element from the directory.
Definition at line 334 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::remove().
     {
       if(nullptr == pObject)
         return STATUS_CODE_INVALID_PTR;
       for(typename ObjectList::iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
       {
         if(pObject == *iter)
         {
           m_contents.erase(iter);
           delete pObject;
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > template<typename F > StatusCode dqm4hep::core::Directory< T >::remove (F function) inline
Remove the monitor element from the directory.
Definition at line 357 of file Directory.h.
     {
       for(typename ObjectList::iterator iter = m_contents.begin(), endIter = m_contents.end() ;
           endIter != iter ; ++iter)
       {
         if(function(*iter))
         {
           T *pObject = *iter;
           m_contents.erase(iter);
           delete pObject;
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > StatusCode dqm4hep::core::Directory< T >::rmdir (const std::string & dirName) inline
Remove the directory and its contents.
Definition at line 385 of file Directory.h.
     {
       for(typename std::vector<Directory<T>*>::iterator iter = m_subdirs.begin(), endIter = m_subdirs.end() ;
           endIter != iter ; ++iter)
       {
         Directory<T> *pDir = *iter;
         if(pDir->name() == dirName)
         {
           m_subdirs.erase(iter);
           delete pDir;
           return STATUS_CODE_SUCCESS;
         }
       }
       return STATUS_CODE_NOT_FOUND;
     }
template<typename T > const std::vector< Directory< T > * > & dqm4hep::core::Directory< T >::subdirs () const inline
Get the sub directory list.
Definition at line 203 of file Directory.h.
Referenced by dqm4hep::core::Storage< T >::iterate(), and dqm4hep::core::Archiver::recursiveFill().
     {
       return m_subdirs;
     }
Member Data Documentation
template<typename T> ObjectList dqm4hep::core::Directory< T >::m_contents private
Definition at line 148 of file Directory.h.
template<typename T> std::string dqm4hep::core::Directory< T >::m_name private
Definition at line 145 of file Directory.h.
template<typename T> Directory* dqm4hep::core::Directory< T >::m_pParent private
Definition at line 146 of file Directory.h.
template<typename T> std::vector<Directory<T>*> dqm4hep::core::Directory< T >::m_subdirs private
Definition at line 147 of file Directory.h.
The documentation for this class was generated from the following files:
Archiver.h
Directory.h