DQMCore: TCLAP::ZshCompletionOutput Class Reference
TCLAP::ZshCompletionOutput Class Reference
A class that generates a Zsh completion function as output from the usage() method for the given CmdLine and its Args.
#include <ZshCompletionOutput.h>
Public Member Functions
ZshCompletionOutput ()
virtual void usage (CmdLineInterface &c)
Prints the usage to stdout.
virtual void version (CmdLineInterface &c)
Prints the version to stdout.
virtual void failure (CmdLineInterface &c, ArgException &e)
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Public Member Functions inherited from TCLAP::CmdLineOutput
virtual ~CmdLineOutput ()
Virtual destructor.
Protected Member Functions
void basename (std::string &s)
void quoteSpecialChars (std::string &s)
std::string getMutexList (CmdLineInterface &_cmd, Arg *a)
void printOption (Arg *it, std::string mutex)
void printArg (Arg *it)
Protected Attributes
std::map< std::string,
std::string > common
char theDelimiter
Detailed Description
A class that generates a Zsh completion function as output from the usage() method for the given CmdLine and its Args.
Definition at line 43 of file ZshCompletionOutput.h.
Constructor & Destructor Documentation
TCLAP::ZshCompletionOutput::ZshCompletionOutput ()
Definition at line 86 of file ZshCompletionOutput.h.
References common.
 : common(std::map<std::string, std::string>()),
   theDelimiter('=')
 {
   common["host"] = "_hosts";
   common["hostname"] = "_hosts";
   common["file"] = "_files";
   common["filename"] = "_files";
   common["user"] = "_users";
   common["username"] = "_users";
   common["directory"] = "_directories";
   common["path"] = "_directories";
   common["url"] = "_urls";
 }
Member Function Documentation
void TCLAP::ZshCompletionOutput::basename (std::string & s) inline protected
Definition at line 155 of file ZshCompletionOutput.h.
Referenced by usage().
 {
   size_t p = s.find_last_of('/');
   if ( p != std::string::npos )
   {
     s.erase(0, p + 1);
   }
 }
void TCLAP::ZshCompletionOutput::failure (CmdLineInterface & c, ArgException & e) inline virtual
Prints (to stderr) an error message, short usage Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
e - The ArgException that caused the failure.
Implements TCLAP::CmdLineOutput.
Definition at line 129 of file ZshCompletionOutput.h.
References TCLAP::ArgException::what().
 {
   static_cast<void>(_cmd); // unused
   std::cout << e.what() << std::endl;
 }
std::string TCLAP::ZshCompletionOutput::getMutexList (CmdLineInterface & _cmd, Arg * a) inline protected
Definition at line 271 of file ZshCompletionOutput.h.
References TCLAP::Arg::acceptsMultipleValues(), TCLAP::Arg::flagStartChar(), TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::CmdLineInterface::getXorHandler(), TCLAP::XorHandler::getXorList(), and TCLAP::Arg::nameStartString().
Referenced by usage().
 {
   XorHandler xorHandler = _cmd.getXorHandler();
   std::vector< std::vector<Arg*> > xorList = xorHandler.getXorList();
   if (a->getName() == "help" || a->getName() == "version")
   {
     return "(-)";
   }
   std::ostringstream list;
   if ( a->acceptsMultipleValues() )
   {
     list << '*';
   }
   for ( int i = 0; static_cast<unsigned int>(i) < xorList.size(); i++ )
   {
     for ( ArgVectorIterator it = xorList[i].begin();
       it != xorList[i].end();
       it++)
     if ( a == (*it) )
     {
       list << '(';
       for ( ArgVectorIterator iu = xorList[i].begin();
         iu != xorList[i].end();
         iu++ )
       {
         bool notCur = (*iu) != a;
         bool hasFlag = !(*iu)->getFlag().empty();
         if ( iu != xorList[i].begin() && (notCur || hasFlag) )
           list << ' ';
         if (hasFlag)
           list << (*iu)->flagStartChar() << (*iu)->getFlag() << ' ';
         if ( notCur || hasFlag )
           list << (*iu)->nameStartString() << (*iu)->getName();
       }
       list << ')';
       return list.str();
     }
   }
   // wasn't found in xor list
   if (!a->getFlag().empty()) {
     list << "(" << a->flagStartChar() << a->getFlag() << ' ' <<
       a->nameStartString() << a->getName() << ')';
   }
   return list.str();
 }
void TCLAP::ZshCompletionOutput::printArg (Arg * it) inline protected
Definition at line 164 of file ZshCompletionOutput.h.
References TCLAP::Arg::acceptsMultipleValues(), common, TCLAP::Arg::getName(), and TCLAP::Arg::isRequired().
Referenced by usage().
 {
   static int count = 1;
   std::cout << " \\" << std::endl << "  '";
   if ( a->acceptsMultipleValues() )
     std::cout << '*';
   else
     std::cout << count++;
   std::cout << ':';
   if ( !a->isRequired() )
     std::cout << ':';
   std::cout << a->getName() << ':';
   std::map<std::string, std::string>::iterator compArg = common.find(a->getName());
   if ( compArg != common.end() )
   {
     std::cout << compArg->second;
   }
   else
   {
     std::cout << "_guard \"^-*\" " << a->getName();
   }
   std::cout << '\'';
 }
void TCLAP::ZshCompletionOutput::printOption (Arg * it, std::string mutex) inline protected
Definition at line 190 of file ZshCompletionOutput.h.
References common, TCLAP::Arg::flagStartChar(), TCLAP::Arg::getDescription(), TCLAP::Arg::getFlag(), TCLAP::Arg::getName(), TCLAP::Arg::isValueRequired(), TCLAP::Arg::nameStartString(), quoteSpecialChars(), TCLAP::Arg::shortID(), and theDelimiter.
Referenced by usage().
 {
   std::string flag = a->flagStartChar() + a->getFlag();
   std::string name = a->nameStartString() + a->getName();
   std::string desc = a->getDescription();
   // remove full stop and capitalisation from description as
   // this is the convention for zsh function
   if (!desc.compare(0, 12, "(required)  "))
   {
     desc.erase(0, 12);
   }
   if (!desc.compare(0, 15, "(OR required)  "))
   {
     desc.erase(0, 15);
   }
   size_t len = desc.length();
   if (len && desc.at(--len) == '.')
   {
     desc.erase(len);
   }
   if (len)
   {
     desc.replace(0, 1, 1, tolower(desc.at(0)));
   }
   std::cout << " \\" << std::endl << "  '" << mutex;
   if ( a->getFlag().empty() )
   {
     std::cout << name;
   }
   else
   {
     std::cout << "'{" << flag << ',' << name << "}'";
   }
   if ( theDelimiter == '=' && a->isValueRequired() )
     std::cout << "=-";
   quoteSpecialChars(desc);
   std::cout << '[' << desc << ']';
   if ( a->isValueRequired() )
   {
     std::string arg = a->shortID();
     arg.erase(0, arg.find_last_of(theDelimiter) + 1);
     if ( arg.at(arg.length()-1) == ']' )
       arg.erase(arg.length()-1);
     if ( arg.at(arg.length()-1) == ']' )
     {
       arg.erase(arg.length()-1);
     }
     if ( arg.at(0) == '<' )
     {
       arg.erase(arg.length()-1);
       arg.erase(0, 1);
     }
     size_t p = arg.find('|');
     if ( p != std::string::npos )
     {
       do
       {
         arg.replace(p, 1, 1, ' ');
       }
       while ( (p = arg.find_first_of('|', p)) != std::string::npos );
       quoteSpecialChars(arg);
       std::cout << ": :(" << arg << ')';
     }
     else
     {
       std::cout << ':' << arg;
       std::map<std::string, std::string>::iterator compArg = common.find(arg);
       if ( compArg != common.end() )
       {
         std::cout << ':' << compArg->second;
       }
     }
   }
   std::cout << '\'';
 }
void TCLAP::ZshCompletionOutput::quoteSpecialChars (std::string & s) inline protected
Definition at line 136 of file ZshCompletionOutput.h.
Referenced by printOption().
 {
   size_t idx = s.find_last_of(':');
   while ( idx != std::string::npos )
   {
     s.insert(idx, 1, '\\');
     idx = s.find_last_of(':', idx);
   }
   idx = s.find_last_of('\'');
   while ( idx != std::string::npos )
   {
     s.insert(idx, "'\\'");
     if (idx == 0)
       idx = std::string::npos;
     else
       idx = s.find_last_of('\'', --idx);
   }
 }
void TCLAP::ZshCompletionOutput::usage (CmdLineInterface & c) inline virtual
Prints the usage to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 106 of file ZshCompletionOutput.h.
References basename(), TCLAP::CmdLineInterface::getArgList(), TCLAP::CmdLineInterface::getDelimiter(), getMutexList(), TCLAP::CmdLineInterface::getProgramName(), TCLAP::CmdLineInterface::getVersion(), printArg(), printOption(), and theDelimiter.
 {
   std::list<Arg*> argList = _cmd.getArgList();
   std::string progName = _cmd.getProgramName();
   std::string xversion = _cmd.getVersion();
   theDelimiter = _cmd.getDelimiter();
   basename(progName);
   std::cout << "#compdef " << progName << std::endl << std::endl <<
     "# " << progName << " version " << _cmd.getVersion() << std::endl << std::endl <<
     "_arguments -s -S";
   for (ArgListIterator it = argList.begin(); it != argList.end(); it++)
   {
     if ( (*it)->shortID().at(0) == '<' )
       printArg((*it));
     else if ( (*it)->getFlag() != "-" )
       printOption((*it), getMutexList(_cmd, *it));
   }
   std::cout << std::endl;
 }
void TCLAP::ZshCompletionOutput::version (CmdLineInterface & c) inline virtual
Prints the version to stdout.
Can be overridden to produce alternative behavior.
Parameters
c - The CmdLine object the output is generated for.
Implements TCLAP::CmdLineOutput.
Definition at line 101 of file ZshCompletionOutput.h.
References TCLAP::CmdLineInterface::getVersion().
 {
   std::cout << _cmd.getVersion() << std::endl;
 }
Member Data Documentation
std::map<std::string, std::string> TCLAP::ZshCompletionOutput::common protected
Definition at line 82 of file ZshCompletionOutput.h.
Referenced by printArg(), printOption(), and ZshCompletionOutput().
char TCLAP::ZshCompletionOutput::theDelimiter protected
Definition at line 83 of file ZshCompletionOutput.h.
Referenced by printOption(), and usage().
The documentation for this class was generated from the following file:
ZshCompletionOutput.h